/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.scheduler.model;

import com.finbourne.sdk.services.scheduler.model.Notification;
import com.finbourne.sdk.services.scheduler.model.ResourceId;
import com.finbourne.sdk.services.scheduler.model.Trigger;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Schedule
 */
@JsonPropertyOrder({
  ScheduleDefinition.JSON_PROPERTY_SCHEDULE_IDENTIFIER,
  ScheduleDefinition.JSON_PROPERTY_JOB_ID,
  ScheduleDefinition.JSON_PROPERTY_NAME,
  ScheduleDefinition.JSON_PROPERTY_DESCRIPTION,
  ScheduleDefinition.JSON_PROPERTY_AUTHOR,
  ScheduleDefinition.JSON_PROPERTY_OWNER,
  ScheduleDefinition.JSON_PROPERTY_USE_AS_AUTH,
  ScheduleDefinition.JSON_PROPERTY_ARGUMENTS,
  ScheduleDefinition.JSON_PROPERTY_TRIGGER,
  ScheduleDefinition.JSON_PROPERTY_NOTIFICATIONS,
  ScheduleDefinition.JSON_PROPERTY_ENABLED
})

public class ScheduleDefinition {
  public static final String JSON_PROPERTY_SCHEDULE_IDENTIFIER = "scheduleIdentifier";
  @JsonProperty(JSON_PROPERTY_SCHEDULE_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private ResourceId scheduleIdentifier;

  public static final String JSON_PROPERTY_JOB_ID = "jobId";
  @JsonProperty(JSON_PROPERTY_JOB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private ResourceId jobId;

  public static final String JSON_PROPERTY_NAME = "name";
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String description;

  public static final String JSON_PROPERTY_AUTHOR = "author";
  @JsonProperty(JSON_PROPERTY_AUTHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String author;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String owner;

  public static final String JSON_PROPERTY_USE_AS_AUTH = "useAsAuth";
  @JsonProperty(JSON_PROPERTY_USE_AS_AUTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String useAsAuth;

  public static final String JSON_PROPERTY_ARGUMENTS = "arguments";
  @JsonProperty(JSON_PROPERTY_ARGUMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Map<String, String> arguments;

  public static final String JSON_PROPERTY_TRIGGER = "trigger";
  @JsonProperty(JSON_PROPERTY_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Trigger trigger;

  public static final String JSON_PROPERTY_NOTIFICATIONS = "notifications";
  @JsonProperty(JSON_PROPERTY_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<Notification> notifications;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Boolean enabled;

  public ScheduleDefinition() {
  }

  public ScheduleDefinition scheduleIdentifier(ResourceId scheduleIdentifier) {
    this.scheduleIdentifier = scheduleIdentifier;
    return this;
  }

  /**
   * Get scheduleIdentifier
   * @return scheduleIdentifier
   */
  @javax.annotation.Nonnull
  public ResourceId getScheduleIdentifier() {
    return scheduleIdentifier;
  }

  public void setScheduleIdentifier(ResourceId scheduleIdentifier) {
    this.scheduleIdentifier = scheduleIdentifier;
  }


  public ScheduleDefinition jobId(ResourceId jobId) {
    this.jobId = jobId;
    return this;
  }

  /**
   * Get jobId
   * @return jobId
   */
  @javax.annotation.Nullable
  public ResourceId getJobId() {
    return jobId;
  }

  public void setJobId(ResourceId jobId) {
    this.jobId = jobId;
  }


  public ScheduleDefinition name(String name) {
    this.name = name;
    return this;
  }

  /**
   * A display name for this Schedule
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public ScheduleDefinition description(String description) {
    this.description = description;
    return this;
  }

  /**
   * A description of the Schedule
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public ScheduleDefinition author(String author) {
    this.author = author;
    return this;
  }

  /**
   * Name of the author of this schedule
   * @return author
   */
  @javax.annotation.Nullable
  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }


  public ScheduleDefinition owner(String owner) {
    this.owner = owner;
    return this;
  }

  /**
   * Name of owner of this schedule
   * @return owner
   */
  @javax.annotation.Nullable
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }


  public ScheduleDefinition useAsAuth(String useAsAuth) {
    this.useAsAuth = useAsAuth;
    return this;
  }

  /**
   * User to runs schedule when automatically run and authenticates  requests in the schedule
   * @return useAsAuth
   */
  @javax.annotation.Nullable
  public String getUseAsAuth() {
    return useAsAuth;
  }

  public void setUseAsAuth(String useAsAuth) {
    this.useAsAuth = useAsAuth;
  }


  public ScheduleDefinition arguments(Map<String, String> arguments) {
    this.arguments = arguments;
    return this;
  }

  public ScheduleDefinition putArgumentsItem(String key, String argumentsItem) {
    if (this.arguments == null) {
      this.arguments = new HashMap<>();
    }
    this.arguments.put(key, argumentsItem);
    return this;
  }

  /**
   * All arguments specified by this Schedule that will be passed in to the Job
   * @return arguments
   */
  @javax.annotation.Nullable
  public Map<String, String> getArguments() {
    return arguments;
  }

  public void setArguments(Map<String, String> arguments) {
    this.arguments = arguments;
  }


  public ScheduleDefinition trigger(Trigger trigger) {
    this.trigger = trigger;
    return this;
  }

  /**
   * Get trigger
   * @return trigger
   */
  @javax.annotation.Nullable
  public Trigger getTrigger() {
    return trigger;
  }

  public void setTrigger(Trigger trigger) {
    this.trigger = trigger;
  }


  public ScheduleDefinition notifications(List<Notification> notifications) {
    this.notifications = notifications;
    return this;
  }

  public ScheduleDefinition addNotificationsItem(Notification notificationsItem) {
    if (this.notifications == null) {
      this.notifications = new ArrayList<>();
    }
    this.notifications.add(notificationsItem);
    return this;
  }

  /**
   * Notifications for this Schedule
   * @return notifications
   */
  @javax.annotation.Nullable
  public List<Notification> getNotifications() {
    return notifications;
  }

  public void setNotifications(List<Notification> notifications) {
    this.notifications = notifications;
  }


  public ScheduleDefinition enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * The status of this schedule
   * @return enabled
   */
  @javax.annotation.Nullable
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduleDefinition scheduleDefinition = (ScheduleDefinition) o;
    return Objects.equals(this.scheduleIdentifier, scheduleDefinition.scheduleIdentifier) &&
        Objects.equals(this.jobId, scheduleDefinition.jobId) &&
        Objects.equals(this.name, scheduleDefinition.name) &&
        Objects.equals(this.description, scheduleDefinition.description) &&
        Objects.equals(this.author, scheduleDefinition.author) &&
        Objects.equals(this.owner, scheduleDefinition.owner) &&
        Objects.equals(this.useAsAuth, scheduleDefinition.useAsAuth) &&
        Objects.equals(this.arguments, scheduleDefinition.arguments) &&
        Objects.equals(this.trigger, scheduleDefinition.trigger) &&
        Objects.equals(this.notifications, scheduleDefinition.notifications) &&
        Objects.equals(this.enabled, scheduleDefinition.enabled);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(scheduleIdentifier, jobId, name, description, author, owner, useAsAuth, arguments, trigger, notifications, enabled);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduleDefinition {\n");
    sb.append("    scheduleIdentifier: ").append(toIndentedString(scheduleIdentifier)).append("\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    useAsAuth: ").append(toIndentedString(useAsAuth)).append("\n");
    sb.append("    arguments: ").append(toIndentedString(arguments)).append("\n");
    sb.append("    trigger: ").append(toIndentedString(trigger)).append("\n");
    sb.append("    notifications: ").append(toIndentedString(notifications)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of ScheduleDefinition given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ScheduleDefinition
   * @throws java.io.IOException if the JSON string is invalid with respect to ScheduleDefinition
   */
  public static ScheduleDefinition fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, ScheduleDefinition.class);
  }

  /**
   * Convert an instance of ScheduleDefinition to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
