/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.horizon.model;

import com.finbourne.sdk.services.horizon.model.OpenFigiData;
import com.finbourne.sdk.services.horizon.model.PermIdData;
import java.io.IOException;
import java.util.Arrays;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * A packed WebAPI OpenFigi DTO and PermId DTO
 */
@JsonPropertyOrder({
  OpenFigiPermIdResult.JSON_PROPERTY_OPEN_FIGI_RESULT,
  OpenFigiPermIdResult.JSON_PROPERTY_PERM_ID_RESULT
})

public class OpenFigiPermIdResult {
  public static final String JSON_PROPERTY_OPEN_FIGI_RESULT = "openFigiResult";
  @JsonProperty(JSON_PROPERTY_OPEN_FIGI_RESULT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OpenFigiData openFigiResult;

  public static final String JSON_PROPERTY_PERM_ID_RESULT = "permIdResult";
  @JsonProperty(JSON_PROPERTY_PERM_ID_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private PermIdData permIdResult;

  public OpenFigiPermIdResult() {
  }

  public OpenFigiPermIdResult openFigiResult(OpenFigiData openFigiResult) {
    this.openFigiResult = openFigiResult;
    return this;
  }

  /**
   * Get openFigiResult
   * @return openFigiResult
   */
  @javax.annotation.Nonnull
  public OpenFigiData getOpenFigiResult() {
    return openFigiResult;
  }

  public void setOpenFigiResult(OpenFigiData openFigiResult) {
    this.openFigiResult = openFigiResult;
  }


  public OpenFigiPermIdResult permIdResult(PermIdData permIdResult) {
    this.permIdResult = permIdResult;
    return this;
  }

  /**
   * Get permIdResult
   * @return permIdResult
   */
  @javax.annotation.Nullable
  public PermIdData getPermIdResult() {
    return permIdResult;
  }

  public void setPermIdResult(PermIdData permIdResult) {
    this.permIdResult = permIdResult;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenFigiPermIdResult openFigiPermIdResult = (OpenFigiPermIdResult) o;
    return Objects.equals(this.openFigiResult, openFigiPermIdResult.openFigiResult) &&
        Objects.equals(this.permIdResult, openFigiPermIdResult.permIdResult);
  }

  @Override
 public int hashCode() {
    return Objects.hash(openFigiResult, permIdResult);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenFigiPermIdResult {\n");
    sb.append("    openFigiResult: ").append(toIndentedString(openFigiResult)).append("\n");
    sb.append("    permIdResult: ").append(toIndentedString(permIdResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of OpenFigiPermIdResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OpenFigiPermIdResult
   * @throws java.io.IOException if the JSON string is invalid with respect to OpenFigiPermIdResult
   */
  public static OpenFigiPermIdResult fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, OpenFigiPermIdResult.class);
  }

  /**
   * Convert an instance of OpenFigiPermIdResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
