/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.horizon.model;

import com.finbourne.sdk.services.horizon.model.ProcessSummary;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Required information for each process
 */
@JsonPropertyOrder({
  ProcessInformation.JSON_PROPERTY_DOMAIN,
  ProcessInformation.JSON_PROPERTY_PROCESS_NAME,
  ProcessInformation.JSON_PROPERTY_RUN_ID,
  ProcessInformation.JSON_PROPERTY_START_TIME,
  ProcessInformation.JSON_PROPERTY_DATA_ACTION,
  ProcessInformation.JSON_PROPERTY_SCHEMA_VERSION,
  ProcessInformation.JSON_PROPERTY_USER_ID,
  ProcessInformation.JSON_PROPERTY_PROCESS_SUMMARY
})

public class ProcessInformation {
  public static final String JSON_PROPERTY_DOMAIN = "domain";
  @JsonProperty(JSON_PROPERTY_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String domain;

  public static final String JSON_PROPERTY_PROCESS_NAME = "processName";
  @JsonProperty(JSON_PROPERTY_PROCESS_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String processName;

  public static final String JSON_PROPERTY_RUN_ID = "runId";
  @JsonProperty(JSON_PROPERTY_RUN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String runId;

  public static final String JSON_PROPERTY_START_TIME = "startTime";
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OffsetDateTime startTime;

  public static final String JSON_PROPERTY_DATA_ACTION = "dataAction";
  @JsonProperty(JSON_PROPERTY_DATA_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String dataAction;

  public static final String JSON_PROPERTY_SCHEMA_VERSION = "schemaVersion";
  @JsonProperty(JSON_PROPERTY_SCHEMA_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String schemaVersion;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String userId;

  public static final String JSON_PROPERTY_PROCESS_SUMMARY = "processSummary";
  @JsonProperty(JSON_PROPERTY_PROCESS_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private ProcessSummary processSummary;

  public ProcessInformation() {
  }

  public ProcessInformation domain(String domain) {
    this.domain = domain;
    return this;
  }

  /**
   * 
   * @return domain
   */
  @javax.annotation.Nonnull
  public String getDomain() {
    return domain;
  }

  public void setDomain(String domain) {
    this.domain = domain;
  }


  public ProcessInformation processName(String processName) {
    this.processName = processName;
    return this;
  }

  /**
   * 
   * @return processName
   */
  @javax.annotation.Nonnull
  public String getProcessName() {
    return processName;
  }

  public void setProcessName(String processName) {
    this.processName = processName;
  }


  public ProcessInformation runId(String runId) {
    this.runId = runId;
    return this;
  }

  /**
   * 
   * @return runId
   */
  @javax.annotation.Nonnull
  public String getRunId() {
    return runId;
  }

  public void setRunId(String runId) {
    this.runId = runId;
  }


  public ProcessInformation startTime(OffsetDateTime startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * 
   * @return startTime
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }


  public ProcessInformation dataAction(String dataAction) {
    this.dataAction = dataAction;
    return this;
  }

  /**
   * 
   * @return dataAction
   */
  @javax.annotation.Nonnull
  public String getDataAction() {
    return dataAction;
  }

  public void setDataAction(String dataAction) {
    this.dataAction = dataAction;
  }


  public ProcessInformation schemaVersion(String schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

  /**
   * 
   * @return schemaVersion
   */
  @javax.annotation.Nullable
  public String getSchemaVersion() {
    return schemaVersion;
  }

  public void setSchemaVersion(String schemaVersion) {
    this.schemaVersion = schemaVersion;
  }


  public ProcessInformation userId(String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * 
   * @return userId
   */
  @javax.annotation.Nonnull
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  public ProcessInformation processSummary(ProcessSummary processSummary) {
    this.processSummary = processSummary;
    return this;
  }

  /**
   * Get processSummary
   * @return processSummary
   */
  @javax.annotation.Nullable
  public ProcessSummary getProcessSummary() {
    return processSummary;
  }

  public void setProcessSummary(ProcessSummary processSummary) {
    this.processSummary = processSummary;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessInformation processInformation = (ProcessInformation) o;
    return Objects.equals(this.domain, processInformation.domain) &&
        Objects.equals(this.processName, processInformation.processName) &&
        Objects.equals(this.runId, processInformation.runId) &&
        Objects.equals(this.startTime, processInformation.startTime) &&
        Objects.equals(this.dataAction, processInformation.dataAction) &&
        Objects.equals(this.schemaVersion, processInformation.schemaVersion) &&
        Objects.equals(this.userId, processInformation.userId) &&
        Objects.equals(this.processSummary, processInformation.processSummary);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(domain, processName, runId, startTime, dataAction, schemaVersion, userId, processSummary);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessInformation {\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    processName: ").append(toIndentedString(processName)).append("\n");
    sb.append("    runId: ").append(toIndentedString(runId)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    dataAction: ").append(toIndentedString(dataAction)).append("\n");
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    processSummary: ").append(toIndentedString(processSummary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of ProcessInformation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ProcessInformation
   * @throws java.io.IOException if the JSON string is invalid with respect to ProcessInformation
   */
  public static ProcessInformation fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, ProcessInformation.class);
  }

  /**
   * Convert an instance of ProcessInformation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
