/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.horizon.model;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * record containing details of a transaction payload.
 */
@JsonPropertyOrder({
  TransactionPayloadResponse.JSON_PROPERTY_COLUMNS,
  TransactionPayloadResponse.JSON_PROPERTY_VALUES,
  TransactionPayloadResponse.JSON_PROPERTY_RAW_CSV_ROW
})

public class TransactionPayloadResponse {
  public static final String JSON_PROPERTY_COLUMNS = "columns";
  @JsonProperty(JSON_PROPERTY_COLUMNS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<String> columns = new ArrayList<>();

  public static final String JSON_PROPERTY_VALUES = "values";
  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private Map<String, String> values = new HashMap<>();

  public static final String JSON_PROPERTY_RAW_CSV_ROW = "rawCsvRow";
  @JsonProperty(JSON_PROPERTY_RAW_CSV_ROW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String rawCsvRow;

  public TransactionPayloadResponse() {
  }

  public TransactionPayloadResponse columns(List<String> columns) {
    this.columns = columns;
    return this;
  }

  public TransactionPayloadResponse addColumnsItem(String columnsItem) {
    if (this.columns == null) {
      this.columns = new ArrayList<>();
    }
    this.columns.add(columnsItem);
    return this;
  }

  /**
   * Get columns
   * @return columns
   */
  @javax.annotation.Nonnull
  public List<String> getColumns() {
    return columns;
  }

  public void setColumns(List<String> columns) {
    this.columns = columns;
  }


  public TransactionPayloadResponse values(Map<String, String> values) {
    this.values = values;
    return this;
  }

  public TransactionPayloadResponse putValuesItem(String key, String valuesItem) {
    if (this.values == null) {
      this.values = new HashMap<>();
    }
    this.values.put(key, valuesItem);
    return this;
  }

  /**
   * Get values
   * @return values
   */
  @javax.annotation.Nonnull
  public Map<String, String> getValues() {
    return values;
  }

  public void setValues(Map<String, String> values) {
    this.values = values;
  }


  public TransactionPayloadResponse rawCsvRow(String rawCsvRow) {
    this.rawCsvRow = rawCsvRow;
    return this;
  }

  /**
   * Get rawCsvRow
   * @return rawCsvRow
   */
  @javax.annotation.Nonnull
  public String getRawCsvRow() {
    return rawCsvRow;
  }

  public void setRawCsvRow(String rawCsvRow) {
    this.rawCsvRow = rawCsvRow;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionPayloadResponse transactionPayloadResponse = (TransactionPayloadResponse) o;
    return Objects.equals(this.columns, transactionPayloadResponse.columns) &&
        Objects.equals(this.values, transactionPayloadResponse.values) &&
        Objects.equals(this.rawCsvRow, transactionPayloadResponse.rawCsvRow);
  }

  @Override
 public int hashCode() {
    return Objects.hash(columns, values, rawCsvRow);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionPayloadResponse {\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    rawCsvRow: ").append(toIndentedString(rawCsvRow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of TransactionPayloadResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TransactionPayloadResponse
   * @throws java.io.IOException if the JSON string is invalid with respect to TransactionPayloadResponse
   */
  public static TransactionPayloadResponse fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, TransactionPayloadResponse.class);
  }

  /**
   * Convert an instance of TransactionPayloadResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
