/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.horizon.model;

import com.finbourne.sdk.services.horizon.model.LusidEntity;
import java.io.IOException;
import java.util.Arrays;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Denormalised information about vendors, the products they provide and the LUSID entity types they can be used to populate.
 */
@JsonPropertyOrder({
  VendorProduct.JSON_PROPERTY_VENDOR_NAME,
  VendorProduct.JSON_PROPERTY_PRODUCT_NAME,
  VendorProduct.JSON_PROPERTY_VENDOR_PRODUCT_KEY,
  VendorProduct.JSON_PROPERTY_LUSID_ENTITY
})

public class VendorProduct {
  public static final String JSON_PROPERTY_VENDOR_NAME = "vendorName";
  @JsonProperty(JSON_PROPERTY_VENDOR_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String vendorName;

  public static final String JSON_PROPERTY_PRODUCT_NAME = "productName";
  @JsonProperty(JSON_PROPERTY_PRODUCT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String productName;

  public static final String JSON_PROPERTY_VENDOR_PRODUCT_KEY = "vendorProductKey";
  @JsonProperty(JSON_PROPERTY_VENDOR_PRODUCT_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String vendorProductKey;

  public static final String JSON_PROPERTY_LUSID_ENTITY = "lusidEntity";
  @JsonProperty(JSON_PROPERTY_LUSID_ENTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private LusidEntity lusidEntity;

  public VendorProduct() {
  }

  public VendorProduct vendorName(String vendorName) {
    this.vendorName = vendorName;
    return this;
  }

  /**
   * Get vendorName
   * @return vendorName
   */
  @javax.annotation.Nonnull
  public String getVendorName() {
    return vendorName;
  }

  public void setVendorName(String vendorName) {
    this.vendorName = vendorName;
  }


  public VendorProduct productName(String productName) {
    this.productName = productName;
    return this;
  }

  /**
   * Get productName
   * @return productName
   */
  @javax.annotation.Nonnull
  public String getProductName() {
    return productName;
  }

  public void setProductName(String productName) {
    this.productName = productName;
  }


  public VendorProduct vendorProductKey(String vendorProductKey) {
    this.vendorProductKey = vendorProductKey;
    return this;
  }

  /**
   * Get vendorProductKey
   * @return vendorProductKey
   */
  @javax.annotation.Nonnull
  public String getVendorProductKey() {
    return vendorProductKey;
  }

  public void setVendorProductKey(String vendorProductKey) {
    this.vendorProductKey = vendorProductKey;
  }


  public VendorProduct lusidEntity(LusidEntity lusidEntity) {
    this.lusidEntity = lusidEntity;
    return this;
  }

  /**
   * Get lusidEntity
   * @return lusidEntity
   */
  @javax.annotation.Nonnull
  public LusidEntity getLusidEntity() {
    return lusidEntity;
  }

  public void setLusidEntity(LusidEntity lusidEntity) {
    this.lusidEntity = lusidEntity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VendorProduct vendorProduct = (VendorProduct) o;
    return Objects.equals(this.vendorName, vendorProduct.vendorName) &&
        Objects.equals(this.productName, vendorProduct.productName) &&
        Objects.equals(this.vendorProductKey, vendorProduct.vendorProductKey) &&
        Objects.equals(this.lusidEntity, vendorProduct.lusidEntity);
  }

  @Override
 public int hashCode() {
    return Objects.hash(vendorName, productName, vendorProductKey, lusidEntity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VendorProduct {\n");
    sb.append("    vendorName: ").append(toIndentedString(vendorName)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    vendorProductKey: ").append(toIndentedString(vendorProductKey)).append("\n");
    sb.append("    lusidEntity: ").append(toIndentedString(lusidEntity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of VendorProduct given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of VendorProduct
   * @throws java.io.IOException if the JSON string is invalid with respect to VendorProduct
   */
  public static VendorProduct fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, VendorProduct.class);
  }

  /**
   * Convert an instance of VendorProduct to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
