/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.horizon.model;

import com.finbourne.sdk.services.horizon.model.WorkflowRunResultResponse;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * A run&#39;s status and the result values it published, which is what the Workflow AQS polls while it waits for an integration it started to finish.
 */
@JsonPropertyOrder({
  WorkflowRunResultsResponse.JSON_PROPERTY_RUN_ID,
  WorkflowRunResultsResponse.JSON_PROPERTY_INSTANCE_ID,
  WorkflowRunResultsResponse.JSON_PROPERTY_STATUS,
  WorkflowRunResultsResponse.JSON_PROPERTY_QUEUED_AT,
  WorkflowRunResultsResponse.JSON_PROPERTY_STARTED_AT,
  WorkflowRunResultsResponse.JSON_PROPERTY_COMPLETED_AT,
  WorkflowRunResultsResponse.JSON_PROPERTY_ATTEMPT,
  WorkflowRunResultsResponse.JSON_PROPERTY_REPORTS_TO_WORKFLOW,
  WorkflowRunResultsResponse.JSON_PROPERTY_RESULTS
})

public class WorkflowRunResultsResponse {
  public static final String JSON_PROPERTY_RUN_ID = "runId";
  @JsonProperty(JSON_PROPERTY_RUN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String runId;

  public static final String JSON_PROPERTY_INSTANCE_ID = "instanceId";
  @JsonProperty(JSON_PROPERTY_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String instanceId;

  public static final String JSON_PROPERTY_STATUS = "status";
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String status;

  public static final String JSON_PROPERTY_QUEUED_AT = "queuedAt";
  @JsonProperty(JSON_PROPERTY_QUEUED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime queuedAt;

  public static final String JSON_PROPERTY_STARTED_AT = "startedAt";
  @JsonProperty(JSON_PROPERTY_STARTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime startedAt;

  public static final String JSON_PROPERTY_COMPLETED_AT = "completedAt";
  @JsonProperty(JSON_PROPERTY_COMPLETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime completedAt;

  public static final String JSON_PROPERTY_ATTEMPT = "attempt";
  @JsonProperty(JSON_PROPERTY_ATTEMPT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private Integer attempt;

  public static final String JSON_PROPERTY_REPORTS_TO_WORKFLOW = "reportsToWorkflow";
  @JsonProperty(JSON_PROPERTY_REPORTS_TO_WORKFLOW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private Boolean reportsToWorkflow;

  public static final String JSON_PROPERTY_RESULTS = "results";
  @JsonProperty(JSON_PROPERTY_RESULTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<WorkflowRunResultResponse> results = new ArrayList<>();

  public WorkflowRunResultsResponse() {
  }

  public WorkflowRunResultsResponse runId(String runId) {
    this.runId = runId;
    return this;
  }

  /**
   * The run these results belong to, as returned by the execute endpoint.
   * @return runId
   */
  @javax.annotation.Nonnull
  public String getRunId() {
    return runId;
  }

  public void setRunId(String runId) {
    this.runId = runId;
  }


  public WorkflowRunResultsResponse instanceId(String instanceId) {
    this.instanceId = instanceId;
    return this;
  }

  /**
   * The instance that ran.
   * @return instanceId
   */
  @javax.annotation.Nonnull
  public String getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }


  public WorkflowRunResultsResponse status(String status) {
    this.status = status;
    return this;
  }

  /**
   * The run&#39;s status, reported exactly as the runs endpoint reports it: Queued, Started, Completed, Errored or Interrupted. A caller waiting for the run to finish is waiting for one of the last three.
   * @return status
   */
  @javax.annotation.Nonnull
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  public WorkflowRunResultsResponse queuedAt(OffsetDateTime queuedAt) {
    this.queuedAt = queuedAt;
    return this;
  }

  /**
   * Get queuedAt
   * @return queuedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getQueuedAt() {
    return queuedAt;
  }

  public void setQueuedAt(OffsetDateTime queuedAt) {
    this.queuedAt = queuedAt;
  }


  public WorkflowRunResultsResponse startedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
    return this;
  }

  /**
   * Get startedAt
   * @return startedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
  }


  public WorkflowRunResultsResponse completedAt(OffsetDateTime completedAt) {
    this.completedAt = completedAt;
    return this;
  }

  /**
   * Null until the run reaches a terminal status.
   * @return completedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCompletedAt() {
    return completedAt;
  }

  public void setCompletedAt(OffsetDateTime completedAt) {
    this.completedAt = completedAt;
  }


  public WorkflowRunResultsResponse attempt(Integer attempt) {
    this.attempt = attempt;
    return this;
  }

  /**
   * Which attempt this run is, counting reruns of the same work.
   * @return attempt
   */
  @javax.annotation.Nonnull
  public Integer getAttempt() {
    return attempt;
  }

  public void setAttempt(Integer attempt) {
    this.attempt = attempt;
  }


  public WorkflowRunResultsResponse reportsToWorkflow(Boolean reportsToWorkflow) {
    this.reportsToWorkflow = reportsToWorkflow;
    return this;
  }

  /**
   * Whether this run was started by a Workflow task. False for a scheduled or file-triggered run, which publishes no results because nothing is waiting on them.
   * @return reportsToWorkflow
   */
  @javax.annotation.Nonnull
  public Boolean getReportsToWorkflow() {
    return reportsToWorkflow;
  }

  public void setReportsToWorkflow(Boolean reportsToWorkflow) {
    this.reportsToWorkflow = reportsToWorkflow;
  }


  public WorkflowRunResultsResponse results(List<WorkflowRunResultResponse> results) {
    this.results = results;
    return this;
  }

  public WorkflowRunResultsResponse addResultsItem(WorkflowRunResultResponse resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<>();
    }
    this.results.add(resultsItem);
    return this;
  }

  /**
   * One entry per field the instance declares, so the shape matches what the discovery endpoint promised when the worker was created. A declared field the run never published carries a null value.
   * @return results
   */
  @javax.annotation.Nonnull
  public List<WorkflowRunResultResponse> getResults() {
    return results;
  }

  public void setResults(List<WorkflowRunResultResponse> results) {
    this.results = results;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowRunResultsResponse workflowRunResultsResponse = (WorkflowRunResultsResponse) o;
    return Objects.equals(this.runId, workflowRunResultsResponse.runId) &&
        Objects.equals(this.instanceId, workflowRunResultsResponse.instanceId) &&
        Objects.equals(this.status, workflowRunResultsResponse.status) &&
        Objects.equals(this.queuedAt, workflowRunResultsResponse.queuedAt) &&
        Objects.equals(this.startedAt, workflowRunResultsResponse.startedAt) &&
        Objects.equals(this.completedAt, workflowRunResultsResponse.completedAt) &&
        Objects.equals(this.attempt, workflowRunResultsResponse.attempt) &&
        Objects.equals(this.reportsToWorkflow, workflowRunResultsResponse.reportsToWorkflow) &&
        Objects.equals(this.results, workflowRunResultsResponse.results);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(runId, instanceId, status, queuedAt, startedAt, completedAt, attempt, reportsToWorkflow, results);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowRunResultsResponse {\n");
    sb.append("    runId: ").append(toIndentedString(runId)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    queuedAt: ").append(toIndentedString(queuedAt)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    completedAt: ").append(toIndentedString(completedAt)).append("\n");
    sb.append("    attempt: ").append(toIndentedString(attempt)).append("\n");
    sb.append("    reportsToWorkflow: ").append(toIndentedString(reportsToWorkflow)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of WorkflowRunResultsResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WorkflowRunResultsResponse
   * @throws java.io.IOException if the JSON string is invalid with respect to WorkflowRunResultsResponse
   */
  public static WorkflowRunResultsResponse fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, WorkflowRunResultsResponse.class);
  }

  /**
   * Convert an instance of WorkflowRunResultsResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
