/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.identity.model;

import com.finbourne.sdk.services.identity.model.McpToolLuminescePayload;
import com.finbourne.sdk.services.identity.model.McpToolParameter;
import com.finbourne.sdk.services.identity.model.McpToolSchedulerPayload;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * The response representation of an MCP tool
 */
@JsonPropertyOrder({
  McpToolResponse.JSON_PROPERTY_SCOPE,
  McpToolResponse.JSON_PROPERTY_CODE,
  McpToolResponse.JSON_PROPERTY_NAME,
  McpToolResponse.JSON_PROPERTY_VERSION,
  McpToolResponse.JSON_PROPERTY_TITLE,
  McpToolResponse.JSON_PROPERTY_DESCRIPTION,
  McpToolResponse.JSON_PROPERTY_DESTRUCTIVE,
  McpToolResponse.JSON_PROPERTY_IDEMPOTENT,
  McpToolResponse.JSON_PROPERTY_OPEN_WORLD,
  McpToolResponse.JSON_PROPERTY_READ_ONLY,
  McpToolResponse.JSON_PROPERTY_PARAMETERS,
  McpToolResponse.JSON_PROPERTY_PAYLOAD_TYPE,
  McpToolResponse.JSON_PROPERTY_LUMINESCE_PAYLOAD,
  McpToolResponse.JSON_PROPERTY_SCHEDULER_PAYLOAD,
  McpToolResponse.JSON_PROPERTY_DESTRUCTIVE_ACTION_SUMMARY_TEMPLATE,
  McpToolResponse.JSON_PROPERTY_CREATED_AT,
  McpToolResponse.JSON_PROPERTY_CREATED_BY,
  McpToolResponse.JSON_PROPERTY_UPDATED_AT,
  McpToolResponse.JSON_PROPERTY_UPDATED_BY
})

public class McpToolResponse {
  public static final String JSON_PROPERTY_SCOPE = "scope";
  @JsonProperty(JSON_PROPERTY_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String scope;

  public static final String JSON_PROPERTY_CODE = "code";
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String code;

  public static final String JSON_PROPERTY_NAME = "name";
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String name;

  public static final String JSON_PROPERTY_VERSION = "version";
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Integer version;

  public static final String JSON_PROPERTY_TITLE = "title";
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String title;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String description;

  public static final String JSON_PROPERTY_DESTRUCTIVE = "destructive";
  @JsonProperty(JSON_PROPERTY_DESTRUCTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Boolean destructive;

  public static final String JSON_PROPERTY_IDEMPOTENT = "idempotent";
  @JsonProperty(JSON_PROPERTY_IDEMPOTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Boolean idempotent;

  public static final String JSON_PROPERTY_OPEN_WORLD = "openWorld";
  @JsonProperty(JSON_PROPERTY_OPEN_WORLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Boolean openWorld;

  public static final String JSON_PROPERTY_READ_ONLY = "readOnly";
  @JsonProperty(JSON_PROPERTY_READ_ONLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Boolean readOnly;

  public static final String JSON_PROPERTY_PARAMETERS = "parameters";
  @JsonProperty(JSON_PROPERTY_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<McpToolParameter> parameters;

  public static final String JSON_PROPERTY_PAYLOAD_TYPE = "payloadType";
  @JsonProperty(JSON_PROPERTY_PAYLOAD_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String payloadType;

  public static final String JSON_PROPERTY_LUMINESCE_PAYLOAD = "luminescePayload";
  @JsonProperty(JSON_PROPERTY_LUMINESCE_PAYLOAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private McpToolLuminescePayload luminescePayload;

  public static final String JSON_PROPERTY_SCHEDULER_PAYLOAD = "schedulerPayload";
  @JsonProperty(JSON_PROPERTY_SCHEDULER_PAYLOAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private McpToolSchedulerPayload schedulerPayload;

  public static final String JSON_PROPERTY_DESTRUCTIVE_ACTION_SUMMARY_TEMPLATE = "destructiveActionSummaryTemplate";
  @JsonProperty(JSON_PROPERTY_DESTRUCTIVE_ACTION_SUMMARY_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String destructiveActionSummaryTemplate;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_CREATED_BY = "createdBy";
  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String createdBy;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_UPDATED_BY = "updatedBy";
  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String updatedBy;

  public McpToolResponse() {
  }

  public McpToolResponse scope(String scope) {
    this.scope = scope;
    return this;
  }

  /**
   * The scope of the MCP tool
   * @return scope
   */
  @javax.annotation.Nullable
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }


  public McpToolResponse code(String code) {
    this.code = code;
    return this;
  }

  /**
   * The code of the MCP tool
   * @return code
   */
  @javax.annotation.Nullable
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }


  public McpToolResponse name(String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the MCP tool
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public McpToolResponse version(Integer version) {
    this.version = version;
    return this;
  }

  /**
   * The version number of this MCP tool
   * @return version
   */
  @javax.annotation.Nullable
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }


  public McpToolResponse title(String title) {
    this.title = title;
    return this;
  }

  /**
   * The title of the MCP tool
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  public McpToolResponse description(String description) {
    this.description = description;
    return this;
  }

  /**
   * The description of the MCP tool
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public McpToolResponse destructive(Boolean destructive) {
    this.destructive = destructive;
    return this;
  }

  /**
   * Whether the tool is destructive
   * @return destructive
   */
  @javax.annotation.Nullable
  public Boolean getDestructive() {
    return destructive;
  }

  public void setDestructive(Boolean destructive) {
    this.destructive = destructive;
  }


  public McpToolResponse idempotent(Boolean idempotent) {
    this.idempotent = idempotent;
    return this;
  }

  /**
   * Whether the tool is idempotent
   * @return idempotent
   */
  @javax.annotation.Nullable
  public Boolean getIdempotent() {
    return idempotent;
  }

  public void setIdempotent(Boolean idempotent) {
    this.idempotent = idempotent;
  }


  public McpToolResponse openWorld(Boolean openWorld) {
    this.openWorld = openWorld;
    return this;
  }

  /**
   * Whether the tool operates in open world
   * @return openWorld
   */
  @javax.annotation.Nullable
  public Boolean getOpenWorld() {
    return openWorld;
  }

  public void setOpenWorld(Boolean openWorld) {
    this.openWorld = openWorld;
  }


  public McpToolResponse readOnly(Boolean readOnly) {
    this.readOnly = readOnly;
    return this;
  }

  /**
   * Whether the tool is read-only
   * @return readOnly
   */
  @javax.annotation.Nullable
  public Boolean getReadOnly() {
    return readOnly;
  }

  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }


  public McpToolResponse parameters(List<McpToolParameter> parameters) {
    this.parameters = parameters;
    return this;
  }

  public McpToolResponse addParametersItem(McpToolParameter parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

  /**
   * The parameters for this MCP tool
   * @return parameters
   */
  @javax.annotation.Nullable
  public List<McpToolParameter> getParameters() {
    return parameters;
  }

  public void setParameters(List<McpToolParameter> parameters) {
    this.parameters = parameters;
  }


  public McpToolResponse payloadType(String payloadType) {
    this.payloadType = payloadType;
    return this;
  }

  /**
   * The type of payload (Luminesce or Scheduler)
   * @return payloadType
   */
  @javax.annotation.Nullable
  public String getPayloadType() {
    return payloadType;
  }

  public void setPayloadType(String payloadType) {
    this.payloadType = payloadType;
  }


  public McpToolResponse luminescePayload(McpToolLuminescePayload luminescePayload) {
    this.luminescePayload = luminescePayload;
    return this;
  }

  /**
   * Get luminescePayload
   * @return luminescePayload
   */
  @javax.annotation.Nullable
  public McpToolLuminescePayload getLuminescePayload() {
    return luminescePayload;
  }

  public void setLuminescePayload(McpToolLuminescePayload luminescePayload) {
    this.luminescePayload = luminescePayload;
  }


  public McpToolResponse schedulerPayload(McpToolSchedulerPayload schedulerPayload) {
    this.schedulerPayload = schedulerPayload;
    return this;
  }

  /**
   * Get schedulerPayload
   * @return schedulerPayload
   */
  @javax.annotation.Nullable
  public McpToolSchedulerPayload getSchedulerPayload() {
    return schedulerPayload;
  }

  public void setSchedulerPayload(McpToolSchedulerPayload schedulerPayload) {
    this.schedulerPayload = schedulerPayload;
  }


  public McpToolResponse destructiveActionSummaryTemplate(String destructiveActionSummaryTemplate) {
    this.destructiveActionSummaryTemplate = destructiveActionSummaryTemplate;
    return this;
  }

  /**
   * Template for human-readable destructive action summary. Uses {paramName} single-brace placeholders (e.g. \&quot;Delete file &#39;{filePath}&#39;\&quot;). Required when Destructive is true.
   * @return destructiveActionSummaryTemplate
   */
  @javax.annotation.Nullable
  public String getDestructiveActionSummaryTemplate() {
    return destructiveActionSummaryTemplate;
  }

  public void setDestructiveActionSummaryTemplate(String destructiveActionSummaryTemplate) {
    this.destructiveActionSummaryTemplate = destructiveActionSummaryTemplate;
  }


  public McpToolResponse createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * When the MCP tool was created
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public McpToolResponse createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * Who created the MCP tool
   * @return createdBy
   */
  @javax.annotation.Nullable
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }


  public McpToolResponse updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * When the MCP tool was last updated
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public McpToolResponse updatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

  /**
   * Who last updated the MCP tool
   * @return updatedBy
   */
  @javax.annotation.Nullable
  public String getUpdatedBy() {
    return updatedBy;
  }

  public void setUpdatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    McpToolResponse mcpToolResponse = (McpToolResponse) o;
    return Objects.equals(this.scope, mcpToolResponse.scope) &&
        Objects.equals(this.code, mcpToolResponse.code) &&
        Objects.equals(this.name, mcpToolResponse.name) &&
        Objects.equals(this.version, mcpToolResponse.version) &&
        Objects.equals(this.title, mcpToolResponse.title) &&
        Objects.equals(this.description, mcpToolResponse.description) &&
        Objects.equals(this.destructive, mcpToolResponse.destructive) &&
        Objects.equals(this.idempotent, mcpToolResponse.idempotent) &&
        Objects.equals(this.openWorld, mcpToolResponse.openWorld) &&
        Objects.equals(this.readOnly, mcpToolResponse.readOnly) &&
        Objects.equals(this.parameters, mcpToolResponse.parameters) &&
        Objects.equals(this.payloadType, mcpToolResponse.payloadType) &&
        Objects.equals(this.luminescePayload, mcpToolResponse.luminescePayload) &&
        Objects.equals(this.schedulerPayload, mcpToolResponse.schedulerPayload) &&
        Objects.equals(this.destructiveActionSummaryTemplate, mcpToolResponse.destructiveActionSummaryTemplate) &&
        Objects.equals(this.createdAt, mcpToolResponse.createdAt) &&
        Objects.equals(this.createdBy, mcpToolResponse.createdBy) &&
        Objects.equals(this.updatedAt, mcpToolResponse.updatedAt) &&
        Objects.equals(this.updatedBy, mcpToolResponse.updatedBy);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(scope, code, name, version, title, description, destructive, idempotent, openWorld, readOnly, parameters, payloadType, luminescePayload, schedulerPayload, destructiveActionSummaryTemplate, createdAt, createdBy, updatedAt, updatedBy);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class McpToolResponse {\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    destructive: ").append(toIndentedString(destructive)).append("\n");
    sb.append("    idempotent: ").append(toIndentedString(idempotent)).append("\n");
    sb.append("    openWorld: ").append(toIndentedString(openWorld)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    payloadType: ").append(toIndentedString(payloadType)).append("\n");
    sb.append("    luminescePayload: ").append(toIndentedString(luminescePayload)).append("\n");
    sb.append("    schedulerPayload: ").append(toIndentedString(schedulerPayload)).append("\n");
    sb.append("    destructiveActionSummaryTemplate: ").append(toIndentedString(destructiveActionSummaryTemplate)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of McpToolResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of McpToolResponse
   * @throws java.io.IOException if the JSON string is invalid with respect to McpToolResponse
   */
  public static McpToolResponse fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, McpToolResponse.class);
  }

  /**
   * Convert an instance of McpToolResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
