/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.identity.model;

import com.finbourne.sdk.services.identity.model.IpAddressDefinition;
import com.finbourne.sdk.services.identity.model.NetworkZonesApplyRules;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * The Client facing representation of a NetworkZone
 */
@JsonPropertyOrder({
  NetworkZoneDefinitionResponse.JSON_PROPERTY_CODE,
  NetworkZoneDefinitionResponse.JSON_PROPERTY_HIERARCHY,
  NetworkZoneDefinitionResponse.JSON_PROPERTY_DESCRIPTION,
  NetworkZoneDefinitionResponse.JSON_PROPERTY_CREATED_AT,
  NetworkZoneDefinitionResponse.JSON_PROPERTY_UPDATED_AT,
  NetworkZoneDefinitionResponse.JSON_PROPERTY_NETWORK_ZONE_I_PS,
  NetworkZoneDefinitionResponse.JSON_PROPERTY_ACTION,
  NetworkZoneDefinitionResponse.JSON_PROPERTY_APPLY_RULES,
  NetworkZoneDefinitionResponse.JSON_PROPERTY_CREATED_BY,
  NetworkZoneDefinitionResponse.JSON_PROPERTY_UPDATED_BY
})

public class NetworkZoneDefinitionResponse {
  public static final String JSON_PROPERTY_CODE = "code";
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String code;

  public static final String JSON_PROPERTY_HIERARCHY = "hierarchy";
  @JsonProperty(JSON_PROPERTY_HIERARCHY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Integer hierarchy;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String description;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_NETWORK_ZONE_I_PS = "networkZoneIPs";
  @JsonProperty(JSON_PROPERTY_NETWORK_ZONE_I_PS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<IpAddressDefinition> networkZoneIPs;

  public static final String JSON_PROPERTY_ACTION = "action";
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String action;

  public static final String JSON_PROPERTY_APPLY_RULES = "applyRules";
  @JsonProperty(JSON_PROPERTY_APPLY_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private NetworkZonesApplyRules applyRules;

  public static final String JSON_PROPERTY_CREATED_BY = "createdBy";
  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String createdBy;

  public static final String JSON_PROPERTY_UPDATED_BY = "updatedBy";
  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String updatedBy;

  public NetworkZoneDefinitionResponse() {
  }

  public NetworkZoneDefinitionResponse code(String code) {
    this.code = code;
    return this;
  }

  /**
   * The Network Zone Code
   * @return code
   */
  @javax.annotation.Nullable
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }


  public NetworkZoneDefinitionResponse hierarchy(Integer hierarchy) {
    this.hierarchy = hierarchy;
    return this;
  }

  /**
   * Hierarchy of the Network Zone
   * @return hierarchy
   */
  @javax.annotation.Nullable
  public Integer getHierarchy() {
    return hierarchy;
  }

  public void setHierarchy(Integer hierarchy) {
    this.hierarchy = hierarchy;
  }


  public NetworkZoneDefinitionResponse description(String description) {
    this.description = description;
    return this;
  }

  /**
   * The Description of the Network Zone
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public NetworkZoneDefinitionResponse createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Network Zone Creation timestamp
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public NetworkZoneDefinitionResponse updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Timestamp of the last update
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public NetworkZoneDefinitionResponse networkZoneIPs(List<IpAddressDefinition> networkZoneIPs) {
    this.networkZoneIPs = networkZoneIPs;
    return this;
  }

  public NetworkZoneDefinitionResponse addNetworkZoneIPsItem(IpAddressDefinition networkZoneIPsItem) {
    if (this.networkZoneIPs == null) {
      this.networkZoneIPs = new ArrayList<>();
    }
    this.networkZoneIPs.add(networkZoneIPsItem);
    return this;
  }

  /**
   * Network zone IP information (IPs and CIDR ranges)
   * @return networkZoneIPs
   */
  @javax.annotation.Nullable
  public List<IpAddressDefinition> getNetworkZoneIPs() {
    return networkZoneIPs;
  }

  public void setNetworkZoneIPs(List<IpAddressDefinition> networkZoneIPs) {
    this.networkZoneIPs = networkZoneIPs;
  }


  public NetworkZoneDefinitionResponse action(String action) {
    this.action = action;
    return this;
  }

  /**
   * Kind of action to apply when a request matches this Network Zone (Block/Allow/NoOp)
   * @return action
   */
  @javax.annotation.Nullable
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }


  public NetworkZoneDefinitionResponse applyRules(NetworkZonesApplyRules applyRules) {
    this.applyRules = applyRules;
    return this;
  }

  /**
   * Get applyRules
   * @return applyRules
   */
  @javax.annotation.Nullable
  public NetworkZonesApplyRules getApplyRules() {
    return applyRules;
  }

  public void setApplyRules(NetworkZonesApplyRules applyRules) {
    this.applyRules = applyRules;
  }


  public NetworkZoneDefinitionResponse createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * User Id that created the Network Zone
   * @return createdBy
   */
  @javax.annotation.Nullable
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }


  public NetworkZoneDefinitionResponse updatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

  /**
   * User Id of the last update on the Network Zone
   * @return updatedBy
   */
  @javax.annotation.Nullable
  public String getUpdatedBy() {
    return updatedBy;
  }

  public void setUpdatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkZoneDefinitionResponse networkZoneDefinitionResponse = (NetworkZoneDefinitionResponse) o;
    return Objects.equals(this.code, networkZoneDefinitionResponse.code) &&
        Objects.equals(this.hierarchy, networkZoneDefinitionResponse.hierarchy) &&
        Objects.equals(this.description, networkZoneDefinitionResponse.description) &&
        Objects.equals(this.createdAt, networkZoneDefinitionResponse.createdAt) &&
        Objects.equals(this.updatedAt, networkZoneDefinitionResponse.updatedAt) &&
        Objects.equals(this.networkZoneIPs, networkZoneDefinitionResponse.networkZoneIPs) &&
        Objects.equals(this.action, networkZoneDefinitionResponse.action) &&
        Objects.equals(this.applyRules, networkZoneDefinitionResponse.applyRules) &&
        Objects.equals(this.createdBy, networkZoneDefinitionResponse.createdBy) &&
        Objects.equals(this.updatedBy, networkZoneDefinitionResponse.updatedBy);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(code, hierarchy, description, createdAt, updatedAt, networkZoneIPs, action, applyRules, createdBy, updatedBy);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkZoneDefinitionResponse {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    hierarchy: ").append(toIndentedString(hierarchy)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    networkZoneIPs: ").append(toIndentedString(networkZoneIPs)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    applyRules: ").append(toIndentedString(applyRules)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of NetworkZoneDefinitionResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NetworkZoneDefinitionResponse
   * @throws java.io.IOException if the JSON string is invalid with respect to NetworkZoneDefinitionResponse
   */
  public static NetworkZoneDefinitionResponse fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, NetworkZoneDefinitionResponse.class);
  }

  /**
   * Convert an instance of NetworkZoneDefinitionResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
