/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.workflow.model;

import com.finbourne.sdk.services.workflow.model.VersionedTaskDefinitionId;
import java.io.IOException;
import java.util.Arrays;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Represents a parent-child relationship between two Task Definitions in a Workflow
 */
@JsonPropertyOrder({
  ChildTaskDefinitionEdge.JSON_PROPERTY_PARENT,
  ChildTaskDefinitionEdge.JSON_PROPERTY_CHILD
})

public class ChildTaskDefinitionEdge {
  public static final String JSON_PROPERTY_PARENT = "parent";
  @JsonProperty(JSON_PROPERTY_PARENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private VersionedTaskDefinitionId parent;

  public static final String JSON_PROPERTY_CHILD = "child";
  @JsonProperty(JSON_PROPERTY_CHILD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private VersionedTaskDefinitionId child;

  public ChildTaskDefinitionEdge() {
  }

  public ChildTaskDefinitionEdge parent(VersionedTaskDefinitionId parent) {
    this.parent = parent;
    return this;
  }

  /**
   * Get parent
   * @return parent
   */
  @javax.annotation.Nullable
  public VersionedTaskDefinitionId getParent() {
    return parent;
  }

  public void setParent(VersionedTaskDefinitionId parent) {
    this.parent = parent;
  }


  public ChildTaskDefinitionEdge child(VersionedTaskDefinitionId child) {
    this.child = child;
    return this;
  }

  /**
   * Get child
   * @return child
   */
  @javax.annotation.Nullable
  public VersionedTaskDefinitionId getChild() {
    return child;
  }

  public void setChild(VersionedTaskDefinitionId child) {
    this.child = child;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChildTaskDefinitionEdge childTaskDefinitionEdge = (ChildTaskDefinitionEdge) o;
    return Objects.equals(this.parent, childTaskDefinitionEdge.parent) &&
        Objects.equals(this.child, childTaskDefinitionEdge.child);
  }

  @Override
 public int hashCode() {
    return Objects.hash(parent, child);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChildTaskDefinitionEdge {\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    child: ").append(toIndentedString(child)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of ChildTaskDefinitionEdge given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ChildTaskDefinitionEdge
   * @throws java.io.IOException if the JSON string is invalid with respect to ChildTaskDefinitionEdge
   */
  public static ChildTaskDefinitionEdge fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, ChildTaskDefinitionEdge.class);
  }

  /**
   * Convert an instance of ChildTaskDefinitionEdge to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
