/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.workflow.model;

import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Configuration for a Worker that performs a GET against a given Url.
 */
@JsonPropertyOrder({
  HealthCheck.JSON_PROPERTY_TYPE,
  HealthCheck.JSON_PROPERTY_URL
})

public class HealthCheck {
  /**
   * The type of worker
   */
  public enum TypeEnum {
    HEALTH_CHECK("HealthCheck");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @com.fasterxml.jackson.annotation.JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @com.fasterxml.jackson.annotation.JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_TYPE = "type";
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private TypeEnum type;

  public static final String JSON_PROPERTY_URL = "url";
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private URI url;

  public HealthCheck() {
  }

  public HealthCheck type(TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * The type of worker
   * @return type
   */
  @javax.annotation.Nonnull
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  public HealthCheck url(URI url) {
    this.url = url;
    return this;
  }

  /**
   * The URL to check, eg: https://www.google.com/
   * @return url
   */
  @javax.annotation.Nonnull
  public URI getUrl() {
    return url;
  }

  public void setUrl(URI url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HealthCheck healthCheck = (HealthCheck) o;
    return Objects.equals(this.type, healthCheck.type) &&
        Objects.equals(this.url, healthCheck.url);
  }

  @Override
 public int hashCode() {
    return Objects.hash(type, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HealthCheck {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of HealthCheck given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of HealthCheck
   * @throws java.io.IOException if the JSON string is invalid with respect to HealthCheck
   */
  public static HealthCheck fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, HealthCheck.class);
  }

  /**
   * Convert an instance of HealthCheck to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
