/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.luminesce.model;

import java.io.IOException;
import java.util.Arrays;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Information about a case statement. A typical case statement would look like: CASE WHEN Field {Filter} Source THEN Target For example: CASE WHEN &#39;currency&#39; &#x3D; &#39;USD&#39; THEN &#39;US&#39; Here the Field is &#39;currency&#39;, the Source is &#39;USD&#39;, the Filter is &#39;&#x3D;&#39;, and the Target is &#39;US&#39;
 */
@JsonPropertyOrder({
  CaseStatementItem.JSON_PROPERTY_FILTER,
  CaseStatementItem.JSON_PROPERTY_SOURCE,
  CaseStatementItem.JSON_PROPERTY_TARGET,
  CaseStatementItem.JSON_PROPERTY_IS_TARGET_NON_LITERAL
})

public class CaseStatementItem {
  public static final String JSON_PROPERTY_FILTER = "filter";
  @JsonProperty(JSON_PROPERTY_FILTER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String filter;

  public static final String JSON_PROPERTY_SOURCE = "source";
  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String source;

  public static final String JSON_PROPERTY_TARGET = "target";
  @JsonProperty(JSON_PROPERTY_TARGET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String target;

  public static final String JSON_PROPERTY_IS_TARGET_NON_LITERAL = "isTargetNonLiteral";
  @JsonProperty(JSON_PROPERTY_IS_TARGET_NON_LITERAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Boolean isTargetNonLiteral;

  public CaseStatementItem() {
  }

  public CaseStatementItem filter(String filter) {
    this.filter = filter;
    return this;
  }

  /**
   * The operator in the case statement SQL expression
   * @return filter
   */
  @javax.annotation.Nonnull
  public String getFilter() {
    return filter;
  }

  public void setFilter(String filter) {
    this.filter = filter;
  }


  public CaseStatementItem source(String source) {
    this.source = source;
    return this;
  }

  /**
   * The expression that is on the LHS of the operator A typical case statement would look like: CASE Field {Filter} Source THEN Target
   * @return source
   */
  @javax.annotation.Nonnull
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }


  public CaseStatementItem target(String target) {
    this.target = target;
    return this;
  }

  /**
   * The expression that is on the RHS of the operator A typical case statement would look like: CASE Field {Filter} Source THEN Target
   * @return target
   */
  @javax.annotation.Nonnull
  public String getTarget() {
    return target;
  }

  public void setTarget(String target) {
    this.target = target;
  }


  public CaseStatementItem isTargetNonLiteral(Boolean isTargetNonLiteral) {
    this.isTargetNonLiteral = isTargetNonLiteral;
    return this;
  }

  /**
   * The Target can be a literal value or a non literal (field) and hence will be interpreted differently. This can be determined from the UI and passed down as a true / false
   * @return isTargetNonLiteral
   */
  @javax.annotation.Nullable
  public Boolean getIsTargetNonLiteral() {
    return isTargetNonLiteral;
  }

  public void setIsTargetNonLiteral(Boolean isTargetNonLiteral) {
    this.isTargetNonLiteral = isTargetNonLiteral;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaseStatementItem caseStatementItem = (CaseStatementItem) o;
    return Objects.equals(this.filter, caseStatementItem.filter) &&
        Objects.equals(this.source, caseStatementItem.source) &&
        Objects.equals(this.target, caseStatementItem.target) &&
        Objects.equals(this.isTargetNonLiteral, caseStatementItem.isTargetNonLiteral);
  }

  @Override
 public int hashCode() {
    return Objects.hash(filter, source, target, isTargetNonLiteral);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaseStatementItem {\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    isTargetNonLiteral: ").append(toIndentedString(isTargetNonLiteral)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of CaseStatementItem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CaseStatementItem
   * @throws java.io.IOException if the JSON string is invalid with respect to CaseStatementItem
   */
  public static CaseStatementItem fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, CaseStatementItem.class);
  }

  /**
   * Convert an instance of CaseStatementItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
