/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.luminesce.model;

import java.util.Objects;

import java.io.IOException;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The types of Exporting capable of being delivered by the WebAPI. Similar but not identical to &lt;seealso cref&#x3D;\&quot;T:Finbourne.Honeycomb.Api.Hosting.Exporting.OutputType\&quot; /&gt;
 */
public enum ExportType {
  
  CSV("csv"),
  
  PIPE("pipe"),
  
  EXCEL("excel"),
  
  JSON("json"),
  
  JSON_PROPER("jsonProper"),
  
  XML("xml"),
  
  PARQUET("parquet"),
  
  SQLITE("sqlite"),
  
  TABLE_INTERNAL("TableInternal"),
  
  JSON_PROPER_WITH_LINEAGE("jsonProperWithLineage"),
  
  PDF("pdf");

  private String value;

  ExportType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ExportType fromValue(String value) {
    for (ExportType b : ExportType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
