/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.luminesce.model;

import com.finbourne.sdk.services.luminesce.model.Aggregation;
import com.finbourne.sdk.services.luminesce.model.DataType;
import com.finbourne.sdk.services.luminesce.model.FilterTermDesign;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Treatment of a single field within a QueryDesign
 */
@JsonPropertyOrder({
  FieldDesign.JSON_PROPERTY_NAME,
  FieldDesign.JSON_PROPERTY_TABLE_ALIAS,
  FieldDesign.JSON_PROPERTY_ALIAS,
  FieldDesign.JSON_PROPERTY_DATA_TYPE,
  FieldDesign.JSON_PROPERTY_SHOULD_SELECT,
  FieldDesign.JSON_PROPERTY_FILTERS,
  FieldDesign.JSON_PROPERTY_AGGREGATIONS,
  FieldDesign.JSON_PROPERTY_IS_EXPRESSION
})

public class FieldDesign {
  public static final String JSON_PROPERTY_NAME = "name";
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String name;

  public static final String JSON_PROPERTY_TABLE_ALIAS = "tableAlias";
  @JsonProperty(JSON_PROPERTY_TABLE_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String tableAlias;

  public static final String JSON_PROPERTY_ALIAS = "alias";
  @JsonProperty(JSON_PROPERTY_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String alias;

  public static final String JSON_PROPERTY_DATA_TYPE = "dataType";
  @JsonProperty(JSON_PROPERTY_DATA_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private DataType dataType;

  public static final String JSON_PROPERTY_SHOULD_SELECT = "shouldSelect";
  @JsonProperty(JSON_PROPERTY_SHOULD_SELECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Boolean shouldSelect;

  public static final String JSON_PROPERTY_FILTERS = "filters";
  @JsonProperty(JSON_PROPERTY_FILTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<FilterTermDesign> filters;

  public static final String JSON_PROPERTY_AGGREGATIONS = "aggregations";
  @JsonProperty(JSON_PROPERTY_AGGREGATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<Aggregation> aggregations;

  public static final String JSON_PROPERTY_IS_EXPRESSION = "isExpression";
  @JsonProperty(JSON_PROPERTY_IS_EXPRESSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Boolean isExpression;

  public FieldDesign() {
  }

  public FieldDesign name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the Field (column name, constant, complex expression, etc.)
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public FieldDesign tableAlias(String tableAlias) {
    this.tableAlias = tableAlias;
    return this;
  }

  /**
   * Alias of the Table the field belongs to
   * @return tableAlias
   */
  @javax.annotation.Nullable
  public String getTableAlias() {
    return tableAlias;
  }

  public void setTableAlias(String tableAlias) {
    this.tableAlias = tableAlias;
  }


  public FieldDesign alias(String alias) {
    this.alias = alias;
    return this;
  }

  /**
   * Alias if any (if none the Name is used)
   * @return alias
   */
  @javax.annotation.Nullable
  public String getAlias() {
    return alias;
  }

  public void setAlias(String alias) {
    this.alias = alias;
  }


  public FieldDesign dataType(DataType dataType) {
    this.dataType = dataType;
    return this;
  }

  /**
   * Get dataType
   * @return dataType
   */
  @javax.annotation.Nullable
  public DataType getDataType() {
    return dataType;
  }

  public void setDataType(DataType dataType) {
    this.dataType = dataType;
  }


  public FieldDesign shouldSelect(Boolean shouldSelect) {
    this.shouldSelect = shouldSelect;
    return this;
  }

  /**
   * Should this be selected? False would imply it is only being filtered on. Ignored when Aggregations are present
   * @return shouldSelect
   */
  @javax.annotation.Nullable
  public Boolean getShouldSelect() {
    return shouldSelect;
  }

  public void setShouldSelect(Boolean shouldSelect) {
    this.shouldSelect = shouldSelect;
  }


  public FieldDesign filters(List<FilterTermDesign> filters) {
    this.filters = filters;
    return this;
  }

  public FieldDesign addFiltersItem(FilterTermDesign filtersItem) {
    if (this.filters == null) {
      this.filters = new ArrayList<>();
    }
    this.filters.add(filtersItem);
    return this;
  }

  /**
   * Filter clauses to apply to this field (And&#39;ed together)
   * @return filters
   */
  @javax.annotation.Nullable
  public List<FilterTermDesign> getFilters() {
    return filters;
  }

  public void setFilters(List<FilterTermDesign> filters) {
    this.filters = filters;
  }


  public FieldDesign aggregations(List<Aggregation> aggregations) {
    this.aggregations = aggregations;
    return this;
  }

  public FieldDesign addAggregationsItem(Aggregation aggregationsItem) {
    if (this.aggregations == null) {
      this.aggregations = new ArrayList<>();
    }
    this.aggregations.add(aggregationsItem);
    return this;
  }

  /**
   * Aggregations to apply (as opposed to simply selecting)
   * @return aggregations
   */
  @javax.annotation.Nullable
  public List<Aggregation> getAggregations() {
    return aggregations;
  }

  public void setAggregations(List<Aggregation> aggregations) {
    this.aggregations = aggregations;
  }


  public FieldDesign isExpression(Boolean isExpression) {
    this.isExpression = isExpression;
    return this;
  }

  /**
   * Is this field an expression
   * @return isExpression
   */
  @javax.annotation.Nullable
  public Boolean getIsExpression() {
    return isExpression;
  }

  public void setIsExpression(Boolean isExpression) {
    this.isExpression = isExpression;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldDesign fieldDesign = (FieldDesign) o;
    return Objects.equals(this.name, fieldDesign.name) &&
        Objects.equals(this.tableAlias, fieldDesign.tableAlias) &&
        Objects.equals(this.alias, fieldDesign.alias) &&
        Objects.equals(this.dataType, fieldDesign.dataType) &&
        Objects.equals(this.shouldSelect, fieldDesign.shouldSelect) &&
        Objects.equals(this.filters, fieldDesign.filters) &&
        Objects.equals(this.aggregations, fieldDesign.aggregations) &&
        Objects.equals(this.isExpression, fieldDesign.isExpression);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(name, tableAlias, alias, dataType, shouldSelect, filters, aggregations, isExpression);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldDesign {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tableAlias: ").append(toIndentedString(tableAlias)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
    sb.append("    shouldSelect: ").append(toIndentedString(shouldSelect)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    aggregations: ").append(toIndentedString(aggregations)).append("\n");
    sb.append("    isExpression: ").append(toIndentedString(isExpression)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of FieldDesign given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FieldDesign
   * @throws java.io.IOException if the JSON string is invalid with respect to FieldDesign
   */
  public static FieldDesign fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, FieldDesign.class);
  }

  /**
   * Convert an instance of FieldDesign to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
