/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.AllocationMapAllocation;
import com.finbourne.sdk.services.lusid.model.Link;
import com.finbourne.sdk.services.lusid.model.ResourceId;
import com.finbourne.sdk.services.lusid.model.Version;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * One economic event shared across the participants of an Allocation Map: raised as a draft, computed into  per-investor shares, and finally booked.
 */
@JsonPropertyOrder({
  AllocationEvent.JSON_PROPERTY_HREF,
  AllocationEvent.JSON_PROPERTY_ID,
  AllocationEvent.JSON_PROPERTY_DESCRIPTION,
  AllocationEvent.JSON_PROPERTY_ALLOCATION_MAP_ID,
  AllocationEvent.JSON_PROPERTY_EVENT_TYPE,
  AllocationEvent.JSON_PROPERTY_AMOUNT,
  AllocationEvent.JSON_PROPERTY_CURRENCY,
  AllocationEvent.JSON_PROPERTY_EVENT_DATE,
  AllocationEvent.JSON_PROPERTY_STATUS,
  AllocationEvent.JSON_PROPERTY_BASIS_SOURCE,
  AllocationEvent.JSON_PROPERTY_ALLOCATIONS,
  AllocationEvent.JSON_PROPERTY_BOOKING_REFERENCE,
  AllocationEvent.JSON_PROPERTY_BOOKED_AT,
  AllocationEvent.JSON_PROPERTY_REALLOCATION_REASON,
  AllocationEvent.JSON_PROPERTY_VERSION,
  AllocationEvent.JSON_PROPERTY_LINKS
})

public class AllocationEvent {
  public static final String JSON_PROPERTY_HREF = "href";
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private URI href;

  public static final String JSON_PROPERTY_ID = "id";
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private ResourceId id;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String description;

  public static final String JSON_PROPERTY_ALLOCATION_MAP_ID = "allocationMapId";
  @JsonProperty(JSON_PROPERTY_ALLOCATION_MAP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private ResourceId allocationMapId;

  public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String eventType;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private java.math.BigDecimal amount;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String currency;

  public static final String JSON_PROPERTY_EVENT_DATE = "eventDate";
  @JsonProperty(JSON_PROPERTY_EVENT_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OffsetDateTime eventDate;

  public static final String JSON_PROPERTY_STATUS = "status";
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String status;

  public static final String JSON_PROPERTY_BASIS_SOURCE = "basisSource";
  @JsonProperty(JSON_PROPERTY_BASIS_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String basisSource;

  public static final String JSON_PROPERTY_ALLOCATIONS = "allocations";
  @JsonProperty(JSON_PROPERTY_ALLOCATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<AllocationMapAllocation> allocations = new ArrayList<>();

  public static final String JSON_PROPERTY_BOOKING_REFERENCE = "bookingReference";
  @JsonProperty(JSON_PROPERTY_BOOKING_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String bookingReference;

  public static final String JSON_PROPERTY_BOOKED_AT = "bookedAt";
  @JsonProperty(JSON_PROPERTY_BOOKED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime bookedAt;

  public static final String JSON_PROPERTY_REALLOCATION_REASON = "reallocationReason";
  @JsonProperty(JSON_PROPERTY_REALLOCATION_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String reallocationReason;

  public static final String JSON_PROPERTY_VERSION = "version";
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Version version;

  public static final String JSON_PROPERTY_LINKS = "links";
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<Link> links;

  public AllocationEvent() {
  }

  public AllocationEvent href(URI href) {
    this.href = href;
    return this;
  }

  /**
   * The specific Uniform Resource Identifier (URI) for this resource at the requested effective and asAt datetime.
   * @return href
   */
  @javax.annotation.Nullable
  public URI getHref() {
    return href;
  }

  public void setHref(URI href) {
    this.href = href;
  }


  public AllocationEvent id(ResourceId id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public ResourceId getId() {
    return id;
  }

  public void setId(ResourceId id) {
    this.id = id;
  }


  public AllocationEvent description(String description) {
    this.description = description;
    return this;
  }

  /**
   * A description of the Allocation Event.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public AllocationEvent allocationMapId(ResourceId allocationMapId) {
    this.allocationMapId = allocationMapId;
    return this;
  }

  /**
   * Get allocationMapId
   * @return allocationMapId
   */
  @javax.annotation.Nonnull
  public ResourceId getAllocationMapId() {
    return allocationMapId;
  }

  public void setAllocationMapId(ResourceId allocationMapId) {
    this.allocationMapId = allocationMapId;
  }


  public AllocationEvent eventType(String eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * The type of the event: CapitalCall, Distribution, FeeExpense or ValuationMove. Selects the basis rule from the map. Available values: CapitalCall, Distribution, FeeExpense, ValuationMove.
   * @return eventType
   */
  @javax.annotation.Nonnull
  public String getEventType() {
    return eventType;
  }

  public void setEventType(String eventType) {
    this.eventType = eventType;
  }


  public AllocationEvent amount(java.math.BigDecimal amount) {
    this.amount = amount;
    return this;
  }

  /**
   * The total amount to be shared across the participants.
   * @return amount
   */
  @javax.annotation.Nonnull
  public java.math.BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(java.math.BigDecimal amount) {
    this.amount = amount;
  }


  public AllocationEvent currency(String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * The ISO 4217 code of the currency of the amount. The amount may not be finer than the currency&#39;s minor unit: two decimal places for most currencies, none for JPY, three for KWD and BHD. A code with no defined minor unit, such as XAU or XAG, is taken to have two decimal places.
   * @return currency
   */
  @javax.annotation.Nonnull
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public AllocationEvent eventDate(OffsetDateTime eventDate) {
    this.eventDate = eventDate;
    return this;
  }

  /**
   * The date of the event: the point at which the map, its participants and their basis values are read.
   * @return eventDate
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getEventDate() {
    return eventDate;
  }

  public void setEventDate(OffsetDateTime eventDate) {
    this.eventDate = eventDate;
  }


  public AllocationEvent status(String status) {
    this.status = status;
    return this;
  }

  /**
   * The lifecycle status of the event: Draft until its shares are computed, Computed once they are, and Booked once posted. Available values: Draft, Computed, Booked.
   * @return status
   */
  @javax.annotation.Nonnull
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  public AllocationEvent basisSource(String basisSource) {
    this.basisSource = basisSource;
    return this;
  }

  /**
   * Where the basis values came from when the shares were last computed.
   * @return basisSource
   */
  @javax.annotation.Nullable
  public String getBasisSource() {
    return basisSource;
  }

  public void setBasisSource(String basisSource) {
    this.basisSource = basisSource;
  }


  public AllocationEvent allocations(List<AllocationMapAllocation> allocations) {
    this.allocations = allocations;
    return this;
  }

  public AllocationEvent addAllocationsItem(AllocationMapAllocation allocationsItem) {
    if (this.allocations == null) {
      this.allocations = new ArrayList<>();
    }
    this.allocations.add(allocationsItem);
    return this;
  }

  /**
   * The per-investor shares of the amount, as last computed.
   * @return allocations
   */
  @javax.annotation.Nonnull
  public List<AllocationMapAllocation> getAllocations() {
    return allocations;
  }

  public void setAllocations(List<AllocationMapAllocation> allocations) {
    this.allocations = allocations;
  }


  public AllocationEvent bookingReference(String bookingReference) {
    this.bookingReference = bookingReference;
    return this;
  }

  /**
   * The reference under which the shares were posted. Set only once the event is booked.
   * @return bookingReference
   */
  @javax.annotation.Nullable
  public String getBookingReference() {
    return bookingReference;
  }

  public void setBookingReference(String bookingReference) {
    this.bookingReference = bookingReference;
  }


  public AllocationEvent bookedAt(OffsetDateTime bookedAt) {
    this.bookedAt = bookedAt;
    return this;
  }

  /**
   * The datetime at which the event was booked.
   * @return bookedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getBookedAt() {
    return bookedAt;
  }

  public void setBookedAt(OffsetDateTime bookedAt) {
    this.bookedAt = bookedAt;
  }


  public AllocationEvent reallocationReason(String reallocationReason) {
    this.reallocationReason = reallocationReason;
    return this;
  }

  /**
   * The reason given when the event was last recomputed, if it has been.
   * @return reallocationReason
   */
  @javax.annotation.Nullable
  public String getReallocationReason() {
    return reallocationReason;
  }

  public void setReallocationReason(String reallocationReason) {
    this.reallocationReason = reallocationReason;
  }


  public AllocationEvent version(Version version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nullable
  public Version getVersion() {
    return version;
  }

  public void setVersion(Version version) {
    this.version = version;
  }


  public AllocationEvent links(List<Link> links) {
    this.links = links;
    return this;
  }

  public AllocationEvent addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @javax.annotation.Nullable
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllocationEvent allocationEvent = (AllocationEvent) o;
    return Objects.equals(this.href, allocationEvent.href) &&
        Objects.equals(this.id, allocationEvent.id) &&
        Objects.equals(this.description, allocationEvent.description) &&
        Objects.equals(this.allocationMapId, allocationEvent.allocationMapId) &&
        Objects.equals(this.eventType, allocationEvent.eventType) &&
        (this.amount == null ? allocationEvent.amount == null : (allocationEvent.amount != null && this.amount.compareTo(allocationEvent.getAmount()) == 0)) &&
        Objects.equals(this.currency, allocationEvent.currency) &&
        Objects.equals(this.eventDate, allocationEvent.eventDate) &&
        Objects.equals(this.status, allocationEvent.status) &&
        Objects.equals(this.basisSource, allocationEvent.basisSource) &&
        Objects.equals(this.allocations, allocationEvent.allocations) &&
        Objects.equals(this.bookingReference, allocationEvent.bookingReference) &&
        Objects.equals(this.bookedAt, allocationEvent.bookedAt) &&
        Objects.equals(this.reallocationReason, allocationEvent.reallocationReason) &&
        Objects.equals(this.version, allocationEvent.version) &&
        Objects.equals(this.links, allocationEvent.links);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(href, id, description, allocationMapId, eventType, amount, currency, eventDate, status, basisSource, allocations, bookingReference, bookedAt, reallocationReason, version, links);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllocationEvent {\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    allocationMapId: ").append(toIndentedString(allocationMapId)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    eventDate: ").append(toIndentedString(eventDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    basisSource: ").append(toIndentedString(basisSource)).append("\n");
    sb.append("    allocations: ").append(toIndentedString(allocations)).append("\n");
    sb.append("    bookingReference: ").append(toIndentedString(bookingReference)).append("\n");
    sb.append("    bookedAt: ").append(toIndentedString(bookedAt)).append("\n");
    sb.append("    reallocationReason: ").append(toIndentedString(reallocationReason)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of AllocationEvent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AllocationEvent
   * @throws java.io.IOException if the JSON string is invalid with respect to AllocationEvent
   */
  public static AllocationEvent fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, AllocationEvent.class);
  }

  /**
   * Convert an instance of AllocationEvent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
