/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.CurrencyAndAmount;
import com.finbourne.sdk.services.lusid.model.DataModelMembership;
import com.finbourne.sdk.services.lusid.model.Link;
import com.finbourne.sdk.services.lusid.model.PerpetualProperty;
import com.finbourne.sdk.services.lusid.model.ResourceId;
import com.finbourne.sdk.services.lusid.model.Version;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * A block of orders for the same instrument, intended to record for example a trader&#39;s aggregation  of outstanding orders at a given time.
 */
@JsonPropertyOrder({
  Block.JSON_PROPERTY_ID,
  Block.JSON_PROPERTY_ORDER_IDS,
  Block.JSON_PROPERTY_PROPERTIES,
  Block.JSON_PROPERTY_INSTRUMENT_IDENTIFIERS,
  Block.JSON_PROPERTY_LUSID_INSTRUMENT_ID,
  Block.JSON_PROPERTY_QUANTITY,
  Block.JSON_PROPERTY_SIDE,
  Block.JSON_PROPERTY_TYPE,
  Block.JSON_PROPERTY_TIME_IN_FORCE,
  Block.JSON_PROPERTY_CREATED_DATE,
  Block.JSON_PROPERTY_LIMIT_PRICE,
  Block.JSON_PROPERTY_STOP_PRICE,
  Block.JSON_PROPERTY_IS_SWEPT,
  Block.JSON_PROPERTY_VERSION,
  Block.JSON_PROPERTY_DATA_MODEL_MEMBERSHIP,
  Block.JSON_PROPERTY_LINKS
})

public class Block {
  public static final String JSON_PROPERTY_ID = "id";
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private ResourceId id;

  public static final String JSON_PROPERTY_ORDER_IDS = "orderIds";
  @JsonProperty(JSON_PROPERTY_ORDER_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<ResourceId> orderIds = new ArrayList<>();

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Map<String, PerpetualProperty> properties;

  public static final String JSON_PROPERTY_INSTRUMENT_IDENTIFIERS = "instrumentIdentifiers";
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_IDENTIFIERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private Map<String, String> instrumentIdentifiers = new HashMap<>();

  public static final String JSON_PROPERTY_LUSID_INSTRUMENT_ID = "lusidInstrumentId";
  @JsonProperty(JSON_PROPERTY_LUSID_INSTRUMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String lusidInstrumentId;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private java.math.BigDecimal quantity;

  public static final String JSON_PROPERTY_SIDE = "side";
  @JsonProperty(JSON_PROPERTY_SIDE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String side;

  public static final String JSON_PROPERTY_TYPE = "type";
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String type;

  public static final String JSON_PROPERTY_TIME_IN_FORCE = "timeInForce";
  @JsonProperty(JSON_PROPERTY_TIME_IN_FORCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String timeInForce;

  public static final String JSON_PROPERTY_CREATED_DATE = "createdDate";
  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OffsetDateTime createdDate;

  public static final String JSON_PROPERTY_LIMIT_PRICE = "limitPrice";
  @JsonProperty(JSON_PROPERTY_LIMIT_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private CurrencyAndAmount limitPrice;

  public static final String JSON_PROPERTY_STOP_PRICE = "stopPrice";
  @JsonProperty(JSON_PROPERTY_STOP_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private CurrencyAndAmount stopPrice;

  public static final String JSON_PROPERTY_IS_SWEPT = "isSwept";
  @JsonProperty(JSON_PROPERTY_IS_SWEPT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private Boolean isSwept;

  public static final String JSON_PROPERTY_VERSION = "version";
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Version version;

  public static final String JSON_PROPERTY_DATA_MODEL_MEMBERSHIP = "dataModelMembership";
  @JsonProperty(JSON_PROPERTY_DATA_MODEL_MEMBERSHIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private DataModelMembership dataModelMembership;

  public static final String JSON_PROPERTY_LINKS = "links";
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<Link> links;

  public Block() {
  }

  public Block id(ResourceId id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public ResourceId getId() {
    return id;
  }

  public void setId(ResourceId id) {
    this.id = id;
  }


  public Block orderIds(List<ResourceId> orderIds) {
    this.orderIds = orderIds;
    return this;
  }

  public Block addOrderIdsItem(ResourceId orderIdsItem) {
    if (this.orderIds == null) {
      this.orderIds = new ArrayList<>();
    }
    this.orderIds.add(orderIdsItem);
    return this;
  }

  /**
   * The related order ids.
   * @return orderIds
   */
  @javax.annotation.Nonnull
  public List<ResourceId> getOrderIds() {
    return orderIds;
  }

  public void setOrderIds(List<ResourceId> orderIds) {
    this.orderIds = orderIds;
  }


  public Block properties(Map<String, PerpetualProperty> properties) {
    this.properties = properties;
    return this;
  }

  public Block putPropertiesItem(String key, PerpetualProperty propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

  /**
   * Client-defined properties associated with this block.
   * @return properties
   */
  @javax.annotation.Nullable
  public Map<String, PerpetualProperty> getProperties() {
    return properties;
  }

  public void setProperties(Map<String, PerpetualProperty> properties) {
    this.properties = properties;
  }


  public Block instrumentIdentifiers(Map<String, String> instrumentIdentifiers) {
    this.instrumentIdentifiers = instrumentIdentifiers;
    return this;
  }

  public Block putInstrumentIdentifiersItem(String key, String instrumentIdentifiersItem) {
    if (this.instrumentIdentifiers == null) {
      this.instrumentIdentifiers = new HashMap<>();
    }
    this.instrumentIdentifiers.put(key, instrumentIdentifiersItem);
    return this;
  }

  /**
   * The instrument ordered.
   * @return instrumentIdentifiers
   */
  @javax.annotation.Nonnull
  public Map<String, String> getInstrumentIdentifiers() {
    return instrumentIdentifiers;
  }

  public void setInstrumentIdentifiers(Map<String, String> instrumentIdentifiers) {
    this.instrumentIdentifiers = instrumentIdentifiers;
  }


  public Block lusidInstrumentId(String lusidInstrumentId) {
    this.lusidInstrumentId = lusidInstrumentId;
    return this;
  }

  /**
   * The LUSID instrument id for the instrument ordered.
   * @return lusidInstrumentId
   */
  @javax.annotation.Nonnull
  public String getLusidInstrumentId() {
    return lusidInstrumentId;
  }

  public void setLusidInstrumentId(String lusidInstrumentId) {
    this.lusidInstrumentId = lusidInstrumentId;
  }


  public Block quantity(java.math.BigDecimal quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * The total quantity of given instrument ordered.
   * @return quantity
   */
  @javax.annotation.Nonnull
  public java.math.BigDecimal getQuantity() {
    return quantity;
  }

  public void setQuantity(java.math.BigDecimal quantity) {
    this.quantity = quantity;
  }


  public Block side(String side) {
    this.side = side;
    return this;
  }

  /**
   * The client&#39;s representation of the block&#39;s side (buy, sell, short, etc)
   * @return side
   */
  @javax.annotation.Nonnull
  public String getSide() {
    return side;
  }

  public void setSide(String side) {
    this.side = side;
  }


  public Block type(String type) {
    this.type = type;
    return this;
  }

  /**
   * The block order&#39;s type (examples: Limit, Market, ...)
   * @return type
   */
  @javax.annotation.Nullable
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  public Block timeInForce(String timeInForce) {
    this.timeInForce = timeInForce;
    return this;
  }

  /**
   * The block orders&#39; time in force (examples: Day, GoodTilCancel, ...)
   * @return timeInForce
   */
  @javax.annotation.Nullable
  public String getTimeInForce() {
    return timeInForce;
  }

  public void setTimeInForce(String timeInForce) {
    this.timeInForce = timeInForce;
  }


  public Block createdDate(OffsetDateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

  /**
   * The date on which the block was made
   * @return createdDate
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(OffsetDateTime createdDate) {
    this.createdDate = createdDate;
  }


  public Block limitPrice(CurrencyAndAmount limitPrice) {
    this.limitPrice = limitPrice;
    return this;
  }

  /**
   * Get limitPrice
   * @return limitPrice
   */
  @javax.annotation.Nullable
  public CurrencyAndAmount getLimitPrice() {
    return limitPrice;
  }

  public void setLimitPrice(CurrencyAndAmount limitPrice) {
    this.limitPrice = limitPrice;
  }


  public Block stopPrice(CurrencyAndAmount stopPrice) {
    this.stopPrice = stopPrice;
    return this;
  }

  /**
   * Get stopPrice
   * @return stopPrice
   */
  @javax.annotation.Nullable
  public CurrencyAndAmount getStopPrice() {
    return stopPrice;
  }

  public void setStopPrice(CurrencyAndAmount stopPrice) {
    this.stopPrice = stopPrice;
  }


  public Block isSwept(Boolean isSwept) {
    this.isSwept = isSwept;
    return this;
  }

  /**
   * Swept blocks are considered no longer of active interest, and no longer take part in various order management processes
   * @return isSwept
   */
  @javax.annotation.Nonnull
  public Boolean getIsSwept() {
    return isSwept;
  }

  public void setIsSwept(Boolean isSwept) {
    this.isSwept = isSwept;
  }


  public Block version(Version version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nullable
  public Version getVersion() {
    return version;
  }

  public void setVersion(Version version) {
    this.version = version;
  }


  public Block dataModelMembership(DataModelMembership dataModelMembership) {
    this.dataModelMembership = dataModelMembership;
    return this;
  }

  /**
   * Get dataModelMembership
   * @return dataModelMembership
   */
  @javax.annotation.Nullable
  public DataModelMembership getDataModelMembership() {
    return dataModelMembership;
  }

  public void setDataModelMembership(DataModelMembership dataModelMembership) {
    this.dataModelMembership = dataModelMembership;
  }


  public Block links(List<Link> links) {
    this.links = links;
    return this;
  }

  public Block addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @javax.annotation.Nullable
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Block block = (Block) o;
    return Objects.equals(this.id, block.id) &&
        Objects.equals(this.orderIds, block.orderIds) &&
        Objects.equals(this.properties, block.properties) &&
        Objects.equals(this.instrumentIdentifiers, block.instrumentIdentifiers) &&
        Objects.equals(this.lusidInstrumentId, block.lusidInstrumentId) &&
        (this.quantity.compareTo(block.getQuantity()) == 0) &&
        Objects.equals(this.side, block.side) &&
        Objects.equals(this.type, block.type) &&
        Objects.equals(this.timeInForce, block.timeInForce) &&
        Objects.equals(this.createdDate, block.createdDate) &&
        Objects.equals(this.limitPrice, block.limitPrice) &&
        Objects.equals(this.stopPrice, block.stopPrice) &&
        Objects.equals(this.isSwept, block.isSwept) &&
        Objects.equals(this.version, block.version) &&
        Objects.equals(this.dataModelMembership, block.dataModelMembership) &&
        Objects.equals(this.links, block.links);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(id, orderIds, properties, instrumentIdentifiers, lusidInstrumentId, quantity, side, type, timeInForce, createdDate, limitPrice, stopPrice, isSwept, version, dataModelMembership, links);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Block {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    orderIds: ").append(toIndentedString(orderIds)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    instrumentIdentifiers: ").append(toIndentedString(instrumentIdentifiers)).append("\n");
    sb.append("    lusidInstrumentId: ").append(toIndentedString(lusidInstrumentId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    side: ").append(toIndentedString(side)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    timeInForce: ").append(toIndentedString(timeInForce)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    limitPrice: ").append(toIndentedString(limitPrice)).append("\n");
    sb.append("    stopPrice: ").append(toIndentedString(stopPrice)).append("\n");
    sb.append("    isSwept: ").append(toIndentedString(isSwept)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    dataModelMembership: ").append(toIndentedString(dataModelMembership)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of Block given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Block
   * @throws java.io.IOException if the JSON string is invalid with respect to Block
   */
  public static Block fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, Block.class);
  }

  /**
   * Convert an instance of Block to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
