/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.Link;
import com.finbourne.sdk.services.lusid.model.ResourceId;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * An individual cashflow inside a cashflow bucket, annotated with the source that produced it  in the cash flow waterfall (SRS &gt; Transaction &gt; Instrument).
 */
@JsonPropertyOrder({
  CashFlowDetail.JSON_PROPERTY_PAYMENT_DATE,
  CashFlowDetail.JSON_PROPERTY_AMOUNT,
  CashFlowDetail.JSON_PROPERTY_CURRENCY,
  CashFlowDetail.JSON_PROPERTY_SOURCE_TYPE,
  CashFlowDetail.JSON_PROPERTY_INSTRUMENT_ID,
  CashFlowDetail.JSON_PROPERTY_INSTRUMENT_DISPLAY_NAME,
  CashFlowDetail.JSON_PROPERTY_TRANSACTION_ID,
  CashFlowDetail.JSON_PROPERTY_PORTFOLIO_ID,
  CashFlowDetail.JSON_PROPERTY_FLOW_TYPE,
  CashFlowDetail.JSON_PROPERTY_MOVEMENT_NAME,
  CashFlowDetail.JSON_PROPERTY_PAY_RECEIVE,
  CashFlowDetail.JSON_PROPERTY_GROSS_AMOUNT,
  CashFlowDetail.JSON_PROPERTY_HAIRCUT_FRACTION,
  CashFlowDetail.JSON_PROPERTY_NET_AMOUNT,
  CashFlowDetail.JSON_PROPERTY_HAIRCUT_RULE_APPLIED,
  CashFlowDetail.JSON_PROPERTY_ERROR,
  CashFlowDetail.JSON_PROPERTY_AMOUNT_IN_REPORT_CURRENCY,
  CashFlowDetail.JSON_PROPERTY_TRADE_TO_REPORT_CURRENCY_RATE,
  CashFlowDetail.JSON_PROPERTY_LINKS
})

public class CashFlowDetail {
  public static final String JSON_PROPERTY_PAYMENT_DATE = "paymentDate";
  @JsonProperty(JSON_PROPERTY_PAYMENT_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OffsetDateTime paymentDate;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private java.math.BigDecimal amount;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String currency;

  public static final String JSON_PROPERTY_SOURCE_TYPE = "sourceType";
  @JsonProperty(JSON_PROPERTY_SOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String sourceType;

  public static final String JSON_PROPERTY_INSTRUMENT_ID = "instrumentId";
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String instrumentId;

  public static final String JSON_PROPERTY_INSTRUMENT_DISPLAY_NAME = "instrumentDisplayName";
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String instrumentDisplayName;

  public static final String JSON_PROPERTY_TRANSACTION_ID = "transactionId";
  @JsonProperty(JSON_PROPERTY_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String transactionId;

  public static final String JSON_PROPERTY_PORTFOLIO_ID = "portfolioId";
  @JsonProperty(JSON_PROPERTY_PORTFOLIO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private ResourceId portfolioId;

  public static final String JSON_PROPERTY_FLOW_TYPE = "flowType";
  @JsonProperty(JSON_PROPERTY_FLOW_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String flowType;

  public static final String JSON_PROPERTY_MOVEMENT_NAME = "movementName";
  @JsonProperty(JSON_PROPERTY_MOVEMENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String movementName;

  public static final String JSON_PROPERTY_PAY_RECEIVE = "payReceive";
  @JsonProperty(JSON_PROPERTY_PAY_RECEIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String payReceive;

  public static final String JSON_PROPERTY_GROSS_AMOUNT = "grossAmount";
  @JsonProperty(JSON_PROPERTY_GROSS_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private java.math.BigDecimal grossAmount;

  public static final String JSON_PROPERTY_HAIRCUT_FRACTION = "haircutFraction";
  @JsonProperty(JSON_PROPERTY_HAIRCUT_FRACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private java.math.BigDecimal haircutFraction;

  public static final String JSON_PROPERTY_NET_AMOUNT = "netAmount";
  @JsonProperty(JSON_PROPERTY_NET_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private java.math.BigDecimal netAmount;

  public static final String JSON_PROPERTY_HAIRCUT_RULE_APPLIED = "haircutRuleApplied";
  @JsonProperty(JSON_PROPERTY_HAIRCUT_RULE_APPLIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String haircutRuleApplied;

  public static final String JSON_PROPERTY_ERROR = "error";
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String error;

  public static final String JSON_PROPERTY_AMOUNT_IN_REPORT_CURRENCY = "amountInReportCurrency";
  @JsonProperty(JSON_PROPERTY_AMOUNT_IN_REPORT_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private java.math.BigDecimal amountInReportCurrency;

  public static final String JSON_PROPERTY_TRADE_TO_REPORT_CURRENCY_RATE = "tradeToReportCurrencyRate";
  @JsonProperty(JSON_PROPERTY_TRADE_TO_REPORT_CURRENCY_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private java.math.BigDecimal tradeToReportCurrencyRate;

  public static final String JSON_PROPERTY_LINKS = "links";
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<Link> links;

  public CashFlowDetail() {
  }

  public CashFlowDetail paymentDate(OffsetDateTime paymentDate) {
    this.paymentDate = paymentDate;
    return this;
  }

  /**
   * The date on which the cashflow is paid.
   * @return paymentDate
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getPaymentDate() {
    return paymentDate;
  }

  public void setPaymentDate(OffsetDateTime paymentDate) {
    this.paymentDate = paymentDate;
  }


  public CashFlowDetail amount(java.math.BigDecimal amount) {
    this.amount = amount;
    return this;
  }

  /**
   * The signed amount of the cashflow. A positive amount indicates money is received, a negative amount indicates money is paid. The amount is always the gross (pre-haircut) signed amount; when haircut rules are supplied the haircut and net amounts are reported separately.
   * @return amount
   */
  @javax.annotation.Nullable
  public java.math.BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(java.math.BigDecimal amount) {
    this.amount = amount;
  }


  public CashFlowDetail currency(String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * The payment currency of the cashflow.
   * @return currency
   */
  @javax.annotation.Nonnull
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public CashFlowDetail sourceType(String sourceType) {
    this.sourceType = sourceType;
    return this;
  }

  /**
   * The source that produced the cashflow in the cash flow waterfall. One of &#39;Instrument&#39; (produced by the valuation engine), &#39;Transaction&#39; (produced from a booked transaction or movement) or &#39;SRS&#39; (sourced from the structured results store).
   * @return sourceType
   */
  @javax.annotation.Nonnull
  public String getSourceType() {
    return sourceType;
  }

  public void setSourceType(String sourceType) {
    this.sourceType = sourceType;
  }


  public CashFlowDetail instrumentId(String instrumentId) {
    this.instrumentId = instrumentId;
    return this;
  }

  /**
   * The LUSID instrument identifier of the instrument that produced the cashflow.
   * @return instrumentId
   */
  @javax.annotation.Nonnull
  public String getInstrumentId() {
    return instrumentId;
  }

  public void setInstrumentId(String instrumentId) {
    this.instrumentId = instrumentId;
  }


  public CashFlowDetail instrumentDisplayName(String instrumentDisplayName) {
    this.instrumentDisplayName = instrumentDisplayName;
    return this;
  }

  /**
   * The display name of the instrument that produced the cashflow. Not present when the instrument cannot be resolved (e.g. deleted, no permission).
   * @return instrumentDisplayName
   */
  @javax.annotation.Nullable
  public String getInstrumentDisplayName() {
    return instrumentDisplayName;
  }

  public void setInstrumentDisplayName(String instrumentDisplayName) {
    this.instrumentDisplayName = instrumentDisplayName;
  }


  public CashFlowDetail transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * The identifier of the transaction from which the cashflow originates, where known.
   * @return transactionId
   */
  @javax.annotation.Nullable
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }


  public CashFlowDetail portfolioId(ResourceId portfolioId) {
    this.portfolioId = portfolioId;
    return this;
  }

  /**
   * Get portfolioId
   * @return portfolioId
   */
  @javax.annotation.Nonnull
  public ResourceId getPortfolioId() {
    return portfolioId;
  }

  public void setPortfolioId(ResourceId portfolioId) {
    this.portfolioId = portfolioId;
  }


  public CashFlowDetail flowType(String flowType) {
    this.flowType = flowType;
    return this;
  }

  /**
   * The type of the cashflow, e.g. Coupon, Principal or Premium.
   * @return flowType
   */
  @javax.annotation.Nullable
  public String getFlowType() {
    return flowType;
  }

  public void setFlowType(String flowType) {
    this.flowType = flowType;
  }


  public CashFlowDetail movementName(String movementName) {
    this.movementName = movementName;
    return this;
  }

  /**
   * The name of the movement that produced the cashflow (e.g. Coupon, Side1), falling back to the flow type when the movement is unnamed. Not present when the cashflow could not be valued.
   * @return movementName
   */
  @javax.annotation.Nullable
  public String getMovementName() {
    return movementName;
  }

  public void setMovementName(String movementName) {
    this.movementName = movementName;
  }


  public CashFlowDetail payReceive(String payReceive) {
    this.payReceive = payReceive;
    return this;
  }

  /**
   * Indicates whether the cashflow is paid or received.
   * @return payReceive
   */
  @javax.annotation.Nullable
  public String getPayReceive() {
    return payReceive;
  }

  public void setPayReceive(String payReceive) {
    this.payReceive = payReceive;
  }


  public CashFlowDetail grossAmount(java.math.BigDecimal grossAmount) {
    this.grossAmount = grossAmount;
    return this;
  }

  /**
   * The signed amount of the cashflow before any haircut was applied. Only populated when haircut rules were supplied on the request.
   * @return grossAmount
   */
  @javax.annotation.Nullable
  public java.math.BigDecimal getGrossAmount() {
    return grossAmount;
  }

  public void setGrossAmount(java.math.BigDecimal grossAmount) {
    this.grossAmount = grossAmount;
  }


  public CashFlowDetail haircutFraction(java.math.BigDecimal haircutFraction) {
    this.haircutFraction = haircutFraction;
    return this;
  }

  /**
   * The fraction of the gross amount removed by the haircut, in the range [0, 1]. Zero for outflows and for cashflows no rule matched. Only populated when haircut rules were supplied on the request.
   * @return haircutFraction
   */
  @javax.annotation.Nullable
  public java.math.BigDecimal getHaircutFraction() {
    return haircutFraction;
  }

  public void setHaircutFraction(java.math.BigDecimal haircutFraction) {
    this.haircutFraction = haircutFraction;
  }


  public CashFlowDetail netAmount(java.math.BigDecimal netAmount) {
    this.netAmount = netAmount;
    return this;
  }

  /**
   * The signed amount of the cashflow net of the haircut. Only populated when haircut rules were supplied on the request.
   * @return netAmount
   */
  @javax.annotation.Nullable
  public java.math.BigDecimal getNetAmount() {
    return netAmount;
  }

  public void setNetAmount(java.math.BigDecimal netAmount) {
    this.netAmount = netAmount;
  }


  public CashFlowDetail haircutRuleApplied(String haircutRuleApplied) {
    this.haircutRuleApplied = haircutRuleApplied;
    return this;
  }

  /**
   * The identifier of the haircut rule that was applied to the cashflow, or not present when no rule matched or no haircut rules were supplied on the request.
   * @return haircutRuleApplied
   */
  @javax.annotation.Nullable
  public String getHaircutRuleApplied() {
    return haircutRuleApplied;
  }

  public void setHaircutRuleApplied(String haircutRuleApplied) {
    this.haircutRuleApplied = haircutRuleApplied;
  }


  public CashFlowDetail error(String error) {
    this.error = error;
    return this;
  }

  /**
   * Present when the cashflow could not be valued, for example because of missing market data: the valuation error, matching the CashflowError diagnostic reported by the QueryCashFlows endpoint. In that case the amount is null rather than zero. Error may also be set when only the report-currency FX lookup failed (see AmountInReportCurrency), in which case the base Amount remains populated and only AmountInReportCurrency and TradeToReportCurrencyRate are null.
   * @return error
   */
  @javax.annotation.Nullable
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }


  public CashFlowDetail amountInReportCurrency(java.math.BigDecimal amountInReportCurrency) {
    this.amountInReportCurrency = amountInReportCurrency;
    return this;
  }

  /**
   * The signed amount of the cashflow (see Amount), converted into the request&#39;s report currency (see QueryBucketCashFlowDrillDownRequest.ReportCurrency). Not present when the FX rate used to convert into the report currency could not be resolved; see Error.
   * @return amountInReportCurrency
   */
  @javax.annotation.Nullable
  public java.math.BigDecimal getAmountInReportCurrency() {
    return amountInReportCurrency;
  }

  public void setAmountInReportCurrency(java.math.BigDecimal amountInReportCurrency) {
    this.amountInReportCurrency = amountInReportCurrency;
  }


  public CashFlowDetail tradeToReportCurrencyRate(java.math.BigDecimal tradeToReportCurrencyRate) {
    this.tradeToReportCurrencyRate = tradeToReportCurrencyRate;
    return this;
  }

  /**
   * The FX rate used to convert the cashflow amount into the request&#39;s report currency, resolved at the cashflow&#39;s transaction (trade) date, not its payment date. Not present when the rate could not be resolved; see Error.
   * @return tradeToReportCurrencyRate
   */
  @javax.annotation.Nullable
  public java.math.BigDecimal getTradeToReportCurrencyRate() {
    return tradeToReportCurrencyRate;
  }

  public void setTradeToReportCurrencyRate(java.math.BigDecimal tradeToReportCurrencyRate) {
    this.tradeToReportCurrencyRate = tradeToReportCurrencyRate;
  }


  public CashFlowDetail links(List<Link> links) {
    this.links = links;
    return this;
  }

  public CashFlowDetail addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @javax.annotation.Nullable
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CashFlowDetail cashFlowDetail = (CashFlowDetail) o;
    return Objects.equals(this.paymentDate, cashFlowDetail.paymentDate) &&
        (this.amount == null ? cashFlowDetail.amount == null : (cashFlowDetail.amount != null && this.amount.compareTo(cashFlowDetail.getAmount()) == 0)) &&
        Objects.equals(this.currency, cashFlowDetail.currency) &&
        Objects.equals(this.sourceType, cashFlowDetail.sourceType) &&
        Objects.equals(this.instrumentId, cashFlowDetail.instrumentId) &&
        Objects.equals(this.instrumentDisplayName, cashFlowDetail.instrumentDisplayName) &&
        Objects.equals(this.transactionId, cashFlowDetail.transactionId) &&
        Objects.equals(this.portfolioId, cashFlowDetail.portfolioId) &&
        Objects.equals(this.flowType, cashFlowDetail.flowType) &&
        Objects.equals(this.movementName, cashFlowDetail.movementName) &&
        Objects.equals(this.payReceive, cashFlowDetail.payReceive) &&
        (this.grossAmount == null ? cashFlowDetail.grossAmount == null : (cashFlowDetail.grossAmount != null && this.grossAmount.compareTo(cashFlowDetail.getGrossAmount()) == 0)) &&
        (this.haircutFraction == null ? cashFlowDetail.haircutFraction == null : (cashFlowDetail.haircutFraction != null && this.haircutFraction.compareTo(cashFlowDetail.getHaircutFraction()) == 0)) &&
        (this.netAmount == null ? cashFlowDetail.netAmount == null : (cashFlowDetail.netAmount != null && this.netAmount.compareTo(cashFlowDetail.getNetAmount()) == 0)) &&
        Objects.equals(this.haircutRuleApplied, cashFlowDetail.haircutRuleApplied) &&
        Objects.equals(this.error, cashFlowDetail.error) &&
        (this.amountInReportCurrency == null ? cashFlowDetail.amountInReportCurrency == null : (cashFlowDetail.amountInReportCurrency != null && this.amountInReportCurrency.compareTo(cashFlowDetail.getAmountInReportCurrency()) == 0)) &&
        (this.tradeToReportCurrencyRate == null ? cashFlowDetail.tradeToReportCurrencyRate == null : (cashFlowDetail.tradeToReportCurrencyRate != null && this.tradeToReportCurrencyRate.compareTo(cashFlowDetail.getTradeToReportCurrencyRate()) == 0)) &&
        Objects.equals(this.links, cashFlowDetail.links);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(paymentDate, amount, currency, sourceType, instrumentId, instrumentDisplayName, transactionId, portfolioId, flowType, movementName, payReceive, grossAmount, haircutFraction, netAmount, haircutRuleApplied, error, amountInReportCurrency, tradeToReportCurrencyRate, links);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CashFlowDetail {\n");
    sb.append("    paymentDate: ").append(toIndentedString(paymentDate)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    instrumentId: ").append(toIndentedString(instrumentId)).append("\n");
    sb.append("    instrumentDisplayName: ").append(toIndentedString(instrumentDisplayName)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    portfolioId: ").append(toIndentedString(portfolioId)).append("\n");
    sb.append("    flowType: ").append(toIndentedString(flowType)).append("\n");
    sb.append("    movementName: ").append(toIndentedString(movementName)).append("\n");
    sb.append("    payReceive: ").append(toIndentedString(payReceive)).append("\n");
    sb.append("    grossAmount: ").append(toIndentedString(grossAmount)).append("\n");
    sb.append("    haircutFraction: ").append(toIndentedString(haircutFraction)).append("\n");
    sb.append("    netAmount: ").append(toIndentedString(netAmount)).append("\n");
    sb.append("    haircutRuleApplied: ").append(toIndentedString(haircutRuleApplied)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    amountInReportCurrency: ").append(toIndentedString(amountInReportCurrency)).append("\n");
    sb.append("    tradeToReportCurrencyRate: ").append(toIndentedString(tradeToReportCurrencyRate)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of CashFlowDetail given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CashFlowDetail
   * @throws java.io.IOException if the JSON string is invalid with respect to CashFlowDetail
   */
  public static CashFlowDetail fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, CashFlowDetail.class);
  }

  /**
   * Convert an instance of CashFlowDetail to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
