/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import java.util.Objects;

import java.io.IOException;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets ComplianceStepTypeRequest
 */
public enum ComplianceStepTypeRequest {
  
  FILTER_STEP_REQUEST("FilterStepRequest"),
  
  GROUP_BY_STEP_REQUEST("GroupByStepRequest"),
  
  GROUP_FILTER_STEP_REQUEST("GroupFilterStepRequest"),
  
  BRANCH_STEP_REQUEST("BranchStepRequest"),
  
  CHECK_STEP_REQUEST("CheckStepRequest"),
  
  PERCENT_CHECK_STEP_REQUEST("PercentCheckStepRequest");

  private String value;

  ComplianceStepTypeRequest(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ComplianceStepTypeRequest fromValue(String value) {
    for (ComplianceStepTypeRequest b : ComplianceStepTypeRequest.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
