/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.ComplianceStep;
import com.finbourne.sdk.services.lusid.model.ComplianceTemplateParameter;
import com.finbourne.sdk.services.lusid.model.PerpetualProperty;
import com.finbourne.sdk.services.lusid.model.ResourceId;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * ComplianceTemplateVariation
 */
@JsonPropertyOrder({
  ComplianceTemplateVariation.JSON_PROPERTY_LABEL,
  ComplianceTemplateVariation.JSON_PROPERTY_DESCRIPTION,
  ComplianceTemplateVariation.JSON_PROPERTY_REQUIRED_PARAMETERS,
  ComplianceTemplateVariation.JSON_PROPERTY_PROPERTIES,
  ComplianceTemplateVariation.JSON_PROPERTY_ACCEPTED_ADDRESS_KEYS,
  ComplianceTemplateVariation.JSON_PROPERTY_STEPS,
  ComplianceTemplateVariation.JSON_PROPERTY_REFERENCED_GROUP_LABEL
})

public class ComplianceTemplateVariation {
  public static final String JSON_PROPERTY_LABEL = "label";
  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String label;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String description;

  public static final String JSON_PROPERTY_REQUIRED_PARAMETERS = "requiredParameters";
  @JsonProperty(JSON_PROPERTY_REQUIRED_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<ComplianceTemplateParameter> requiredParameters = new ArrayList<>();

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private Map<String, PerpetualProperty> properties = new HashMap<>();

  public static final String JSON_PROPERTY_ACCEPTED_ADDRESS_KEYS = "acceptedAddressKeys";
  @JsonProperty(JSON_PROPERTY_ACCEPTED_ADDRESS_KEYS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private ResourceId acceptedAddressKeys;

  public static final String JSON_PROPERTY_STEPS = "steps";
  @JsonProperty(JSON_PROPERTY_STEPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<ComplianceStep> steps = new ArrayList<>();

  public static final String JSON_PROPERTY_REFERENCED_GROUP_LABEL = "referencedGroupLabel";
  @JsonProperty(JSON_PROPERTY_REFERENCED_GROUP_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String referencedGroupLabel;

  public ComplianceTemplateVariation() {
  }

  public ComplianceTemplateVariation label(String label) {
    this.label = label;
    return this;
  }

  /**
   * Label of a Compliance Template Variation
   * @return label
   */
  @javax.annotation.Nonnull
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }


  public ComplianceTemplateVariation description(String description) {
    this.description = description;
    return this;
  }

  /**
   * The description of the Compliance Template Variation
   * @return description
   */
  @javax.annotation.Nonnull
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public ComplianceTemplateVariation requiredParameters(List<ComplianceTemplateParameter> requiredParameters) {
    this.requiredParameters = requiredParameters;
    return this;
  }

  public ComplianceTemplateVariation addRequiredParametersItem(ComplianceTemplateParameter requiredParametersItem) {
    if (this.requiredParameters == null) {
      this.requiredParameters = new ArrayList<>();
    }
    this.requiredParameters.add(requiredParametersItem);
    return this;
  }

  /**
   * A parameter required by a Compliance Template Variation
   * @return requiredParameters
   */
  @javax.annotation.Nonnull
  public List<ComplianceTemplateParameter> getRequiredParameters() {
    return requiredParameters;
  }

  public void setRequiredParameters(List<ComplianceTemplateParameter> requiredParameters) {
    this.requiredParameters = requiredParameters;
  }


  public ComplianceTemplateVariation properties(Map<String, PerpetualProperty> properties) {
    this.properties = properties;
    return this;
  }

  public ComplianceTemplateVariation putPropertiesItem(String key, PerpetualProperty propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

  /**
   * Properties associated with the Compliance Template Variation
   * @return properties
   */
  @javax.annotation.Nonnull
  public Map<String, PerpetualProperty> getProperties() {
    return properties;
  }

  public void setProperties(Map<String, PerpetualProperty> properties) {
    this.properties = properties;
  }


  public ComplianceTemplateVariation acceptedAddressKeys(ResourceId acceptedAddressKeys) {
    this.acceptedAddressKeys = acceptedAddressKeys;
    return this;
  }

  /**
   * Get acceptedAddressKeys
   * @return acceptedAddressKeys
   */
  @javax.annotation.Nonnull
  public ResourceId getAcceptedAddressKeys() {
    return acceptedAddressKeys;
  }

  public void setAcceptedAddressKeys(ResourceId acceptedAddressKeys) {
    this.acceptedAddressKeys = acceptedAddressKeys;
  }


  public ComplianceTemplateVariation steps(List<ComplianceStep> steps) {
    this.steps = steps;
    return this;
  }

  public ComplianceTemplateVariation addStepsItem(ComplianceStep stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<>();
    }
    this.steps.add(stepsItem);
    return this;
  }

  /**
   * The steps expressed in this template, with their required parameters
   * @return steps
   */
  @javax.annotation.Nonnull
  public List<ComplianceStep> getSteps() {
    return steps;
  }

  public void setSteps(List<ComplianceStep> steps) {
    this.steps = steps;
  }


  public ComplianceTemplateVariation referencedGroupLabel(String referencedGroupLabel) {
    this.referencedGroupLabel = referencedGroupLabel;
    return this;
  }

  /**
   * The label of a given referenced group in a Compliance Rule Template Variation
   * @return referencedGroupLabel
   */
  @javax.annotation.Nullable
  public String getReferencedGroupLabel() {
    return referencedGroupLabel;
  }

  public void setReferencedGroupLabel(String referencedGroupLabel) {
    this.referencedGroupLabel = referencedGroupLabel;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComplianceTemplateVariation complianceTemplateVariation = (ComplianceTemplateVariation) o;
    return Objects.equals(this.label, complianceTemplateVariation.label) &&
        Objects.equals(this.description, complianceTemplateVariation.description) &&
        Objects.equals(this.requiredParameters, complianceTemplateVariation.requiredParameters) &&
        Objects.equals(this.properties, complianceTemplateVariation.properties) &&
        Objects.equals(this.acceptedAddressKeys, complianceTemplateVariation.acceptedAddressKeys) &&
        Objects.equals(this.steps, complianceTemplateVariation.steps) &&
        Objects.equals(this.referencedGroupLabel, complianceTemplateVariation.referencedGroupLabel);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(label, description, requiredParameters, properties, acceptedAddressKeys, steps, referencedGroupLabel);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComplianceTemplateVariation {\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    requiredParameters: ").append(toIndentedString(requiredParameters)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    acceptedAddressKeys: ").append(toIndentedString(acceptedAddressKeys)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    referencedGroupLabel: ").append(toIndentedString(referencedGroupLabel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of ComplianceTemplateVariation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ComplianceTemplateVariation
   * @throws java.io.IOException if the JSON string is invalid with respect to ComplianceTemplateVariation
   */
  public static ComplianceTemplateVariation fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, ComplianceTemplateVariation.class);
  }

  /**
   * Convert an instance of ComplianceTemplateVariation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
