/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.AggregationContext;
import com.finbourne.sdk.services.lusid.model.HoldingContext;
import com.finbourne.sdk.services.lusid.model.MarketContext;
import com.finbourne.sdk.services.lusid.model.PricingContext;
import com.finbourne.sdk.services.lusid.model.TranslationContext;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * The Configuration or Calculation Recipe controls how LUSID processes a given request.  This can be used to change where market data used in pricing is loaded from and in what order, or which model is used to  price a given instrument as well as how aggregation will process the produced results.
 */
@JsonPropertyOrder({
  ConfigurationRecipe.JSON_PROPERTY_SCOPE,
  ConfigurationRecipe.JSON_PROPERTY_CODE,
  ConfigurationRecipe.JSON_PROPERTY_MARKET,
  ConfigurationRecipe.JSON_PROPERTY_PRICING,
  ConfigurationRecipe.JSON_PROPERTY_AGGREGATION,
  ConfigurationRecipe.JSON_PROPERTY_DESCRIPTION,
  ConfigurationRecipe.JSON_PROPERTY_HOLDING,
  ConfigurationRecipe.JSON_PROPERTY_TRANSLATION
})

public class ConfigurationRecipe {
  public static final String JSON_PROPERTY_SCOPE = "scope";
  @JsonProperty(JSON_PROPERTY_SCOPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String scope;

  public static final String JSON_PROPERTY_CODE = "code";
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String code;

  public static final String JSON_PROPERTY_MARKET = "market";
  @JsonProperty(JSON_PROPERTY_MARKET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private MarketContext market;

  public static final String JSON_PROPERTY_PRICING = "pricing";
  @JsonProperty(JSON_PROPERTY_PRICING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private PricingContext pricing;

  public static final String JSON_PROPERTY_AGGREGATION = "aggregation";
  @JsonProperty(JSON_PROPERTY_AGGREGATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private AggregationContext aggregation;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String description;

  public static final String JSON_PROPERTY_HOLDING = "holding";
  @JsonProperty(JSON_PROPERTY_HOLDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private HoldingContext holding;

  public static final String JSON_PROPERTY_TRANSLATION = "translation";
  @JsonProperty(JSON_PROPERTY_TRANSLATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private TranslationContext translation;

  public ConfigurationRecipe() {
  }

  public ConfigurationRecipe scope(String scope) {
    this.scope = scope;
    return this;
  }

  /**
   * The scope used when updating or inserting the Configuration Recipe.
   * @return scope
   */
  @javax.annotation.Nonnull
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }


  public ConfigurationRecipe code(String code) {
    this.code = code;
    return this;
  }

  /**
   * User given string name (code) to identify the recipe.
   * @return code
   */
  @javax.annotation.Nonnull
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }


  public ConfigurationRecipe market(MarketContext market) {
    this.market = market;
    return this;
  }

  /**
   * Get market
   * @return market
   */
  @javax.annotation.Nullable
  public MarketContext getMarket() {
    return market;
  }

  public void setMarket(MarketContext market) {
    this.market = market;
  }


  public ConfigurationRecipe pricing(PricingContext pricing) {
    this.pricing = pricing;
    return this;
  }

  /**
   * Get pricing
   * @return pricing
   */
  @javax.annotation.Nullable
  public PricingContext getPricing() {
    return pricing;
  }

  public void setPricing(PricingContext pricing) {
    this.pricing = pricing;
  }


  public ConfigurationRecipe aggregation(AggregationContext aggregation) {
    this.aggregation = aggregation;
    return this;
  }

  /**
   * Get aggregation
   * @return aggregation
   */
  @javax.annotation.Nullable
  public AggregationContext getAggregation() {
    return aggregation;
  }

  public void setAggregation(AggregationContext aggregation) {
    this.aggregation = aggregation;
  }


  public ConfigurationRecipe description(String description) {
    this.description = description;
    return this;
  }

  /**
   * User can assign a description to understand more humanly the recipe.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public ConfigurationRecipe holding(HoldingContext holding) {
    this.holding = holding;
    return this;
  }

  /**
   * Get holding
   * @return holding
   */
  @javax.annotation.Nullable
  public HoldingContext getHolding() {
    return holding;
  }

  public void setHolding(HoldingContext holding) {
    this.holding = holding;
  }


  public ConfigurationRecipe translation(TranslationContext translation) {
    this.translation = translation;
    return this;
  }

  /**
   * Get translation
   * @return translation
   */
  @javax.annotation.Nullable
  public TranslationContext getTranslation() {
    return translation;
  }

  public void setTranslation(TranslationContext translation) {
    this.translation = translation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigurationRecipe configurationRecipe = (ConfigurationRecipe) o;
    return Objects.equals(this.scope, configurationRecipe.scope) &&
        Objects.equals(this.code, configurationRecipe.code) &&
        Objects.equals(this.market, configurationRecipe.market) &&
        Objects.equals(this.pricing, configurationRecipe.pricing) &&
        Objects.equals(this.aggregation, configurationRecipe.aggregation) &&
        Objects.equals(this.description, configurationRecipe.description) &&
        Objects.equals(this.holding, configurationRecipe.holding) &&
        Objects.equals(this.translation, configurationRecipe.translation);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(scope, code, market, pricing, aggregation, description, holding, translation);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigurationRecipe {\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    market: ").append(toIndentedString(market)).append("\n");
    sb.append("    pricing: ").append(toIndentedString(pricing)).append("\n");
    sb.append("    aggregation: ").append(toIndentedString(aggregation)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    holding: ").append(toIndentedString(holding)).append("\n");
    sb.append("    translation: ").append(toIndentedString(translation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of ConfigurationRecipe given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConfigurationRecipe
   * @throws java.io.IOException if the JSON string is invalid with respect to ConfigurationRecipe
   */
  public static ConfigurationRecipe fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, ConfigurationRecipe.class);
  }

  /**
   * Convert an instance of ConfigurationRecipe to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
