/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.CreateSeriesIdentifierField;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * CreateWithholdingTaxDataset
 */
@JsonPropertyOrder({
  CreateWithholdingTaxDataset.JSON_PROPERTY_SCOPE,
  CreateWithholdingTaxDataset.JSON_PROPERTY_CODE,
  CreateWithholdingTaxDataset.JSON_PROPERTY_DIMENSIONS
})

public class CreateWithholdingTaxDataset {
  public static final String JSON_PROPERTY_SCOPE = "scope";
  @JsonProperty(JSON_PROPERTY_SCOPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String scope;

  public static final String JSON_PROPERTY_CODE = "code";
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String code;

  public static final String JSON_PROPERTY_DIMENSIONS = "dimensions";
  @JsonProperty(JSON_PROPERTY_DIMENSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<CreateSeriesIdentifierField> dimensions;

  public CreateWithholdingTaxDataset() {
  }

  public CreateWithholdingTaxDataset scope(String scope) {
    this.scope = scope;
    return this;
  }

  /**
   * The scope of the relational dataset definition.
   * @return scope
   */
  @javax.annotation.Nonnull
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }


  public CreateWithholdingTaxDataset code(String code) {
    this.code = code;
    return this;
  }

  /**
   * The code of the relational dataset definition. Together with the scope this uniquely identifies the definition.
   * @return code
   */
  @javax.annotation.Nonnull
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }


  public CreateWithholdingTaxDataset dimensions(List<CreateSeriesIdentifierField> dimensions) {
    this.dimensions = dimensions;
    return this;
  }

  public CreateWithholdingTaxDataset addDimensionsItem(CreateSeriesIdentifierField dimensionsItem) {
    if (this.dimensions == null) {
      this.dimensions = new ArrayList<>();
    }
    this.dimensions.add(dimensionsItem);
    return this;
  }

  /**
   * The dimensions, over and above the mandatory core, that this dataset is matched on. Fully customer-defined with no platform-enforced set; each is created as a series identifier, and each requires a value source declaration on the Withholding Tax Configuration naming where the engine reads its value from. May be empty, in which case matching proceeds on tax identity alone. A dimension whose name collides with a mandatory core field is rejected. The two datasets need not carry the same dimensions - one present on only a single dataset is simply not matched on when the other is queried, an ISIN dimension on the anomaly dataset alone being the usual case.
   * @return dimensions
   */
  @javax.annotation.Nullable
  public List<CreateSeriesIdentifierField> getDimensions() {
    return dimensions;
  }

  public void setDimensions(List<CreateSeriesIdentifierField> dimensions) {
    this.dimensions = dimensions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateWithholdingTaxDataset createWithholdingTaxDataset = (CreateWithholdingTaxDataset) o;
    return Objects.equals(this.scope, createWithholdingTaxDataset.scope) &&
        Objects.equals(this.code, createWithholdingTaxDataset.code) &&
        Objects.equals(this.dimensions, createWithholdingTaxDataset.dimensions);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(scope, code, dimensions);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateWithholdingTaxDataset {\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of CreateWithholdingTaxDataset given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateWithholdingTaxDataset
   * @throws java.io.IOException if the JSON string is invalid with respect to CreateWithholdingTaxDataset
   */
  public static CreateWithholdingTaxDataset fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, CreateWithholdingTaxDataset.class);
  }

  /**
   * Convert an instance of CreateWithholdingTaxDataset to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
