/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.InstrumentEvent;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Event to signify the repayment of interest accrued against a deposit holding.
 */
@JsonPropertyOrder({
  DepositInterestPaymentEvent.JSON_PROPERTY_PAYMENT_DATE,
  DepositInterestPaymentEvent.JSON_PROPERTY_EX_DATE,
  DepositInterestPaymentEvent.JSON_PROPERTY_CURRENCY
})

@com.fasterxml.jackson.annotation.JsonIgnoreProperties(
  value = "instrumentEventType", // ignore manually set instrumentEventType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the instrumentEventType to be set during deserialization
)
@com.fasterxml.jackson.annotation.JsonTypeInfo(use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, include = com.fasterxml.jackson.annotation.JsonTypeInfo.As.PROPERTY, property = "instrumentEventType", visible = true)

public class DepositInterestPaymentEvent extends InstrumentEvent {
  public static final String JSON_PROPERTY_PAYMENT_DATE = "paymentDate";
  @JsonProperty(JSON_PROPERTY_PAYMENT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime paymentDate;

  public static final String JSON_PROPERTY_EX_DATE = "exDate";
  @JsonProperty(JSON_PROPERTY_EX_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime exDate;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String currency;

  public DepositInterestPaymentEvent() {
  }

  public DepositInterestPaymentEvent paymentDate(OffsetDateTime paymentDate) {
    this.paymentDate = paymentDate;
    return this;
  }

  /**
   * Date that the interest is due to be paid.
   * @return paymentDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getPaymentDate() {
    return paymentDate;
  }

  public void setPaymentDate(OffsetDateTime paymentDate) {
    this.paymentDate = paymentDate;
  }


  public DepositInterestPaymentEvent exDate(OffsetDateTime exDate) {
    this.exDate = exDate;
    return this;
  }

  /**
   * Date that the accrued interest is calculated up until.
   * @return exDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getExDate() {
    return exDate;
  }

  public void setExDate(OffsetDateTime exDate) {
    this.exDate = exDate;
  }


  public DepositInterestPaymentEvent currency(String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Currency of the repayment.
   * @return currency
   */
  @javax.annotation.Nonnull
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepositInterestPaymentEvent depositInterestPaymentEvent = (DepositInterestPaymentEvent) o;
    return Objects.equals(this.paymentDate, depositInterestPaymentEvent.paymentDate) &&
        Objects.equals(this.exDate, depositInterestPaymentEvent.exDate) &&
        Objects.equals(this.currency, depositInterestPaymentEvent.currency) &&
        super.equals(o);
  }

  @Override
 public int hashCode() {
    return Objects.hash(paymentDate, exDate, currency, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepositInterestPaymentEvent {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    paymentDate: ").append(toIndentedString(paymentDate)).append("\n");
    sb.append("    exDate: ").append(toIndentedString(exDate)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of DepositInterestPaymentEvent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DepositInterestPaymentEvent
   * @throws java.io.IOException if the JSON string is invalid with respect to DepositInterestPaymentEvent
   */
  public static DepositInterestPaymentEvent fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, DepositInterestPaymentEvent.class);
  }

  /**
   * Convert an instance of DepositInterestPaymentEvent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
