/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.ComponentFilter;
import com.finbourne.sdk.services.lusid.model.ExternalFeeComponentFilter;
import com.finbourne.sdk.services.lusid.model.Property;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * FundConfigurationRequest
 */
@JsonPropertyOrder({
  FundConfigurationRequest.JSON_PROPERTY_CODE,
  FundConfigurationRequest.JSON_PROPERTY_DISPLAY_NAME,
  FundConfigurationRequest.JSON_PROPERTY_DESCRIPTION,
  FundConfigurationRequest.JSON_PROPERTY_DEALING_FILTERS,
  FundConfigurationRequest.JSON_PROPERTY_PNL_FILTERS,
  FundConfigurationRequest.JSON_PROPERTY_BACK_OUT_FILTERS,
  FundConfigurationRequest.JSON_PROPERTY_EXTERNAL_FEE_FILTERS,
  FundConfigurationRequest.JSON_PROPERTY_PROPERTIES
})

public class FundConfigurationRequest {
  public static final String JSON_PROPERTY_CODE = "code";
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String code;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String displayName;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String description;

  public static final String JSON_PROPERTY_DEALING_FILTERS = "dealingFilters";
  @JsonProperty(JSON_PROPERTY_DEALING_FILTERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<ComponentFilter> dealingFilters = new ArrayList<>();

  public static final String JSON_PROPERTY_PNL_FILTERS = "pnlFilters";
  @JsonProperty(JSON_PROPERTY_PNL_FILTERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<ComponentFilter> pnlFilters = new ArrayList<>();

  public static final String JSON_PROPERTY_BACK_OUT_FILTERS = "backOutFilters";
  @JsonProperty(JSON_PROPERTY_BACK_OUT_FILTERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<ComponentFilter> backOutFilters = new ArrayList<>();

  public static final String JSON_PROPERTY_EXTERNAL_FEE_FILTERS = "externalFeeFilters";
  @JsonProperty(JSON_PROPERTY_EXTERNAL_FEE_FILTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<ExternalFeeComponentFilter> externalFeeFilters;

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Map<String, Property> properties;

  public FundConfigurationRequest() {
  }

  public FundConfigurationRequest code(String code) {
    this.code = code;
    return this;
  }

  /**
   * 
   * @return code
   */
  @javax.annotation.Nonnull
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }


  public FundConfigurationRequest displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * The name of the Fund.
   * @return displayName
   */
  @javax.annotation.Nullable
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  public FundConfigurationRequest description(String description) {
    this.description = description;
    return this;
  }

  /**
   * A description for the Fund.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public FundConfigurationRequest dealingFilters(List<ComponentFilter> dealingFilters) {
    this.dealingFilters = dealingFilters;
    return this;
  }

  public FundConfigurationRequest addDealingFiltersItem(ComponentFilter dealingFiltersItem) {
    if (this.dealingFilters == null) {
      this.dealingFilters = new ArrayList<>();
    }
    this.dealingFilters.add(dealingFiltersItem);
    return this;
  }

  /**
   * The set of filters used to decide which JE lines are included in the dealing.
   * @return dealingFilters
   */
  @javax.annotation.Nonnull
  public List<ComponentFilter> getDealingFilters() {
    return dealingFilters;
  }

  public void setDealingFilters(List<ComponentFilter> dealingFilters) {
    this.dealingFilters = dealingFilters;
  }


  public FundConfigurationRequest pnlFilters(List<ComponentFilter> pnlFilters) {
    this.pnlFilters = pnlFilters;
    return this;
  }

  public FundConfigurationRequest addPnlFiltersItem(ComponentFilter pnlFiltersItem) {
    if (this.pnlFilters == null) {
      this.pnlFilters = new ArrayList<>();
    }
    this.pnlFilters.add(pnlFiltersItem);
    return this;
  }

  /**
   * The set of filters used to decide which JE lines are included in the PnL.
   * @return pnlFilters
   */
  @javax.annotation.Nonnull
  public List<ComponentFilter> getPnlFilters() {
    return pnlFilters;
  }

  public void setPnlFilters(List<ComponentFilter> pnlFilters) {
    this.pnlFilters = pnlFilters;
  }


  public FundConfigurationRequest backOutFilters(List<ComponentFilter> backOutFilters) {
    this.backOutFilters = backOutFilters;
    return this;
  }

  public FundConfigurationRequest addBackOutFiltersItem(ComponentFilter backOutFiltersItem) {
    if (this.backOutFilters == null) {
      this.backOutFilters = new ArrayList<>();
    }
    this.backOutFilters.add(backOutFiltersItem);
    return this;
  }

  /**
   * The set of filters used to decide which JE lines are included in the back outs.
   * @return backOutFilters
   */
  @javax.annotation.Nonnull
  public List<ComponentFilter> getBackOutFilters() {
    return backOutFilters;
  }

  public void setBackOutFilters(List<ComponentFilter> backOutFilters) {
    this.backOutFilters = backOutFilters;
  }


  public FundConfigurationRequest externalFeeFilters(List<ExternalFeeComponentFilter> externalFeeFilters) {
    this.externalFeeFilters = externalFeeFilters;
    return this;
  }

  public FundConfigurationRequest addExternalFeeFiltersItem(ExternalFeeComponentFilter externalFeeFiltersItem) {
    if (this.externalFeeFilters == null) {
      this.externalFeeFilters = new ArrayList<>();
    }
    this.externalFeeFilters.add(externalFeeFiltersItem);
    return this;
  }

  /**
   * The set of filters used to decide which JE lines are used for inputting fees from an external source.
   * @return externalFeeFilters
   */
  @javax.annotation.Nullable
  public List<ExternalFeeComponentFilter> getExternalFeeFilters() {
    return externalFeeFilters;
  }

  public void setExternalFeeFilters(List<ExternalFeeComponentFilter> externalFeeFilters) {
    this.externalFeeFilters = externalFeeFilters;
  }


  public FundConfigurationRequest properties(Map<String, Property> properties) {
    this.properties = properties;
    return this;
  }

  public FundConfigurationRequest putPropertiesItem(String key, Property propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

  /**
   * A set of properties for the Fund Configuration.
   * @return properties
   */
  @javax.annotation.Nullable
  public Map<String, Property> getProperties() {
    return properties;
  }

  public void setProperties(Map<String, Property> properties) {
    this.properties = properties;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FundConfigurationRequest fundConfigurationRequest = (FundConfigurationRequest) o;
    return Objects.equals(this.code, fundConfigurationRequest.code) &&
        Objects.equals(this.displayName, fundConfigurationRequest.displayName) &&
        Objects.equals(this.description, fundConfigurationRequest.description) &&
        Objects.equals(this.dealingFilters, fundConfigurationRequest.dealingFilters) &&
        Objects.equals(this.pnlFilters, fundConfigurationRequest.pnlFilters) &&
        Objects.equals(this.backOutFilters, fundConfigurationRequest.backOutFilters) &&
        Objects.equals(this.externalFeeFilters, fundConfigurationRequest.externalFeeFilters) &&
        Objects.equals(this.properties, fundConfigurationRequest.properties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(code, displayName, description, dealingFilters, pnlFilters, backOutFilters, externalFeeFilters, properties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FundConfigurationRequest {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    dealingFilters: ").append(toIndentedString(dealingFilters)).append("\n");
    sb.append("    pnlFilters: ").append(toIndentedString(pnlFilters)).append("\n");
    sb.append("    backOutFilters: ").append(toIndentedString(backOutFilters)).append("\n");
    sb.append("    externalFeeFilters: ").append(toIndentedString(externalFeeFilters)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of FundConfigurationRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FundConfigurationRequest
   * @throws java.io.IOException if the JSON string is invalid with respect to FundConfigurationRequest
   */
  public static FundConfigurationRequest fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, FundConfigurationRequest.class);
  }

  /**
   * Convert an instance of FundConfigurationRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
