/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.CurrencyAndAmount;
import com.finbourne.sdk.services.lusid.model.JournalEntryLineShareClassBreakdown;
import com.finbourne.sdk.services.lusid.model.Link;
import com.finbourne.sdk.services.lusid.model.PerpetualProperty;
import com.finbourne.sdk.services.lusid.model.Property;
import com.finbourne.sdk.services.lusid.model.ResourceId;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * A Journal Entry line entity specifically for fund valuation point lines.
 */
@JsonPropertyOrder({
  FundJournalEntryLine.JSON_PROPERTY_ACCOUNTING_DATE,
  FundJournalEntryLine.JSON_PROPERTY_ACTIVITY_DATE,
  FundJournalEntryLine.JSON_PROPERTY_PORTFOLIO_ID,
  FundJournalEntryLine.JSON_PROPERTY_INSTRUMENT_ID,
  FundJournalEntryLine.JSON_PROPERTY_INSTRUMENT_SCOPE,
  FundJournalEntryLine.JSON_PROPERTY_SUB_HOLDING_KEYS,
  FundJournalEntryLine.JSON_PROPERTY_TAX_LOT_ID,
  FundJournalEntryLine.JSON_PROPERTY_GENERAL_LEDGER_ACCOUNT_CODE,
  FundJournalEntryLine.JSON_PROPERTY_LOCAL,
  FundJournalEntryLine.JSON_PROPERTY_BASE,
  FundJournalEntryLine.JSON_PROPERTY_UNITS,
  FundJournalEntryLine.JSON_PROPERTY_POSTING_MODULE_CODE,
  FundJournalEntryLine.JSON_PROPERTY_POSTING_RULE,
  FundJournalEntryLine.JSON_PROPERTY_AS_AT_DATE,
  FundJournalEntryLine.JSON_PROPERTY_ACTIVITIES_DESCRIPTION,
  FundJournalEntryLine.JSON_PROPERTY_SOURCE_TYPE,
  FundJournalEntryLine.JSON_PROPERTY_SOURCE_ID,
  FundJournalEntryLine.JSON_PROPERTY_PROPERTIES,
  FundJournalEntryLine.JSON_PROPERTY_MOVEMENT_NAME,
  FundJournalEntryLine.JSON_PROPERTY_HOLDING_TYPE,
  FundJournalEntryLine.JSON_PROPERTY_ECONOMIC_BUCKET,
  FundJournalEntryLine.JSON_PROPERTY_ECONOMIC_BUCKET_COMPONENT,
  FundJournalEntryLine.JSON_PROPERTY_ECONOMIC_BUCKET_VARIANT,
  FundJournalEntryLine.JSON_PROPERTY_LEVELS,
  FundJournalEntryLine.JSON_PROPERTY_SOURCE_LEVELS,
  FundJournalEntryLine.JSON_PROPERTY_MOVEMENT_SIGN,
  FundJournalEntryLine.JSON_PROPERTY_HOLDING_SIGN,
  FundJournalEntryLine.JSON_PROPERTY_LEDGER_COLUMN,
  FundJournalEntryLine.JSON_PROPERTY_JOURNAL_ENTRY_LINE_TYPE,
  FundJournalEntryLine.JSON_PROPERTY_SHARE_CLASS_BREAKDOWNS,
  FundJournalEntryLine.JSON_PROPERTY_LINKS
})

public class FundJournalEntryLine {
  public static final String JSON_PROPERTY_ACCOUNTING_DATE = "accountingDate";
  @JsonProperty(JSON_PROPERTY_ACCOUNTING_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OffsetDateTime accountingDate;

  public static final String JSON_PROPERTY_ACTIVITY_DATE = "activityDate";
  @JsonProperty(JSON_PROPERTY_ACTIVITY_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OffsetDateTime activityDate;

  public static final String JSON_PROPERTY_PORTFOLIO_ID = "portfolioId";
  @JsonProperty(JSON_PROPERTY_PORTFOLIO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private ResourceId portfolioId;

  public static final String JSON_PROPERTY_INSTRUMENT_ID = "instrumentId";
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String instrumentId;

  public static final String JSON_PROPERTY_INSTRUMENT_SCOPE = "instrumentScope";
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_SCOPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String instrumentScope;

  public static final String JSON_PROPERTY_SUB_HOLDING_KEYS = "subHoldingKeys";
  @JsonProperty(JSON_PROPERTY_SUB_HOLDING_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Map<String, PerpetualProperty> subHoldingKeys;

  public static final String JSON_PROPERTY_TAX_LOT_ID = "taxLotId";
  @JsonProperty(JSON_PROPERTY_TAX_LOT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String taxLotId;

  public static final String JSON_PROPERTY_GENERAL_LEDGER_ACCOUNT_CODE = "generalLedgerAccountCode";
  @JsonProperty(JSON_PROPERTY_GENERAL_LEDGER_ACCOUNT_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String generalLedgerAccountCode;

  public static final String JSON_PROPERTY_LOCAL = "local";
  @JsonProperty(JSON_PROPERTY_LOCAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private CurrencyAndAmount local;

  public static final String JSON_PROPERTY_BASE = "base";
  @JsonProperty(JSON_PROPERTY_BASE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private CurrencyAndAmount base;

  public static final String JSON_PROPERTY_UNITS = "units";
  @JsonProperty(JSON_PROPERTY_UNITS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private java.math.BigDecimal units;

  public static final String JSON_PROPERTY_POSTING_MODULE_CODE = "postingModuleCode";
  @JsonProperty(JSON_PROPERTY_POSTING_MODULE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String postingModuleCode;

  public static final String JSON_PROPERTY_POSTING_RULE = "postingRule";
  @JsonProperty(JSON_PROPERTY_POSTING_RULE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String postingRule;

  public static final String JSON_PROPERTY_AS_AT_DATE = "asAtDate";
  @JsonProperty(JSON_PROPERTY_AS_AT_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OffsetDateTime asAtDate;

  public static final String JSON_PROPERTY_ACTIVITIES_DESCRIPTION = "activitiesDescription";
  @JsonProperty(JSON_PROPERTY_ACTIVITIES_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String activitiesDescription;

  public static final String JSON_PROPERTY_SOURCE_TYPE = "sourceType";
  @JsonProperty(JSON_PROPERTY_SOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String sourceType;

  public static final String JSON_PROPERTY_SOURCE_ID = "sourceId";
  @JsonProperty(JSON_PROPERTY_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String sourceId;

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Map<String, Property> properties;

  public static final String JSON_PROPERTY_MOVEMENT_NAME = "movementName";
  @JsonProperty(JSON_PROPERTY_MOVEMENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String movementName;

  public static final String JSON_PROPERTY_HOLDING_TYPE = "holdingType";
  @JsonProperty(JSON_PROPERTY_HOLDING_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String holdingType;

  public static final String JSON_PROPERTY_ECONOMIC_BUCKET = "economicBucket";
  @JsonProperty(JSON_PROPERTY_ECONOMIC_BUCKET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String economicBucket;

  public static final String JSON_PROPERTY_ECONOMIC_BUCKET_COMPONENT = "economicBucketComponent";
  @JsonProperty(JSON_PROPERTY_ECONOMIC_BUCKET_COMPONENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String economicBucketComponent;

  public static final String JSON_PROPERTY_ECONOMIC_BUCKET_VARIANT = "economicBucketVariant";
  @JsonProperty(JSON_PROPERTY_ECONOMIC_BUCKET_VARIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String economicBucketVariant;

  public static final String JSON_PROPERTY_LEVELS = "levels";
  @JsonProperty(JSON_PROPERTY_LEVELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<String> levels;

  public static final String JSON_PROPERTY_SOURCE_LEVELS = "sourceLevels";
  @JsonProperty(JSON_PROPERTY_SOURCE_LEVELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<String> sourceLevels;

  public static final String JSON_PROPERTY_MOVEMENT_SIGN = "movementSign";
  @JsonProperty(JSON_PROPERTY_MOVEMENT_SIGN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String movementSign;

  public static final String JSON_PROPERTY_HOLDING_SIGN = "holdingSign";
  @JsonProperty(JSON_PROPERTY_HOLDING_SIGN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String holdingSign;

  public static final String JSON_PROPERTY_LEDGER_COLUMN = "ledgerColumn";
  @JsonProperty(JSON_PROPERTY_LEDGER_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String ledgerColumn;

  public static final String JSON_PROPERTY_JOURNAL_ENTRY_LINE_TYPE = "journalEntryLineType";
  @JsonProperty(JSON_PROPERTY_JOURNAL_ENTRY_LINE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String journalEntryLineType;

  public static final String JSON_PROPERTY_SHARE_CLASS_BREAKDOWNS = "shareClassBreakdowns";
  @JsonProperty(JSON_PROPERTY_SHARE_CLASS_BREAKDOWNS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<JournalEntryLineShareClassBreakdown> shareClassBreakdowns;

  public static final String JSON_PROPERTY_LINKS = "links";
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<Link> links;

  public FundJournalEntryLine() {
  }

  public FundJournalEntryLine accountingDate(OffsetDateTime accountingDate) {
    this.accountingDate = accountingDate;
    return this;
  }

  /**
   * The Journal Entry Line accounting date.
   * @return accountingDate
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getAccountingDate() {
    return accountingDate;
  }

  public void setAccountingDate(OffsetDateTime accountingDate) {
    this.accountingDate = accountingDate;
  }


  public FundJournalEntryLine activityDate(OffsetDateTime activityDate) {
    this.activityDate = activityDate;
    return this;
  }

  /**
   * The actual date of the activity. Differs from the accounting date when creating journals that would occur in a closed period.
   * @return activityDate
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getActivityDate() {
    return activityDate;
  }

  public void setActivityDate(OffsetDateTime activityDate) {
    this.activityDate = activityDate;
  }


  public FundJournalEntryLine portfolioId(ResourceId portfolioId) {
    this.portfolioId = portfolioId;
    return this;
  }

  /**
   * Get portfolioId
   * @return portfolioId
   */
  @javax.annotation.Nonnull
  public ResourceId getPortfolioId() {
    return portfolioId;
  }

  public void setPortfolioId(ResourceId portfolioId) {
    this.portfolioId = portfolioId;
  }


  public FundJournalEntryLine instrumentId(String instrumentId) {
    this.instrumentId = instrumentId;
    return this;
  }

  /**
   * To indicate the instrument of the transaction that the Journal Entry Line posted for, if applicable.
   * @return instrumentId
   */
  @javax.annotation.Nonnull
  public String getInstrumentId() {
    return instrumentId;
  }

  public void setInstrumentId(String instrumentId) {
    this.instrumentId = instrumentId;
  }


  public FundJournalEntryLine instrumentScope(String instrumentScope) {
    this.instrumentScope = instrumentScope;
    return this;
  }

  /**
   * The scope in which the Journal Entry Line instrument is in.
   * @return instrumentScope
   */
  @javax.annotation.Nonnull
  public String getInstrumentScope() {
    return instrumentScope;
  }

  public void setInstrumentScope(String instrumentScope) {
    this.instrumentScope = instrumentScope;
  }


  public FundJournalEntryLine subHoldingKeys(Map<String, PerpetualProperty> subHoldingKeys) {
    this.subHoldingKeys = subHoldingKeys;
    return this;
  }

  public FundJournalEntryLine putSubHoldingKeysItem(String key, PerpetualProperty subHoldingKeysItem) {
    if (this.subHoldingKeys == null) {
      this.subHoldingKeys = new HashMap<>();
    }
    this.subHoldingKeys.put(key, subHoldingKeysItem);
    return this;
  }

  /**
   * The sub-holding properties which are part of the AccountingKey.
   * @return subHoldingKeys
   */
  @javax.annotation.Nullable
  public Map<String, PerpetualProperty> getSubHoldingKeys() {
    return subHoldingKeys;
  }

  public void setSubHoldingKeys(Map<String, PerpetualProperty> subHoldingKeys) {
    this.subHoldingKeys = subHoldingKeys;
  }


  public FundJournalEntryLine taxLotId(String taxLotId) {
    this.taxLotId = taxLotId;
    return this;
  }

  /**
   * If the holding type is &#39;B&#39; (settled cash balance), this is 1. Otherwise, this is the ID of a tax lot if applicable, or the source ID of the original transaction if not.
   * @return taxLotId
   */
  @javax.annotation.Nullable
  public String getTaxLotId() {
    return taxLotId;
  }

  public void setTaxLotId(String taxLotId) {
    this.taxLotId = taxLotId;
  }


  public FundJournalEntryLine generalLedgerAccountCode(String generalLedgerAccountCode) {
    this.generalLedgerAccountCode = generalLedgerAccountCode;
    return this;
  }

  /**
   * The code of the account in the general ledger the Journal Entry was posted to.
   * @return generalLedgerAccountCode
   */
  @javax.annotation.Nonnull
  public String getGeneralLedgerAccountCode() {
    return generalLedgerAccountCode;
  }

  public void setGeneralLedgerAccountCode(String generalLedgerAccountCode) {
    this.generalLedgerAccountCode = generalLedgerAccountCode;
  }


  public FundJournalEntryLine local(CurrencyAndAmount local) {
    this.local = local;
    return this;
  }

  /**
   * Get local
   * @return local
   */
  @javax.annotation.Nonnull
  public CurrencyAndAmount getLocal() {
    return local;
  }

  public void setLocal(CurrencyAndAmount local) {
    this.local = local;
  }


  public FundJournalEntryLine base(CurrencyAndAmount base) {
    this.base = base;
    return this;
  }

  /**
   * Get base
   * @return base
   */
  @javax.annotation.Nonnull
  public CurrencyAndAmount getBase() {
    return base;
  }

  public void setBase(CurrencyAndAmount base) {
    this.base = base;
  }


  public FundJournalEntryLine units(java.math.BigDecimal units) {
    this.units = units;
    return this;
  }

  /**
   * Units held for the Journal Entry Line.
   * @return units
   */
  @javax.annotation.Nonnull
  public java.math.BigDecimal getUnits() {
    return units;
  }

  public void setUnits(java.math.BigDecimal units) {
    this.units = units;
  }


  public FundJournalEntryLine postingModuleCode(String postingModuleCode) {
    this.postingModuleCode = postingModuleCode;
    return this;
  }

  /**
   * The code of the posting module where the posting rules derived the Journal Entry lines.
   * @return postingModuleCode
   */
  @javax.annotation.Nullable
  public String getPostingModuleCode() {
    return postingModuleCode;
  }

  public void setPostingModuleCode(String postingModuleCode) {
    this.postingModuleCode = postingModuleCode;
  }


  public FundJournalEntryLine postingRule(String postingRule) {
    this.postingRule = postingRule;
    return this;
  }

  /**
   * The rule generating the Journal Entry Line.
   * @return postingRule
   */
  @javax.annotation.Nonnull
  public String getPostingRule() {
    return postingRule;
  }

  public void setPostingRule(String postingRule) {
    this.postingRule = postingRule;
  }


  public FundJournalEntryLine asAtDate(OffsetDateTime asAtDate) {
    this.asAtDate = asAtDate;
    return this;
  }

  /**
   * The corresponding input date and time of the Transaction generating the Journal Entry Line.
   * @return asAtDate
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getAsAtDate() {
    return asAtDate;
  }

  public void setAsAtDate(OffsetDateTime asAtDate) {
    this.asAtDate = asAtDate;
  }


  public FundJournalEntryLine activitiesDescription(String activitiesDescription) {
    this.activitiesDescription = activitiesDescription;
    return this;
  }

  /**
   * This would be the description of the business activities this Journal Entry Line is for.
   * @return activitiesDescription
   */
  @javax.annotation.Nullable
  public String getActivitiesDescription() {
    return activitiesDescription;
  }

  public void setActivitiesDescription(String activitiesDescription) {
    this.activitiesDescription = activitiesDescription;
  }


  public FundJournalEntryLine sourceType(String sourceType) {
    this.sourceType = sourceType;
    return this;
  }

  /**
   * The type of source for the Journal Entry Line. Available values: LusidTransaction, LusidValuation, Manual, External.
   * @return sourceType
   */
  @javax.annotation.Nonnull
  public String getSourceType() {
    return sourceType;
  }

  public void setSourceType(String sourceType) {
    this.sourceType = sourceType;
  }


  public FundJournalEntryLine sourceId(String sourceId) {
    this.sourceId = sourceId;
    return this;
  }

  /**
   * For the Lusid Source Type this will be the txn Id. For the rest will be what the user populates.
   * @return sourceId
   */
  @javax.annotation.Nonnull
  public String getSourceId() {
    return sourceId;
  }

  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }


  public FundJournalEntryLine properties(Map<String, Property> properties) {
    this.properties = properties;
    return this;
  }

  public FundJournalEntryLine putPropertiesItem(String key, Property propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

  /**
   * A set of properties for the Abor.
   * @return properties
   */
  @javax.annotation.Nullable
  public Map<String, Property> getProperties() {
    return properties;
  }

  public void setProperties(Map<String, Property> properties) {
    this.properties = properties;
  }


  public FundJournalEntryLine movementName(String movementName) {
    this.movementName = movementName;
    return this;
  }

  /**
   * If the JE Line is generated from a transaction, the name of the side in the transaction type&#39;s movement. If from a valuation, this is &#39;MarkToMarket&#39;.
   * @return movementName
   */
  @javax.annotation.Nullable
  public String getMovementName() {
    return movementName;
  }

  public void setMovementName(String movementName) {
    this.movementName = movementName;
  }


  public FundJournalEntryLine holdingType(String holdingType) {
    this.holdingType = holdingType;
    return this;
  }

  /**
   * One of the LUSID holding types such as &#39;P&#39; for position or &#39;B&#39; for settled cash balance.
   * @return holdingType
   */
  @javax.annotation.Nonnull
  public String getHoldingType() {
    return holdingType;
  }

  public void setHoldingType(String holdingType) {
    this.holdingType = holdingType;
  }


  public FundJournalEntryLine economicBucket(String economicBucket) {
    this.economicBucket = economicBucket;
    return this;
  }

  /**
   * LUSID automatically categorises a JE Line into a broad economic bucket such as &#39;NA_Cost&#39; or &#39;PL_RealPriceGL&#39;.
   * @return economicBucket
   */
  @javax.annotation.Nonnull
  public String getEconomicBucket() {
    return economicBucket;
  }

  public void setEconomicBucket(String economicBucket) {
    this.economicBucket = economicBucket;
  }


  public FundJournalEntryLine economicBucketComponent(String economicBucketComponent) {
    this.economicBucketComponent = economicBucketComponent;
    return this;
  }

  /**
   * Sub bucket of the economic bucket. Available values: Undefined, Premium, OID, MarketDiscount, AcquisitionPremium, CoreMarket, CrossGainLoss, TradedInterest, Income, Expense.
   * @return economicBucketComponent
   */
  @javax.annotation.Nullable
  public String getEconomicBucketComponent() {
    return economicBucketComponent;
  }

  public void setEconomicBucketComponent(String economicBucketComponent) {
    this.economicBucketComponent = economicBucketComponent;
  }


  public FundJournalEntryLine economicBucketVariant(String economicBucketVariant) {
    this.economicBucketVariant = economicBucketVariant;
    return this;
  }

  /**
   * Further categorisation of a journal entry line. LongTerm/ShortTerm: based on whether the ActivityDate is more than a year after the purchase trade date. TradeDateToSettlementDate: FX gain/loss between trade date and settlement date. InLieuSubstitution: FX gain/loss from settling in a different currency when the original settlement currency is the portfolio base currency. Available values: Undefined, ShortTerm, LongTerm, Bought, Sold, TradeDateToSettlementDate, Rounding, InLieuSubstitution.
   * @return economicBucketVariant
   */
  @javax.annotation.Nullable
  public String getEconomicBucketVariant() {
    return economicBucketVariant;
  }

  public void setEconomicBucketVariant(String economicBucketVariant) {
    this.economicBucketVariant = economicBucketVariant;
  }


  public FundJournalEntryLine levels(List<String> levels) {
    this.levels = levels;
    return this;
  }

  public FundJournalEntryLine addLevelsItem(String levelsItem) {
    if (this.levels == null) {
      this.levels = new ArrayList<>();
    }
    this.levels.add(levelsItem);
    return this;
  }

  /**
   * Resolved data from the general ledger profile where the GeneralLedgerProfileCode is specified in the GetJournalEntryLines request body.
   * @return levels
   */
  @javax.annotation.Nullable
  public List<String> getLevels() {
    return levels;
  }

  public void setLevels(List<String> levels) {
    this.levels = levels;
  }


  public FundJournalEntryLine sourceLevels(List<String> sourceLevels) {
    this.sourceLevels = sourceLevels;
    return this;
  }

  public FundJournalEntryLine addSourceLevelsItem(String sourceLevelsItem) {
    if (this.sourceLevels == null) {
      this.sourceLevels = new ArrayList<>();
    }
    this.sourceLevels.add(sourceLevelsItem);
    return this;
  }

  /**
   * Source data from the general ledger profile where the GeneralLedgerProfileCode is specified in the GetJournalEntryLines request body.
   * @return sourceLevels
   */
  @javax.annotation.Nullable
  public List<String> getSourceLevels() {
    return sourceLevels;
  }

  public void setSourceLevels(List<String> sourceLevels) {
    this.sourceLevels = sourceLevels;
  }


  public FundJournalEntryLine movementSign(String movementSign) {
    this.movementSign = movementSign;
    return this;
  }

  /**
   * Indicates if the Journal Entry Line corresponds to a Long or Short movement. Available values: NA, Long, Short.
   * @return movementSign
   */
  @javax.annotation.Nullable
  public String getMovementSign() {
    return movementSign;
  }

  public void setMovementSign(String movementSign) {
    this.movementSign = movementSign;
  }


  public FundJournalEntryLine holdingSign(String holdingSign) {
    this.holdingSign = holdingSign;
    return this;
  }

  /**
   * Indicates if the Journal Entry Line is operating against a Long or Short holding. Available values: NA, Long, Short.
   * @return holdingSign
   */
  @javax.annotation.Nullable
  public String getHoldingSign() {
    return holdingSign;
  }

  public void setHoldingSign(String holdingSign) {
    this.holdingSign = holdingSign;
  }


  public FundJournalEntryLine ledgerColumn(String ledgerColumn) {
    this.ledgerColumn = ledgerColumn;
    return this;
  }

  /**
   * Indicates if the Journal Entry Line is credit or debit. Available values: Debit, Credit.
   * @return ledgerColumn
   */
  @javax.annotation.Nullable
  public String getLedgerColumn() {
    return ledgerColumn;
  }

  public void setLedgerColumn(String ledgerColumn) {
    this.ledgerColumn = ledgerColumn;
  }


  public FundJournalEntryLine journalEntryLineType(String journalEntryLineType) {
    this.journalEntryLineType = journalEntryLineType;
    return this;
  }

  /**
   * Indicates the Journal Entry Line type. Available values: Default, Reversal, TrueUp.
   * @return journalEntryLineType
   */
  @javax.annotation.Nullable
  public String getJournalEntryLineType() {
    return journalEntryLineType;
  }

  public void setJournalEntryLineType(String journalEntryLineType) {
    this.journalEntryLineType = journalEntryLineType;
  }


  public FundJournalEntryLine shareClassBreakdowns(List<JournalEntryLineShareClassBreakdown> shareClassBreakdowns) {
    this.shareClassBreakdowns = shareClassBreakdowns;
    return this;
  }

  public FundJournalEntryLine addShareClassBreakdownsItem(JournalEntryLineShareClassBreakdown shareClassBreakdownsItem) {
    if (this.shareClassBreakdowns == null) {
      this.shareClassBreakdowns = new ArrayList<>();
    }
    this.shareClassBreakdowns.add(shareClassBreakdownsItem);
    return this;
  }

  /**
   * Share Class breakdown data for this Journal Entry Line.
   * @return shareClassBreakdowns
   */
  @javax.annotation.Nullable
  public List<JournalEntryLineShareClassBreakdown> getShareClassBreakdowns() {
    return shareClassBreakdowns;
  }

  public void setShareClassBreakdowns(List<JournalEntryLineShareClassBreakdown> shareClassBreakdowns) {
    this.shareClassBreakdowns = shareClassBreakdowns;
  }


  public FundJournalEntryLine links(List<Link> links) {
    this.links = links;
    return this;
  }

  public FundJournalEntryLine addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @javax.annotation.Nullable
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FundJournalEntryLine fundJournalEntryLine = (FundJournalEntryLine) o;
    return Objects.equals(this.accountingDate, fundJournalEntryLine.accountingDate) &&
        Objects.equals(this.activityDate, fundJournalEntryLine.activityDate) &&
        Objects.equals(this.portfolioId, fundJournalEntryLine.portfolioId) &&
        Objects.equals(this.instrumentId, fundJournalEntryLine.instrumentId) &&
        Objects.equals(this.instrumentScope, fundJournalEntryLine.instrumentScope) &&
        Objects.equals(this.subHoldingKeys, fundJournalEntryLine.subHoldingKeys) &&
        Objects.equals(this.taxLotId, fundJournalEntryLine.taxLotId) &&
        Objects.equals(this.generalLedgerAccountCode, fundJournalEntryLine.generalLedgerAccountCode) &&
        Objects.equals(this.local, fundJournalEntryLine.local) &&
        Objects.equals(this.base, fundJournalEntryLine.base) &&
        (this.units.compareTo(fundJournalEntryLine.getUnits()) == 0) &&
        Objects.equals(this.postingModuleCode, fundJournalEntryLine.postingModuleCode) &&
        Objects.equals(this.postingRule, fundJournalEntryLine.postingRule) &&
        Objects.equals(this.asAtDate, fundJournalEntryLine.asAtDate) &&
        Objects.equals(this.activitiesDescription, fundJournalEntryLine.activitiesDescription) &&
        Objects.equals(this.sourceType, fundJournalEntryLine.sourceType) &&
        Objects.equals(this.sourceId, fundJournalEntryLine.sourceId) &&
        Objects.equals(this.properties, fundJournalEntryLine.properties) &&
        Objects.equals(this.movementName, fundJournalEntryLine.movementName) &&
        Objects.equals(this.holdingType, fundJournalEntryLine.holdingType) &&
        Objects.equals(this.economicBucket, fundJournalEntryLine.economicBucket) &&
        Objects.equals(this.economicBucketComponent, fundJournalEntryLine.economicBucketComponent) &&
        Objects.equals(this.economicBucketVariant, fundJournalEntryLine.economicBucketVariant) &&
        Objects.equals(this.levels, fundJournalEntryLine.levels) &&
        Objects.equals(this.sourceLevels, fundJournalEntryLine.sourceLevels) &&
        Objects.equals(this.movementSign, fundJournalEntryLine.movementSign) &&
        Objects.equals(this.holdingSign, fundJournalEntryLine.holdingSign) &&
        Objects.equals(this.ledgerColumn, fundJournalEntryLine.ledgerColumn) &&
        Objects.equals(this.journalEntryLineType, fundJournalEntryLine.journalEntryLineType) &&
        Objects.equals(this.shareClassBreakdowns, fundJournalEntryLine.shareClassBreakdowns) &&
        Objects.equals(this.links, fundJournalEntryLine.links);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(accountingDate, activityDate, portfolioId, instrumentId, instrumentScope, subHoldingKeys, taxLotId, generalLedgerAccountCode, local, base, units, postingModuleCode, postingRule, asAtDate, activitiesDescription, sourceType, sourceId, properties, movementName, holdingType, economicBucket, economicBucketComponent, economicBucketVariant, levels, sourceLevels, movementSign, holdingSign, ledgerColumn, journalEntryLineType, shareClassBreakdowns, links);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FundJournalEntryLine {\n");
    sb.append("    accountingDate: ").append(toIndentedString(accountingDate)).append("\n");
    sb.append("    activityDate: ").append(toIndentedString(activityDate)).append("\n");
    sb.append("    portfolioId: ").append(toIndentedString(portfolioId)).append("\n");
    sb.append("    instrumentId: ").append(toIndentedString(instrumentId)).append("\n");
    sb.append("    instrumentScope: ").append(toIndentedString(instrumentScope)).append("\n");
    sb.append("    subHoldingKeys: ").append(toIndentedString(subHoldingKeys)).append("\n");
    sb.append("    taxLotId: ").append(toIndentedString(taxLotId)).append("\n");
    sb.append("    generalLedgerAccountCode: ").append(toIndentedString(generalLedgerAccountCode)).append("\n");
    sb.append("    local: ").append(toIndentedString(local)).append("\n");
    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("    postingModuleCode: ").append(toIndentedString(postingModuleCode)).append("\n");
    sb.append("    postingRule: ").append(toIndentedString(postingRule)).append("\n");
    sb.append("    asAtDate: ").append(toIndentedString(asAtDate)).append("\n");
    sb.append("    activitiesDescription: ").append(toIndentedString(activitiesDescription)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    movementName: ").append(toIndentedString(movementName)).append("\n");
    sb.append("    holdingType: ").append(toIndentedString(holdingType)).append("\n");
    sb.append("    economicBucket: ").append(toIndentedString(economicBucket)).append("\n");
    sb.append("    economicBucketComponent: ").append(toIndentedString(economicBucketComponent)).append("\n");
    sb.append("    economicBucketVariant: ").append(toIndentedString(economicBucketVariant)).append("\n");
    sb.append("    levels: ").append(toIndentedString(levels)).append("\n");
    sb.append("    sourceLevels: ").append(toIndentedString(sourceLevels)).append("\n");
    sb.append("    movementSign: ").append(toIndentedString(movementSign)).append("\n");
    sb.append("    holdingSign: ").append(toIndentedString(holdingSign)).append("\n");
    sb.append("    ledgerColumn: ").append(toIndentedString(ledgerColumn)).append("\n");
    sb.append("    journalEntryLineType: ").append(toIndentedString(journalEntryLineType)).append("\n");
    sb.append("    shareClassBreakdowns: ").append(toIndentedString(shareClassBreakdowns)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of FundJournalEntryLine given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FundJournalEntryLine
   * @throws java.io.IOException if the JSON string is invalid with respect to FundJournalEntryLine
   */
  public static FundJournalEntryLine fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, FundJournalEntryLine.class);
  }

  /**
   * Convert an instance of FundJournalEntryLine to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
