/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.EconomicDependency;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Indicates a dependency on an FxForwardCurve.  Identical to Fx dependencies in the meaning of domestic and foreign currencies, but describes a *set* of fx rates.  These rates are quoted rates for fx forwards, which can be used to interpolate the forward rate at a specific time in the future.  In the case of pips, the absolute rates can be expressed as rate &#x3D; spotFx + pips / pipsPerUnit
 */
@JsonPropertyOrder({
  FxForwardsDependency.JSON_PROPERTY_DOMESTIC_CURRENCY,
  FxForwardsDependency.JSON_PROPERTY_FOREIGN_CURRENCY,
  FxForwardsDependency.JSON_PROPERTY_CURVE_TYPE,
  FxForwardsDependency.JSON_PROPERTY_DATE
})

@com.fasterxml.jackson.annotation.JsonIgnoreProperties(
  value = "dependencyType", // ignore manually set dependencyType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the dependencyType to be set during deserialization
)
@com.fasterxml.jackson.annotation.JsonTypeInfo(use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, include = com.fasterxml.jackson.annotation.JsonTypeInfo.As.PROPERTY, property = "dependencyType", visible = true)

public class FxForwardsDependency extends EconomicDependency {
  public static final String JSON_PROPERTY_DOMESTIC_CURRENCY = "domesticCurrency";
  @JsonProperty(JSON_PROPERTY_DOMESTIC_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String domesticCurrency;

  public static final String JSON_PROPERTY_FOREIGN_CURRENCY = "foreignCurrency";
  @JsonProperty(JSON_PROPERTY_FOREIGN_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String foreignCurrency;

  public static final String JSON_PROPERTY_CURVE_TYPE = "curveType";
  @JsonProperty(JSON_PROPERTY_CURVE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String curveType;

  public static final String JSON_PROPERTY_DATE = "date";
  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OffsetDateTime date;

  public FxForwardsDependency() {
  }

  public FxForwardsDependency domesticCurrency(String domesticCurrency) {
    this.domesticCurrency = domesticCurrency;
    return this;
  }

  /**
   * DomesticCurrency is the first currency in a currency pair quote e.g. eur-gbp, eur is the domestic currency.
   * @return domesticCurrency
   */
  @javax.annotation.Nonnull
  public String getDomesticCurrency() {
    return domesticCurrency;
  }

  public void setDomesticCurrency(String domesticCurrency) {
    this.domesticCurrency = domesticCurrency;
  }


  public FxForwardsDependency foreignCurrency(String foreignCurrency) {
    this.foreignCurrency = foreignCurrency;
    return this;
  }

  /**
   * ForeignCurrency is the second currency in a currency pair quote e.g. eur-gbp, gbp is the foreign currency.
   * @return foreignCurrency
   */
  @javax.annotation.Nonnull
  public String getForeignCurrency() {
    return foreignCurrency;
  }

  public void setForeignCurrency(String foreignCurrency) {
    this.foreignCurrency = foreignCurrency;
  }


  public FxForwardsDependency curveType(String curveType) {
    this.curveType = curveType;
    return this;
  }

  /**
   * Used to describe the format in which the curve is expressed  e.g. FxFwdCurve (general term to describe any representation), TenorFxFwdCurve, PipsFxFwdCurve.
   * @return curveType
   */
  @javax.annotation.Nonnull
  public String getCurveType() {
    return curveType;
  }

  public void setCurveType(String curveType) {
    this.curveType = curveType;
  }


  public FxForwardsDependency date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

  /**
   * The effectiveDate of the entity that this is a dependency for.  Unless there is an obvious date this should be, like for a historic reset, then this is the valuation date.
   * @return date
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FxForwardsDependency fxForwardsDependency = (FxForwardsDependency) o;
    return Objects.equals(this.domesticCurrency, fxForwardsDependency.domesticCurrency) &&
        Objects.equals(this.foreignCurrency, fxForwardsDependency.foreignCurrency) &&
        Objects.equals(this.curveType, fxForwardsDependency.curveType) &&
        Objects.equals(this.date, fxForwardsDependency.date) &&
        super.equals(o);
  }

  @Override
 public int hashCode() {
    return Objects.hash(domesticCurrency, foreignCurrency, curveType, date, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FxForwardsDependency {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    domesticCurrency: ").append(toIndentedString(domesticCurrency)).append("\n");
    sb.append("    foreignCurrency: ").append(toIndentedString(foreignCurrency)).append("\n");
    sb.append("    curveType: ").append(toIndentedString(curveType)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of FxForwardsDependency given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FxForwardsDependency
   * @throws java.io.IOException if the JSON string is invalid with respect to FxForwardsDependency
   */
  public static FxForwardsDependency fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, FxForwardsDependency.class);
  }

  /**
   * Convert an instance of FxForwardsDependency to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
