/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.ComplexMarketData;
import com.finbourne.sdk.services.lusid.model.FxTenorConvention;
import com.finbourne.sdk.services.lusid.model.MarketDataOptions;
import com.finbourne.sdk.services.lusid.model.Version;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Contains data (i.e. tenors and rates + metadata) for building fx forward curves (when combined with a date to build on)
 */
@JsonPropertyOrder({
  FxForwardCurveByQuoteReference.JSON_PROPERTY_DOM_CCY,
  FxForwardCurveByQuoteReference.JSON_PROPERTY_FGN_CCY,
  FxForwardCurveByQuoteReference.JSON_PROPERTY_TENORS,
  FxForwardCurveByQuoteReference.JSON_PROPERTY_QUOTE_REFERENCES,
  FxForwardCurveByQuoteReference.JSON_PROPERTY_LINEAGE,
  FxForwardCurveByQuoteReference.JSON_PROPERTY_MARKET_DATA_OPTIONS,
  FxForwardCurveByQuoteReference.JSON_PROPERTY_CALENDARS,
  FxForwardCurveByQuoteReference.JSON_PROPERTY_SPOT_DAYS_CALCULATION_TYPE,
  FxForwardCurveByQuoteReference.JSON_PROPERTY_VERSION
})

@com.fasterxml.jackson.annotation.JsonIgnoreProperties(
  value = "marketDataType", // ignore manually set marketDataType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the marketDataType to be set during deserialization
)
@com.fasterxml.jackson.annotation.JsonTypeInfo(use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, include = com.fasterxml.jackson.annotation.JsonTypeInfo.As.PROPERTY, property = "marketDataType", visible = true)

public class FxForwardCurveByQuoteReference extends ComplexMarketData {
  public static final String JSON_PROPERTY_DOM_CCY = "domCcy";
  @JsonProperty(JSON_PROPERTY_DOM_CCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String domCcy;

  public static final String JSON_PROPERTY_FGN_CCY = "fgnCcy";
  @JsonProperty(JSON_PROPERTY_FGN_CCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String fgnCcy;

  public static final String JSON_PROPERTY_TENORS = "tenors";
  @JsonProperty(JSON_PROPERTY_TENORS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<String> tenors = new ArrayList<>();

  public static final String JSON_PROPERTY_QUOTE_REFERENCES = "quoteReferences";
  @JsonProperty(JSON_PROPERTY_QUOTE_REFERENCES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<Map<String, String>> quoteReferences = new ArrayList<>();

  public static final String JSON_PROPERTY_LINEAGE = "lineage";
  @JsonProperty(JSON_PROPERTY_LINEAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String lineage;

  public static final String JSON_PROPERTY_MARKET_DATA_OPTIONS = "marketDataOptions";
  @JsonProperty(JSON_PROPERTY_MARKET_DATA_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private MarketDataOptions marketDataOptions;

  public static final String JSON_PROPERTY_CALENDARS = "calendars";
  @JsonProperty(JSON_PROPERTY_CALENDARS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<FxTenorConvention> calendars;

  public static final String JSON_PROPERTY_SPOT_DAYS_CALCULATION_TYPE = "spotDaysCalculationType";
  @JsonProperty(JSON_PROPERTY_SPOT_DAYS_CALCULATION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String spotDaysCalculationType;

  public static final String JSON_PROPERTY_VERSION = "version";
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Version version;

  public FxForwardCurveByQuoteReference() {
  }

  public FxForwardCurveByQuoteReference domCcy(String domCcy) {
    this.domCcy = domCcy;
    return this;
  }

  /**
   * Domestic currency of the fx forward
   * @return domCcy
   */
  @javax.annotation.Nonnull
  public String getDomCcy() {
    return domCcy;
  }

  public void setDomCcy(String domCcy) {
    this.domCcy = domCcy;
  }


  public FxForwardCurveByQuoteReference fgnCcy(String fgnCcy) {
    this.fgnCcy = fgnCcy;
    return this;
  }

  /**
   * Foreign currency of the fx forward
   * @return fgnCcy
   */
  @javax.annotation.Nonnull
  public String getFgnCcy() {
    return fgnCcy;
  }

  public void setFgnCcy(String fgnCcy) {
    this.fgnCcy = fgnCcy;
  }


  public FxForwardCurveByQuoteReference tenors(List<String> tenors) {
    this.tenors = tenors;
    return this;
  }

  public FxForwardCurveByQuoteReference addTenorsItem(String tenorsItem) {
    if (this.tenors == null) {
      this.tenors = new ArrayList<>();
    }
    this.tenors.add(tenorsItem);
    return this;
  }

  /**
   * Tenors for which the forward rates apply.  For more information on tenors, see [knowledge base article KA-02097](https://support.lusid.com/knowledgebase/article/KA-02097)
   * @return tenors
   */
  @javax.annotation.Nonnull
  public List<String> getTenors() {
    return tenors;
  }

  public void setTenors(List<String> tenors) {
    this.tenors = tenors;
  }


  public FxForwardCurveByQuoteReference quoteReferences(List<Map<String, String>> quoteReferences) {
    this.quoteReferences = quoteReferences;
    return this;
  }

  public FxForwardCurveByQuoteReference addQuoteReferencesItem(Map<String, String> quoteReferencesItem) {
    if (this.quoteReferences == null) {
      this.quoteReferences = new ArrayList<>();
    }
    this.quoteReferences.add(quoteReferencesItem);
    return this;
  }

  /**
   * For each tenor, a collection of identifiers. These will be looked up in the LUSID Quote Store to resolve the actual rates.  Accepts an array of Dictionary&lt;string, string&gt;. The keys of each dictionary must be chosen from the following enumeration:  [LusidInstrumentId, Isin, Sedol, Cusip, ClientInternal, Figi, RIC, QuotePermId, REDCode, BBGId, ICECode].  For example:    \&quot;quoteReferences\&quot;: [{\&quot;ClientInternal\&quot;: \&quot;SomeIdentifierForFirstTenor\&quot;},{\&quot;ClientInternal\&quot;: \&quot;SomeIdentifierForSecondTenor\&quot;}
   * @return quoteReferences
   */
  @javax.annotation.Nonnull
  public List<Map<String, String>> getQuoteReferences() {
    return quoteReferences;
  }

  public void setQuoteReferences(List<Map<String, String>> quoteReferences) {
    this.quoteReferences = quoteReferences;
  }


  public FxForwardCurveByQuoteReference lineage(String lineage) {
    this.lineage = lineage;
    return this;
  }

  /**
   * Description of the complex market data&#39;s lineage e.g. &#39;FundAccountant_GreenQuality&#39;.
   * @return lineage
   */
  @javax.annotation.Nullable
  public String getLineage() {
    return lineage;
  }

  public void setLineage(String lineage) {
    this.lineage = lineage;
  }


  public FxForwardCurveByQuoteReference marketDataOptions(MarketDataOptions marketDataOptions) {
    this.marketDataOptions = marketDataOptions;
    return this;
  }

  /**
   * Get marketDataOptions
   * @return marketDataOptions
   */
  @javax.annotation.Nullable
  public MarketDataOptions getMarketDataOptions() {
    return marketDataOptions;
  }

  public void setMarketDataOptions(MarketDataOptions marketDataOptions) {
    this.marketDataOptions = marketDataOptions;
  }


  public FxForwardCurveByQuoteReference calendars(List<FxTenorConvention> calendars) {
    this.calendars = calendars;
    return this;
  }

  public FxForwardCurveByQuoteReference addCalendarsItem(FxTenorConvention calendarsItem) {
    if (this.calendars == null) {
      this.calendars = new ArrayList<>();
    }
    this.calendars.add(calendarsItem);
    return this;
  }

  /**
   * The list of conventions that should be used when interpreting tenors as dates.
   * @return calendars
   */
  @javax.annotation.Nullable
  public List<FxTenorConvention> getCalendars() {
    return calendars;
  }

  public void setCalendars(List<FxTenorConvention> calendars) {
    this.calendars = calendars;
  }


  public FxForwardCurveByQuoteReference spotDaysCalculationType(String spotDaysCalculationType) {
    this.spotDaysCalculationType = spotDaysCalculationType;
    return this;
  }

  /**
   * Configures how to calculate the spot date from the build date using the Calendars provided. Available values: SingleCalendar, UnionCalendars.
   * @return spotDaysCalculationType
   */
  @javax.annotation.Nullable
  public String getSpotDaysCalculationType() {
    return spotDaysCalculationType;
  }

  public void setSpotDaysCalculationType(String spotDaysCalculationType) {
    this.spotDaysCalculationType = spotDaysCalculationType;
  }


  public FxForwardCurveByQuoteReference version(Version version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nullable
  public Version getVersion() {
    return version;
  }

  public void setVersion(Version version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FxForwardCurveByQuoteReference fxForwardCurveByQuoteReference = (FxForwardCurveByQuoteReference) o;
    return Objects.equals(this.domCcy, fxForwardCurveByQuoteReference.domCcy) &&
        Objects.equals(this.fgnCcy, fxForwardCurveByQuoteReference.fgnCcy) &&
        Objects.equals(this.tenors, fxForwardCurveByQuoteReference.tenors) &&
        Objects.equals(this.quoteReferences, fxForwardCurveByQuoteReference.quoteReferences) &&
        Objects.equals(this.lineage, fxForwardCurveByQuoteReference.lineage) &&
        Objects.equals(this.marketDataOptions, fxForwardCurveByQuoteReference.marketDataOptions) &&
        Objects.equals(this.calendars, fxForwardCurveByQuoteReference.calendars) &&
        Objects.equals(this.spotDaysCalculationType, fxForwardCurveByQuoteReference.spotDaysCalculationType) &&
        Objects.equals(this.version, fxForwardCurveByQuoteReference.version) &&
        super.equals(o);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(domCcy, fgnCcy, tenors, quoteReferences, lineage, marketDataOptions, calendars, spotDaysCalculationType, version, super.hashCode());
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FxForwardCurveByQuoteReference {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    domCcy: ").append(toIndentedString(domCcy)).append("\n");
    sb.append("    fgnCcy: ").append(toIndentedString(fgnCcy)).append("\n");
    sb.append("    tenors: ").append(toIndentedString(tenors)).append("\n");
    sb.append("    quoteReferences: ").append(toIndentedString(quoteReferences)).append("\n");
    sb.append("    lineage: ").append(toIndentedString(lineage)).append("\n");
    sb.append("    marketDataOptions: ").append(toIndentedString(marketDataOptions)).append("\n");
    sb.append("    calendars: ").append(toIndentedString(calendars)).append("\n");
    sb.append("    spotDaysCalculationType: ").append(toIndentedString(spotDaysCalculationType)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of FxForwardCurveByQuoteReference given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FxForwardCurveByQuoteReference
   * @throws java.io.IOException if the JSON string is invalid with respect to FxForwardCurveByQuoteReference
   */
  public static FxForwardCurveByQuoteReference fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, FxForwardCurveByQuoteReference.class);
  }

  /**
   * Convert an instance of FxForwardCurveByQuoteReference to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
