/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.ComplexMarketData;
import com.finbourne.sdk.services.lusid.model.LusidInstrument;
import com.finbourne.sdk.services.lusid.model.MarketQuote;
import com.finbourne.sdk.services.lusid.model.Version;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Market Data for an fx vol surface, represented by a list of fx options and corresponding market quotes
 */
@JsonPropertyOrder({
  FxVolSurfaceData.JSON_PROPERTY_BASE_DATE,
  FxVolSurfaceData.JSON_PROPERTY_INSTRUMENTS,
  FxVolSurfaceData.JSON_PROPERTY_QUOTES,
  FxVolSurfaceData.JSON_PROPERTY_LINEAGE,
  FxVolSurfaceData.JSON_PROPERTY_VERSION
})

@com.fasterxml.jackson.annotation.JsonIgnoreProperties(
  value = "marketDataType", // ignore manually set marketDataType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the marketDataType to be set during deserialization
)
@com.fasterxml.jackson.annotation.JsonTypeInfo(use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, include = com.fasterxml.jackson.annotation.JsonTypeInfo.As.PROPERTY, property = "marketDataType", visible = true)

public class FxVolSurfaceData extends ComplexMarketData {
  public static final String JSON_PROPERTY_BASE_DATE = "baseDate";
  @JsonProperty(JSON_PROPERTY_BASE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OffsetDateTime baseDate;

  public static final String JSON_PROPERTY_INSTRUMENTS = "instruments";
  @JsonProperty(JSON_PROPERTY_INSTRUMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<LusidInstrument> instruments = new ArrayList<>();

  public static final String JSON_PROPERTY_QUOTES = "quotes";
  @JsonProperty(JSON_PROPERTY_QUOTES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<MarketQuote> quotes = new ArrayList<>();

  public static final String JSON_PROPERTY_LINEAGE = "lineage";
  @JsonProperty(JSON_PROPERTY_LINEAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String lineage;

  public static final String JSON_PROPERTY_VERSION = "version";
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Version version;

  public FxVolSurfaceData() {
  }

  public FxVolSurfaceData baseDate(OffsetDateTime baseDate) {
    this.baseDate = baseDate;
    return this;
  }

  /**
   * Base date of the surface
   * @return baseDate
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getBaseDate() {
    return baseDate;
  }

  public void setBaseDate(OffsetDateTime baseDate) {
    this.baseDate = baseDate;
  }


  public FxVolSurfaceData instruments(List<LusidInstrument> instruments) {
    this.instruments = instruments;
    return this;
  }

  public FxVolSurfaceData addInstrumentsItem(LusidInstrument instrumentsItem) {
    if (this.instruments == null) {
      this.instruments = new ArrayList<>();
    }
    this.instruments.add(instrumentsItem);
    return this;
  }

  /**
   * The set of instruments that define the surface.
   * @return instruments
   */
  @javax.annotation.Nonnull
  public List<LusidInstrument> getInstruments() {
    return instruments;
  }

  public void setInstruments(List<LusidInstrument> instruments) {
    this.instruments = instruments;
  }


  public FxVolSurfaceData quotes(List<MarketQuote> quotes) {
    this.quotes = quotes;
    return this;
  }

  public FxVolSurfaceData addQuotesItem(MarketQuote quotesItem) {
    if (this.quotes == null) {
      this.quotes = new ArrayList<>();
    }
    this.quotes.add(quotesItem);
    return this;
  }

  /**
   * The set of market quotes that define the surface, in NormalVol or LogNormalVol terms.
   * @return quotes
   */
  @javax.annotation.Nonnull
  public List<MarketQuote> getQuotes() {
    return quotes;
  }

  public void setQuotes(List<MarketQuote> quotes) {
    this.quotes = quotes;
  }


  public FxVolSurfaceData lineage(String lineage) {
    this.lineage = lineage;
    return this;
  }

  /**
   * Description of the complex market data&#39;s lineage e.g. &#39;FundAccountant_GreenQuality&#39;.
   * @return lineage
   */
  @javax.annotation.Nullable
  public String getLineage() {
    return lineage;
  }

  public void setLineage(String lineage) {
    this.lineage = lineage;
  }


  public FxVolSurfaceData version(Version version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nullable
  public Version getVersion() {
    return version;
  }

  public void setVersion(Version version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FxVolSurfaceData fxVolSurfaceData = (FxVolSurfaceData) o;
    return Objects.equals(this.baseDate, fxVolSurfaceData.baseDate) &&
        Objects.equals(this.instruments, fxVolSurfaceData.instruments) &&
        Objects.equals(this.quotes, fxVolSurfaceData.quotes) &&
        Objects.equals(this.lineage, fxVolSurfaceData.lineage) &&
        Objects.equals(this.version, fxVolSurfaceData.version) &&
        super.equals(o);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(baseDate, instruments, quotes, lineage, version, super.hashCode());
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FxVolSurfaceData {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    baseDate: ").append(toIndentedString(baseDate)).append("\n");
    sb.append("    instruments: ").append(toIndentedString(instruments)).append("\n");
    sb.append("    quotes: ").append(toIndentedString(quotes)).append("\n");
    sb.append("    lineage: ").append(toIndentedString(lineage)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of FxVolSurfaceData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FxVolSurfaceData
   * @throws java.io.IOException if the JSON string is invalid with respect to FxVolSurfaceData
   */
  public static FxVolSurfaceData fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, FxVolSurfaceData.class);
  }

  /**
   * Convert an instance of FxVolSurfaceData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
