/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * GroupReconciliationDatePair
 */
@JsonPropertyOrder({
  GroupReconciliationDatePair.JSON_PROPERTY_EFFECTIVE_AT,
  GroupReconciliationDatePair.JSON_PROPERTY_AS_AT
})

public class GroupReconciliationDatePair {
  public static final String JSON_PROPERTY_EFFECTIVE_AT = "effectiveAt";
  @JsonProperty(JSON_PROPERTY_EFFECTIVE_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime effectiveAt;

  public static final String JSON_PROPERTY_AS_AT = "asAt";
  @JsonProperty(JSON_PROPERTY_AS_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime asAt;

  public GroupReconciliationDatePair() {
  }

  public GroupReconciliationDatePair effectiveAt(OffsetDateTime effectiveAt) {
    this.effectiveAt = effectiveAt;
    return this;
  }

  /**
   * The effective at date for the reconciliation
   * @return effectiveAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getEffectiveAt() {
    return effectiveAt;
  }

  public void setEffectiveAt(OffsetDateTime effectiveAt) {
    this.effectiveAt = effectiveAt;
  }


  public GroupReconciliationDatePair asAt(OffsetDateTime asAt) {
    this.asAt = asAt;
    return this;
  }

  /**
   * The as at date for the reconciliation
   * @return asAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getAsAt() {
    return asAt;
  }

  public void setAsAt(OffsetDateTime asAt) {
    this.asAt = asAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupReconciliationDatePair groupReconciliationDatePair = (GroupReconciliationDatePair) o;
    return Objects.equals(this.effectiveAt, groupReconciliationDatePair.effectiveAt) &&
        Objects.equals(this.asAt, groupReconciliationDatePair.asAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(effectiveAt, asAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupReconciliationDatePair {\n");
    sb.append("    effectiveAt: ").append(toIndentedString(effectiveAt)).append("\n");
    sb.append("    asAt: ").append(toIndentedString(asAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of GroupReconciliationDatePair given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GroupReconciliationDatePair
   * @throws java.io.IOException if the JSON string is invalid with respect to GroupReconciliationDatePair
   */
  public static GroupReconciliationDatePair fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, GroupReconciliationDatePair.class);
  }

  /**
   * Convert an instance of GroupReconciliationDatePair to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
