/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import java.util.Objects;

import java.io.IOException;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets InstrumentType
 */
public enum InstrumentType {
  
  QUOTED_SECURITY("QuotedSecurity"),
  
  INTEREST_RATE_SWAP("InterestRateSwap"),
  
  FX_FORWARD("FxForward"),
  
  FUTURE("Future"),
  
  EXOTIC_INSTRUMENT("ExoticInstrument"),
  
  FX_OPTION("FxOption"),
  
  CREDIT_DEFAULT_SWAP("CreditDefaultSwap"),
  
  INTEREST_RATE_SWAPTION("InterestRateSwaption"),
  
  BOND("Bond"),
  
  EQUITY_OPTION("EquityOption"),
  
  FIXED_LEG("FixedLeg"),
  
  FLOATING_LEG("FloatingLeg"),
  
  BESPOKE_CASH_FLOWS_LEG("BespokeCashFlowsLeg"),
  
  UNKNOWN("Unknown"),
  
  TERM_DEPOSIT("TermDeposit"),
  
  CONTRACT_FOR_DIFFERENCE("ContractForDifference"),
  
  EQUITY_SWAP("EquitySwap"),
  
  CASH_PERPETUAL("CashPerpetual"),
  
  CAP_FLOOR("CapFloor"),
  
  CASH_SETTLED("CashSettled"),
  
  CDS_INDEX("CdsIndex"),
  
  BASKET("Basket"),
  
  FUNDING_LEG("FundingLeg"),
  
  FX_SWAP("FxSwap"),
  
  FORWARD_RATE_AGREEMENT("ForwardRateAgreement"),
  
  SIMPLE_INSTRUMENT("SimpleInstrument"),
  
  REPO("Repo"),
  
  EQUITY("Equity"),
  
  EXCHANGE_TRADED_OPTION("ExchangeTradedOption"),
  
  REFERENCE_INSTRUMENT("ReferenceInstrument"),
  
  COMPLEX_BOND("ComplexBond"),
  
  INFLATION_LINKED_BOND("InflationLinkedBond"),
  
  INFLATION_SWAP("InflationSwap"),
  
  SIMPLE_CASH_FLOW_LOAN("SimpleCashFlowLoan"),
  
  TOTAL_RETURN_SWAP("TotalReturnSwap"),
  
  INFLATION_LEG("InflationLeg"),
  
  FUND_SHARE_CLASS("FundShareClass"),
  
  FLEXIBLE_LOAN("FlexibleLoan"),
  
  UNSETTLED_CASH("UnsettledCash"),
  
  CASH("Cash"),
  
  MASTERED_INSTRUMENT("MasteredInstrument"),
  
  LOAN_FACILITY("LoanFacility"),
  
  FLEXIBLE_DEPOSIT("FlexibleDeposit"),
  
  FLEXIBLE_REPO("FlexibleRepo");

  private String value;

  InstrumentType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static InstrumentType fromValue(String value) {
    for (InstrumentType b : InstrumentType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
