/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import java.io.IOException;
import java.util.Arrays;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * InstrumentSearchProperty
 */
@JsonPropertyOrder({
  InstrumentSearchProperty.JSON_PROPERTY_KEY,
  InstrumentSearchProperty.JSON_PROPERTY_VALUE
})

public class InstrumentSearchProperty {
  public static final String JSON_PROPERTY_KEY = "key";
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String key;

  public static final String JSON_PROPERTY_VALUE = "value";
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String value;

  public InstrumentSearchProperty() {
  }

  public InstrumentSearchProperty key(String key) {
    this.key = key;
    return this;
  }

  /**
   * The property key of instrument property to search for. This will be from the &#39;Instrument&#39; domain and will take the format {domain}/{scope}/{code} e.g. &#39;Instrument/system/Isin&#39; or &#39;Instrument/MyScope/AssetClass&#39;.
   * @return key
   */
  @javax.annotation.Nonnull
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }


  public InstrumentSearchProperty value(String value) {
    this.value = value;
    return this;
  }

  /**
   * The value of the property e.g. &#39;US0378331005&#39; or &#39;Equity&#39;.
   * @return value
   */
  @javax.annotation.Nonnull
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstrumentSearchProperty instrumentSearchProperty = (InstrumentSearchProperty) o;
    return Objects.equals(this.key, instrumentSearchProperty.key) &&
        Objects.equals(this.value, instrumentSearchProperty.value);
  }

  @Override
 public int hashCode() {
    return Objects.hash(key, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstrumentSearchProperty {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of InstrumentSearchProperty given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InstrumentSearchProperty
   * @throws java.io.IOException if the JSON string is invalid with respect to InstrumentSearchProperty
   */
  public static InstrumentSearchProperty fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, InstrumentSearchProperty.class);
  }

  /**
   * Convert an instance of InstrumentSearchProperty to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
