/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * The lineage of the event value
 */
@JsonPropertyOrder({
  LifeCycleEventLineage.JSON_PROPERTY_EVENT_TYPE,
  LifeCycleEventLineage.JSON_PROPERTY_INSTRUMENT_TYPE,
  LifeCycleEventLineage.JSON_PROPERTY_INSTRUMENT_ID,
  LifeCycleEventLineage.JSON_PROPERTY_LEG_ID,
  LifeCycleEventLineage.JSON_PROPERTY_SOURCE_TRANSACTION_ID
})

public class LifeCycleEventLineage {
  public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String eventType;

  public static final String JSON_PROPERTY_INSTRUMENT_TYPE = "instrumentType";
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String instrumentType;

  public static final String JSON_PROPERTY_INSTRUMENT_ID = "instrumentId";
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String instrumentId;

  public static final String JSON_PROPERTY_LEG_ID = "legId";
  @JsonProperty(JSON_PROPERTY_LEG_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String legId;

  public static final String JSON_PROPERTY_SOURCE_TRANSACTION_ID = "sourceTransactionId";
  @JsonProperty(JSON_PROPERTY_SOURCE_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String sourceTransactionId;

  public LifeCycleEventLineage() {
  }

  public LifeCycleEventLineage eventType(String eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * The type of the event
   * @return eventType
   */
  @javax.annotation.Nullable
  public String getEventType() {
    return eventType;
  }

  public void setEventType(String eventType) {
    this.eventType = eventType;
  }


  public LifeCycleEventLineage instrumentType(String instrumentType) {
    this.instrumentType = instrumentType;
    return this;
  }

  /**
   * The instrument type of the instrument for the event.
   * @return instrumentType
   */
  @javax.annotation.Nullable
  public String getInstrumentType() {
    return instrumentType;
  }

  public void setInstrumentType(String instrumentType) {
    this.instrumentType = instrumentType;
  }


  public LifeCycleEventLineage instrumentId(String instrumentId) {
    this.instrumentId = instrumentId;
    return this;
  }

  /**
   * The LUID of the instrument for the event.
   * @return instrumentId
   */
  @javax.annotation.Nullable
  public String getInstrumentId() {
    return instrumentId;
  }

  public void setInstrumentId(String instrumentId) {
    this.instrumentId = instrumentId;
  }


  public LifeCycleEventLineage legId(String legId) {
    this.legId = legId;
    return this;
  }

  /**
   * Leg id for the event.
   * @return legId
   */
  @javax.annotation.Nullable
  public String getLegId() {
    return legId;
  }

  public void setLegId(String legId) {
    this.legId = legId;
  }


  public LifeCycleEventLineage sourceTransactionId(String sourceTransactionId) {
    this.sourceTransactionId = sourceTransactionId;
    return this;
  }

  /**
   * The source transaction of the instrument for the event.
   * @return sourceTransactionId
   */
  @javax.annotation.Nullable
  public String getSourceTransactionId() {
    return sourceTransactionId;
  }

  public void setSourceTransactionId(String sourceTransactionId) {
    this.sourceTransactionId = sourceTransactionId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LifeCycleEventLineage lifeCycleEventLineage = (LifeCycleEventLineage) o;
    return Objects.equals(this.eventType, lifeCycleEventLineage.eventType) &&
        Objects.equals(this.instrumentType, lifeCycleEventLineage.instrumentType) &&
        Objects.equals(this.instrumentId, lifeCycleEventLineage.instrumentId) &&
        Objects.equals(this.legId, lifeCycleEventLineage.legId) &&
        Objects.equals(this.sourceTransactionId, lifeCycleEventLineage.sourceTransactionId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(eventType, instrumentType, instrumentId, legId, sourceTransactionId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LifeCycleEventLineage {\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    instrumentType: ").append(toIndentedString(instrumentType)).append("\n");
    sb.append("    instrumentId: ").append(toIndentedString(instrumentId)).append("\n");
    sb.append("    legId: ").append(toIndentedString(legId)).append("\n");
    sb.append("    sourceTransactionId: ").append(toIndentedString(sourceTransactionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of LifeCycleEventLineage given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of LifeCycleEventLineage
   * @throws java.io.IOException if the JSON string is invalid with respect to LifeCycleEventLineage
   */
  public static LifeCycleEventLineage fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, LifeCycleEventLineage.class);
  }

  /**
   * Convert an instance of LifeCycleEventLineage to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
