/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.CurrencyAndAmount;
import com.finbourne.sdk.services.lusid.model.LusidInstrument;
import com.finbourne.sdk.services.lusid.model.Property;
import com.finbourne.sdk.services.lusid.model.ResourceId;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * A LUSID Trade Ticket comprising an instrument, a transaction, and a counterparty.
 */
@JsonPropertyOrder({
  LusidTradeTicket.JSON_PROPERTY_TRANSACTION_ID,
  LusidTradeTicket.JSON_PROPERTY_TRANSACTION_TYPE,
  LusidTradeTicket.JSON_PROPERTY_SOURCE,
  LusidTradeTicket.JSON_PROPERTY_TRANSACTION_DATE,
  LusidTradeTicket.JSON_PROPERTY_SETTLEMENT_DATE,
  LusidTradeTicket.JSON_PROPERTY_TOTAL_CONSIDERATION,
  LusidTradeTicket.JSON_PROPERTY_UNITS,
  LusidTradeTicket.JSON_PROPERTY_INSTRUMENT_IDENTIFIERS,
  LusidTradeTicket.JSON_PROPERTY_INSTRUMENT_SCOPE,
  LusidTradeTicket.JSON_PROPERTY_INSTRUMENT_NAME,
  LusidTradeTicket.JSON_PROPERTY_INSTRUMENT_DEFINITION,
  LusidTradeTicket.JSON_PROPERTY_COUNTERPARTY_AGREEMENT_ID,
  LusidTradeTicket.JSON_PROPERTY_COUNTERPARTY,
  LusidTradeTicket.JSON_PROPERTY_INSTRUMENT_PROPERTIES,
  LusidTradeTicket.JSON_PROPERTY_TRANSACTION_PROPERTIES,
  LusidTradeTicket.JSON_PROPERTY_TRADE_TICKET_TYPE
})

public class LusidTradeTicket {
  public static final String JSON_PROPERTY_TRANSACTION_ID = "transactionId";
  @JsonProperty(JSON_PROPERTY_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String transactionId;

  public static final String JSON_PROPERTY_TRANSACTION_TYPE = "transactionType";
  @JsonProperty(JSON_PROPERTY_TRANSACTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String transactionType;

  public static final String JSON_PROPERTY_SOURCE = "source";
  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String source;

  public static final String JSON_PROPERTY_TRANSACTION_DATE = "transactionDate";
  @JsonProperty(JSON_PROPERTY_TRANSACTION_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String transactionDate;

  public static final String JSON_PROPERTY_SETTLEMENT_DATE = "settlementDate";
  @JsonProperty(JSON_PROPERTY_SETTLEMENT_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String settlementDate;

  public static final String JSON_PROPERTY_TOTAL_CONSIDERATION = "totalConsideration";
  @JsonProperty(JSON_PROPERTY_TOTAL_CONSIDERATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private CurrencyAndAmount totalConsideration;

  public static final String JSON_PROPERTY_UNITS = "units";
  @JsonProperty(JSON_PROPERTY_UNITS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private java.math.BigDecimal units;

  public static final String JSON_PROPERTY_INSTRUMENT_IDENTIFIERS = "instrumentIdentifiers";
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_IDENTIFIERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private Map<String, String> instrumentIdentifiers = new HashMap<>();

  public static final String JSON_PROPERTY_INSTRUMENT_SCOPE = "instrumentScope";
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String instrumentScope;

  public static final String JSON_PROPERTY_INSTRUMENT_NAME = "instrumentName";
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String instrumentName;

  public static final String JSON_PROPERTY_INSTRUMENT_DEFINITION = "instrumentDefinition";
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_DEFINITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private LusidInstrument instrumentDefinition;

  public static final String JSON_PROPERTY_COUNTERPARTY_AGREEMENT_ID = "counterpartyAgreementId";
  @JsonProperty(JSON_PROPERTY_COUNTERPARTY_AGREEMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private ResourceId counterpartyAgreementId;

  public static final String JSON_PROPERTY_COUNTERPARTY = "counterparty";
  @JsonProperty(JSON_PROPERTY_COUNTERPARTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String counterparty;

  public static final String JSON_PROPERTY_INSTRUMENT_PROPERTIES = "instrumentProperties";
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<Property> instrumentProperties;

  public static final String JSON_PROPERTY_TRANSACTION_PROPERTIES = "transactionProperties";
  @JsonProperty(JSON_PROPERTY_TRANSACTION_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<Property> transactionProperties;

  /**
   * Available values: LusidTradeTicket, ExternalTradeTicket.
   */
  public enum TradeTicketTypeEnum {
    LUSID_TRADE_TICKET("LusidTradeTicket"),
    
    EXTERNAL_TRADE_TICKET("ExternalTradeTicket");

    private String value;

    TradeTicketTypeEnum(String value) {
      this.value = value;
    }

    @com.fasterxml.jackson.annotation.JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @com.fasterxml.jackson.annotation.JsonCreator
    public static TradeTicketTypeEnum fromValue(String value) {
      for (TradeTicketTypeEnum b : TradeTicketTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_TRADE_TICKET_TYPE = "tradeTicketType";
  @JsonProperty(JSON_PROPERTY_TRADE_TICKET_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private TradeTicketTypeEnum tradeTicketType;

  public LusidTradeTicket() {
  }

  public LusidTradeTicket transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * Transaction ID. Must be unique.
   * @return transactionId
   */
  @javax.annotation.Nonnull
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }


  public LusidTradeTicket transactionType(String transactionType) {
    this.transactionType = transactionType;
    return this;
  }

  /**
   * Type of transaction for processing. Referenced by Transaction Configuration.
   * @return transactionType
   */
  @javax.annotation.Nonnull
  public String getTransactionType() {
    return transactionType;
  }

  public void setTransactionType(String transactionType) {
    this.transactionType = transactionType;
  }


  public LusidTradeTicket source(String source) {
    this.source = source;
    return this;
  }

  /**
   * Transaction Source. Referenced by Transaction Configuration.
   * @return source
   */
  @javax.annotation.Nullable
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }


  public LusidTradeTicket transactionDate(String transactionDate) {
    this.transactionDate = transactionDate;
    return this;
  }

  /**
   * Transaction Date. Date at which transaction is known.
   * @return transactionDate
   */
  @javax.annotation.Nonnull
  public String getTransactionDate() {
    return transactionDate;
  }

  public void setTransactionDate(String transactionDate) {
    this.transactionDate = transactionDate;
  }


  public LusidTradeTicket settlementDate(String settlementDate) {
    this.settlementDate = settlementDate;
    return this;
  }

  /**
   * Transaction settlement. Date at which transaction is finalised and realised into the system.
   * @return settlementDate
   */
  @javax.annotation.Nonnull
  public String getSettlementDate() {
    return settlementDate;
  }

  public void setSettlementDate(String settlementDate) {
    this.settlementDate = settlementDate;
  }


  public LusidTradeTicket totalConsideration(CurrencyAndAmount totalConsideration) {
    this.totalConsideration = totalConsideration;
    return this;
  }

  /**
   * Get totalConsideration
   * @return totalConsideration
   */
  @javax.annotation.Nonnull
  public CurrencyAndAmount getTotalConsideration() {
    return totalConsideration;
  }

  public void setTotalConsideration(CurrencyAndAmount totalConsideration) {
    this.totalConsideration = totalConsideration;
  }


  public LusidTradeTicket units(java.math.BigDecimal units) {
    this.units = units;
    return this;
  }

  /**
   * Number of units in the transaction. For an OTC this is somewhat interchangeable with the quantity booked in the  instrument. As M x N or N x M are equivalent it is advised a client chooses one approach and sticks to it.  Arguably either the unit or holding is best unitised.
   * @return units
   */
  @javax.annotation.Nonnull
  public java.math.BigDecimal getUnits() {
    return units;
  }

  public void setUnits(java.math.BigDecimal units) {
    this.units = units;
  }


  public LusidTradeTicket instrumentIdentifiers(Map<String, String> instrumentIdentifiers) {
    this.instrumentIdentifiers = instrumentIdentifiers;
    return this;
  }

  public LusidTradeTicket putInstrumentIdentifiersItem(String key, String instrumentIdentifiersItem) {
    if (this.instrumentIdentifiers == null) {
      this.instrumentIdentifiers = new HashMap<>();
    }
    this.instrumentIdentifiers.put(key, instrumentIdentifiersItem);
    return this;
  }

  /**
   * Identifiers for the instrument.
   * @return instrumentIdentifiers
   */
  @javax.annotation.Nonnull
  public Map<String, String> getInstrumentIdentifiers() {
    return instrumentIdentifiers;
  }

  public void setInstrumentIdentifiers(Map<String, String> instrumentIdentifiers) {
    this.instrumentIdentifiers = instrumentIdentifiers;
  }


  public LusidTradeTicket instrumentScope(String instrumentScope) {
    this.instrumentScope = instrumentScope;
    return this;
  }

  /**
   * Scope of instrument
   * @return instrumentScope
   */
  @javax.annotation.Nullable
  public String getInstrumentScope() {
    return instrumentScope;
  }

  public void setInstrumentScope(String instrumentScope) {
    this.instrumentScope = instrumentScope;
  }


  public LusidTradeTicket instrumentName(String instrumentName) {
    this.instrumentName = instrumentName;
    return this;
  }

  /**
   * Name of instrument
   * @return instrumentName
   */
  @javax.annotation.Nullable
  public String getInstrumentName() {
    return instrumentName;
  }

  public void setInstrumentName(String instrumentName) {
    this.instrumentName = instrumentName;
  }


  public LusidTradeTicket instrumentDefinition(LusidInstrument instrumentDefinition) {
    this.instrumentDefinition = instrumentDefinition;
    return this;
  }

  /**
   * Get instrumentDefinition
   * @return instrumentDefinition
   */
  @javax.annotation.Nullable
  public LusidInstrument getInstrumentDefinition() {
    return instrumentDefinition;
  }

  public void setInstrumentDefinition(LusidInstrument instrumentDefinition) {
    this.instrumentDefinition = instrumentDefinition;
  }


  public LusidTradeTicket counterpartyAgreementId(ResourceId counterpartyAgreementId) {
    this.counterpartyAgreementId = counterpartyAgreementId;
    return this;
  }

  /**
   * Get counterpartyAgreementId
   * @return counterpartyAgreementId
   */
  @javax.annotation.Nullable
  public ResourceId getCounterpartyAgreementId() {
    return counterpartyAgreementId;
  }

  public void setCounterpartyAgreementId(ResourceId counterpartyAgreementId) {
    this.counterpartyAgreementId = counterpartyAgreementId;
  }


  public LusidTradeTicket counterparty(String counterparty) {
    this.counterparty = counterparty;
    return this;
  }

  /**
   * Counterparty
   * @return counterparty
   */
  @javax.annotation.Nullable
  public String getCounterparty() {
    return counterparty;
  }

  public void setCounterparty(String counterparty) {
    this.counterparty = counterparty;
  }


  public LusidTradeTicket instrumentProperties(List<Property> instrumentProperties) {
    this.instrumentProperties = instrumentProperties;
    return this;
  }

  public LusidTradeTicket addInstrumentPropertiesItem(Property instrumentPropertiesItem) {
    if (this.instrumentProperties == null) {
      this.instrumentProperties = new ArrayList<>();
    }
    this.instrumentProperties.add(instrumentPropertiesItem);
    return this;
  }

  /**
   * Set of instrument properties (as defined by client/user).
   * @return instrumentProperties
   */
  @javax.annotation.Nullable
  public List<Property> getInstrumentProperties() {
    return instrumentProperties;
  }

  public void setInstrumentProperties(List<Property> instrumentProperties) {
    this.instrumentProperties = instrumentProperties;
  }


  public LusidTradeTicket transactionProperties(List<Property> transactionProperties) {
    this.transactionProperties = transactionProperties;
    return this;
  }

  public LusidTradeTicket addTransactionPropertiesItem(Property transactionPropertiesItem) {
    if (this.transactionProperties == null) {
      this.transactionProperties = new ArrayList<>();
    }
    this.transactionProperties.add(transactionPropertiesItem);
    return this;
  }

  /**
   * Set of transaction properties (as defined by client/user).
   * @return transactionProperties
   */
  @javax.annotation.Nullable
  public List<Property> getTransactionProperties() {
    return transactionProperties;
  }

  public void setTransactionProperties(List<Property> transactionProperties) {
    this.transactionProperties = transactionProperties;
  }


  public LusidTradeTicket tradeTicketType(TradeTicketTypeEnum tradeTicketType) {
    this.tradeTicketType = tradeTicketType;
    return this;
  }

  /**
   * Available values: LusidTradeTicket, ExternalTradeTicket.
   * @return tradeTicketType
   */
  @javax.annotation.Nonnull
  public TradeTicketTypeEnum getTradeTicketType() {
    return tradeTicketType;
  }

  public void setTradeTicketType(TradeTicketTypeEnum tradeTicketType) {
    this.tradeTicketType = tradeTicketType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LusidTradeTicket lusidTradeTicket = (LusidTradeTicket) o;
    return Objects.equals(this.transactionId, lusidTradeTicket.transactionId) &&
        Objects.equals(this.transactionType, lusidTradeTicket.transactionType) &&
        Objects.equals(this.source, lusidTradeTicket.source) &&
        Objects.equals(this.transactionDate, lusidTradeTicket.transactionDate) &&
        Objects.equals(this.settlementDate, lusidTradeTicket.settlementDate) &&
        Objects.equals(this.totalConsideration, lusidTradeTicket.totalConsideration) &&
        (this.units == null ? lusidTradeTicket.units == null : (lusidTradeTicket.units != null && this.units.compareTo(lusidTradeTicket.getUnits()) == 0)) &&
        Objects.equals(this.instrumentIdentifiers, lusidTradeTicket.instrumentIdentifiers) &&
        Objects.equals(this.instrumentScope, lusidTradeTicket.instrumentScope) &&
        Objects.equals(this.instrumentName, lusidTradeTicket.instrumentName) &&
        Objects.equals(this.instrumentDefinition, lusidTradeTicket.instrumentDefinition) &&
        Objects.equals(this.counterpartyAgreementId, lusidTradeTicket.counterpartyAgreementId) &&
        Objects.equals(this.counterparty, lusidTradeTicket.counterparty) &&
        Objects.equals(this.instrumentProperties, lusidTradeTicket.instrumentProperties) &&
        Objects.equals(this.transactionProperties, lusidTradeTicket.transactionProperties) &&
        Objects.equals(this.tradeTicketType, lusidTradeTicket.tradeTicketType);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(transactionId, transactionType, source, transactionDate, settlementDate, totalConsideration, units, instrumentIdentifiers, instrumentScope, instrumentName, instrumentDefinition, counterpartyAgreementId, counterparty, instrumentProperties, transactionProperties, tradeTicketType);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LusidTradeTicket {\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    transactionDate: ").append(toIndentedString(transactionDate)).append("\n");
    sb.append("    settlementDate: ").append(toIndentedString(settlementDate)).append("\n");
    sb.append("    totalConsideration: ").append(toIndentedString(totalConsideration)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("    instrumentIdentifiers: ").append(toIndentedString(instrumentIdentifiers)).append("\n");
    sb.append("    instrumentScope: ").append(toIndentedString(instrumentScope)).append("\n");
    sb.append("    instrumentName: ").append(toIndentedString(instrumentName)).append("\n");
    sb.append("    instrumentDefinition: ").append(toIndentedString(instrumentDefinition)).append("\n");
    sb.append("    counterpartyAgreementId: ").append(toIndentedString(counterpartyAgreementId)).append("\n");
    sb.append("    counterparty: ").append(toIndentedString(counterparty)).append("\n");
    sb.append("    instrumentProperties: ").append(toIndentedString(instrumentProperties)).append("\n");
    sb.append("    transactionProperties: ").append(toIndentedString(transactionProperties)).append("\n");
    sb.append("    tradeTicketType: ").append(toIndentedString(tradeTicketType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of LusidTradeTicket given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of LusidTradeTicket
   * @throws java.io.IOException if the JSON string is invalid with respect to LusidTradeTicket
   */
  public static LusidTradeTicket fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, LusidTradeTicket.class);
  }

  /**
   * Convert an instance of LusidTradeTicket to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
