/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.InstrumentEvent;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Definition of an MBS Interest Shortfall Event  This is an event that describes the occurence of a cashflow due to unpaid interest that was deferred and  not capitalised into the outstanding principal balance of a mortgage-backed security.
 */
@JsonPropertyOrder({
  MbsInterestShortfallEvent.JSON_PROPERTY_EX_DATE,
  MbsInterestShortfallEvent.JSON_PROPERTY_PAYMENT_DATE,
  MbsInterestShortfallEvent.JSON_PROPERTY_CURRENCY,
  MbsInterestShortfallEvent.JSON_PROPERTY_INTEREST_PER_UNIT
})

@com.fasterxml.jackson.annotation.JsonIgnoreProperties(
  value = "instrumentEventType", // ignore manually set instrumentEventType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the instrumentEventType to be set during deserialization
)
@com.fasterxml.jackson.annotation.JsonTypeInfo(use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, include = com.fasterxml.jackson.annotation.JsonTypeInfo.As.PROPERTY, property = "instrumentEventType", visible = true)

public class MbsInterestShortfallEvent extends InstrumentEvent {
  public static final String JSON_PROPERTY_EX_DATE = "exDate";
  @JsonProperty(JSON_PROPERTY_EX_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime exDate;

  public static final String JSON_PROPERTY_PAYMENT_DATE = "paymentDate";
  @JsonProperty(JSON_PROPERTY_PAYMENT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime paymentDate;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String currency;

  public static final String JSON_PROPERTY_INTEREST_PER_UNIT = "interestPerUnit";
  @JsonProperty(JSON_PROPERTY_INTEREST_PER_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private java.math.BigDecimal interestPerUnit;

  public MbsInterestShortfallEvent() {
  }

  public MbsInterestShortfallEvent exDate(OffsetDateTime exDate) {
    this.exDate = exDate;
    return this;
  }

  /**
   * The ex date (entitlement date) of the interest payment, usually several weeks prior to the payment date
   * @return exDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getExDate() {
    return exDate;
  }

  public void setExDate(OffsetDateTime exDate) {
    this.exDate = exDate;
  }


  public MbsInterestShortfallEvent paymentDate(OffsetDateTime paymentDate) {
    this.paymentDate = paymentDate;
    return this;
  }

  /**
   * The payment date of the interest
   * @return paymentDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getPaymentDate() {
    return paymentDate;
  }

  public void setPaymentDate(OffsetDateTime paymentDate) {
    this.paymentDate = paymentDate;
  }


  public MbsInterestShortfallEvent currency(String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * The currency in which the interest amount is notated
   * @return currency
   */
  @javax.annotation.Nonnull
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public MbsInterestShortfallEvent interestPerUnit(java.math.BigDecimal interestPerUnit) {
    this.interestPerUnit = interestPerUnit;
    return this;
  }

  /**
   * The amount by which the coupon amount will fall short for each unit of the instrument held on the ex date
   * @return interestPerUnit
   */
  @javax.annotation.Nullable
  public java.math.BigDecimal getInterestPerUnit() {
    return interestPerUnit;
  }

  public void setInterestPerUnit(java.math.BigDecimal interestPerUnit) {
    this.interestPerUnit = interestPerUnit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MbsInterestShortfallEvent mbsInterestShortfallEvent = (MbsInterestShortfallEvent) o;
    return Objects.equals(this.exDate, mbsInterestShortfallEvent.exDate) &&
        Objects.equals(this.paymentDate, mbsInterestShortfallEvent.paymentDate) &&
        Objects.equals(this.currency, mbsInterestShortfallEvent.currency) &&
        (this.interestPerUnit == null ? mbsInterestShortfallEvent.interestPerUnit == null : (mbsInterestShortfallEvent.interestPerUnit != null && this.interestPerUnit.compareTo(mbsInterestShortfallEvent.getInterestPerUnit()) == 0)) &&
        super.equals(o);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(exDate, paymentDate, currency, interestPerUnit, super.hashCode());
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MbsInterestShortfallEvent {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    exDate: ").append(toIndentedString(exDate)).append("\n");
    sb.append("    paymentDate: ").append(toIndentedString(paymentDate)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    interestPerUnit: ").append(toIndentedString(interestPerUnit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of MbsInterestShortfallEvent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MbsInterestShortfallEvent
   * @throws java.io.IOException if the JSON string is invalid with respect to MbsInterestShortfallEvent
   */
  public static MbsInterestShortfallEvent fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, MbsInterestShortfallEvent.class);
  }

  /**
   * Convert an instance of MbsInterestShortfallEvent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
