/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.ResourceId;
import java.io.IOException;
import java.util.Arrays;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * MembershipAmendmentRequest
 */
@JsonPropertyOrder({
  MembershipAmendmentRequest.JSON_PROPERTY_CUSTOM_DATA_MODEL_ID,
  MembershipAmendmentRequest.JSON_PROPERTY_ENTITY_TYPE,
  MembershipAmendmentRequest.JSON_PROPERTY_ENTITY_UNIQUE_ID,
  MembershipAmendmentRequest.JSON_PROPERTY_OPERATION
})

public class MembershipAmendmentRequest {
  public static final String JSON_PROPERTY_CUSTOM_DATA_MODEL_ID = "customDataModelId";
  @JsonProperty(JSON_PROPERTY_CUSTOM_DATA_MODEL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private ResourceId customDataModelId;

  public static final String JSON_PROPERTY_ENTITY_TYPE = "entityType";
  @JsonProperty(JSON_PROPERTY_ENTITY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String entityType;

  public static final String JSON_PROPERTY_ENTITY_UNIQUE_ID = "entityUniqueId";
  @JsonProperty(JSON_PROPERTY_ENTITY_UNIQUE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String entityUniqueId;

  public static final String JSON_PROPERTY_OPERATION = "operation";
  @JsonProperty(JSON_PROPERTY_OPERATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String operation;

  public MembershipAmendmentRequest() {
  }

  public MembershipAmendmentRequest customDataModelId(ResourceId customDataModelId) {
    this.customDataModelId = customDataModelId;
    return this;
  }

  /**
   * Get customDataModelId
   * @return customDataModelId
   */
  @javax.annotation.Nonnull
  public ResourceId getCustomDataModelId() {
    return customDataModelId;
  }

  public void setCustomDataModelId(ResourceId customDataModelId) {
    this.customDataModelId = customDataModelId;
  }


  public MembershipAmendmentRequest entityType(String entityType) {
    this.entityType = entityType;
    return this;
  }

  /**
   * The type of the entity that is being added or removed from the Custom Data Model.
   * @return entityType
   */
  @javax.annotation.Nonnull
  public String getEntityType() {
    return entityType;
  }

  public void setEntityType(String entityType) {
    this.entityType = entityType;
  }


  public MembershipAmendmentRequest entityUniqueId(String entityUniqueId) {
    this.entityUniqueId = entityUniqueId;
    return this;
  }

  /**
   * The entity unique identifier of the entity that is being added or removed from the Custom Data Model.
   * @return entityUniqueId
   */
  @javax.annotation.Nonnull
  public String getEntityUniqueId() {
    return entityUniqueId;
  }

  public void setEntityUniqueId(String entityUniqueId) {
    this.entityUniqueId = entityUniqueId;
  }


  public MembershipAmendmentRequest operation(String operation) {
    this.operation = operation;
    return this;
  }

  /**
   * The operation to be performed on the entity&#39;s membership in the Custom Data Model. Available values: Add, Remove.
   * @return operation
   */
  @javax.annotation.Nonnull
  public String getOperation() {
    return operation;
  }

  public void setOperation(String operation) {
    this.operation = operation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MembershipAmendmentRequest membershipAmendmentRequest = (MembershipAmendmentRequest) o;
    return Objects.equals(this.customDataModelId, membershipAmendmentRequest.customDataModelId) &&
        Objects.equals(this.entityType, membershipAmendmentRequest.entityType) &&
        Objects.equals(this.entityUniqueId, membershipAmendmentRequest.entityUniqueId) &&
        Objects.equals(this.operation, membershipAmendmentRequest.operation);
  }

  @Override
 public int hashCode() {
    return Objects.hash(customDataModelId, entityType, entityUniqueId, operation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MembershipAmendmentRequest {\n");
    sb.append("    customDataModelId: ").append(toIndentedString(customDataModelId)).append("\n");
    sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
    sb.append("    entityUniqueId: ").append(toIndentedString(entityUniqueId)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of MembershipAmendmentRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MembershipAmendmentRequest
   * @throws java.io.IOException if the JSON string is invalid with respect to MembershipAmendmentRequest
   */
  public static MembershipAmendmentRequest fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, MembershipAmendmentRequest.class);
  }

  /**
   * Convert an instance of MembershipAmendmentRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
