/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.OptionEntry;
import com.finbourne.sdk.services.lusid.model.Schedule;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Optionality Schedule represents a class for creation of schedules for optionality (call, put)
 */
@JsonPropertyOrder({
  OptionalitySchedule.JSON_PROPERTY_EXERCISE_TYPE,
  OptionalitySchedule.JSON_PROPERTY_OPTION_ENTRIES,
  OptionalitySchedule.JSON_PROPERTY_OPTION_TYPE
})

@com.fasterxml.jackson.annotation.JsonIgnoreProperties(
  value = "scheduleType", // ignore manually set scheduleType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the scheduleType to be set during deserialization
)
@com.fasterxml.jackson.annotation.JsonTypeInfo(use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, include = com.fasterxml.jackson.annotation.JsonTypeInfo.As.PROPERTY, property = "scheduleType", visible = true)

public class OptionalitySchedule extends Schedule {
  public static final String JSON_PROPERTY_EXERCISE_TYPE = "exerciseType";
  @JsonProperty(JSON_PROPERTY_EXERCISE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String exerciseType;

  public static final String JSON_PROPERTY_OPTION_ENTRIES = "optionEntries";
  @JsonProperty(JSON_PROPERTY_OPTION_ENTRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<OptionEntry> optionEntries;

  public static final String JSON_PROPERTY_OPTION_TYPE = "optionType";
  @JsonProperty(JSON_PROPERTY_OPTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String optionType;

  public OptionalitySchedule() {
  }

  public OptionalitySchedule exerciseType(String exerciseType) {
    this.exerciseType = exerciseType;
    return this;
  }

  /**
   * The exercise type of the optionality schedule (American or European).  For American type, the bond is perpetually callable from a given exercise date until it matures, or the next date in the schedule.  For European type, the bond is only callable on a given exercise date.    Supported string (enumeration) values are: [European, American].  Defaults to \&quot;European\&quot; if not set.
   * @return exerciseType
   */
  @javax.annotation.Nullable
  public String getExerciseType() {
    return exerciseType;
  }

  public void setExerciseType(String exerciseType) {
    this.exerciseType = exerciseType;
  }


  public OptionalitySchedule optionEntries(List<OptionEntry> optionEntries) {
    this.optionEntries = optionEntries;
    return this;
  }

  public OptionalitySchedule addOptionEntriesItem(OptionEntry optionEntriesItem) {
    if (this.optionEntries == null) {
      this.optionEntries = new ArrayList<>();
    }
    this.optionEntries.add(optionEntriesItem);
    return this;
  }

  /**
   * The dates at which the bond call/put may be actioned, and associated strikes.
   * @return optionEntries
   */
  @javax.annotation.Nullable
  public List<OptionEntry> getOptionEntries() {
    return optionEntries;
  }

  public void setOptionEntries(List<OptionEntry> optionEntries) {
    this.optionEntries = optionEntries;
  }


  public OptionalitySchedule optionType(String optionType) {
    this.optionType = optionType;
    return this;
  }

  /**
   * Type of optionality for the schedule.    Supported string (enumeration) values are: [Call, Put].  Defaults to \&quot;Call\&quot; if not set.
   * @return optionType
   */
  @javax.annotation.Nullable
  public String getOptionType() {
    return optionType;
  }

  public void setOptionType(String optionType) {
    this.optionType = optionType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OptionalitySchedule optionalitySchedule = (OptionalitySchedule) o;
    return Objects.equals(this.exerciseType, optionalitySchedule.exerciseType) &&
        Objects.equals(this.optionEntries, optionalitySchedule.optionEntries) &&
        Objects.equals(this.optionType, optionalitySchedule.optionType) &&
        super.equals(o);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(exerciseType, optionEntries, optionType, super.hashCode());
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OptionalitySchedule {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    exerciseType: ").append(toIndentedString(exerciseType)).append("\n");
    sb.append("    optionEntries: ").append(toIndentedString(optionEntries)).append("\n");
    sb.append("    optionType: ").append(toIndentedString(optionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of OptionalitySchedule given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OptionalitySchedule
   * @throws java.io.IOException if the JSON string is invalid with respect to OptionalitySchedule
   */
  public static OptionalitySchedule fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, OptionalitySchedule.class);
  }

  /**
   * Convert an instance of OptionalitySchedule to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
