/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.OrderGraphBlockExecutionDetail;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * OrderGraphBlockExecutionSynopsis
 */
@JsonPropertyOrder({
  OrderGraphBlockExecutionSynopsis.JSON_PROPERTY_QUANTITY,
  OrderGraphBlockExecutionSynopsis.JSON_PROPERTY_AMOUNT,
  OrderGraphBlockExecutionSynopsis.JSON_PROPERTY_DETAILS
})

public class OrderGraphBlockExecutionSynopsis {
  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private java.math.BigDecimal quantity;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private java.math.BigDecimal amount;

  public static final String JSON_PROPERTY_DETAILS = "details";
  @JsonProperty(JSON_PROPERTY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<OrderGraphBlockExecutionDetail> details = new ArrayList<>();

  public OrderGraphBlockExecutionSynopsis() {
  }

  public OrderGraphBlockExecutionSynopsis quantity(java.math.BigDecimal quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * Total number of units executed.
   * @return quantity
   */
  @javax.annotation.Nonnull
  public java.math.BigDecimal getQuantity() {
    return quantity;
  }

  public void setQuantity(java.math.BigDecimal quantity) {
    this.quantity = quantity;
  }


  public OrderGraphBlockExecutionSynopsis amount(java.math.BigDecimal amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Total monetary value executed, derived from the quantity and price of each execution.
   * @return amount
   */
  @javax.annotation.Nullable
  public java.math.BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(java.math.BigDecimal amount) {
    this.amount = amount;
  }


  public OrderGraphBlockExecutionSynopsis details(List<OrderGraphBlockExecutionDetail> details) {
    this.details = details;
    return this;
  }

  public OrderGraphBlockExecutionSynopsis addDetailsItem(OrderGraphBlockExecutionDetail detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<>();
    }
    this.details.add(detailsItem);
    return this;
  }

  /**
   * Identifiers for each execution in this block.
   * @return details
   */
  @javax.annotation.Nonnull
  public List<OrderGraphBlockExecutionDetail> getDetails() {
    return details;
  }

  public void setDetails(List<OrderGraphBlockExecutionDetail> details) {
    this.details = details;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderGraphBlockExecutionSynopsis orderGraphBlockExecutionSynopsis = (OrderGraphBlockExecutionSynopsis) o;
    return (this.quantity == null ? orderGraphBlockExecutionSynopsis.quantity == null : (orderGraphBlockExecutionSynopsis.quantity != null && this.quantity.compareTo(orderGraphBlockExecutionSynopsis.getQuantity()) == 0)) &&
        (this.amount == null ? orderGraphBlockExecutionSynopsis.amount == null : (orderGraphBlockExecutionSynopsis.amount != null && this.amount.compareTo(orderGraphBlockExecutionSynopsis.getAmount()) == 0)) &&
        Objects.equals(this.details, orderGraphBlockExecutionSynopsis.details);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(quantity, amount, details);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderGraphBlockExecutionSynopsis {\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of OrderGraphBlockExecutionSynopsis given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OrderGraphBlockExecutionSynopsis
   * @throws java.io.IOException if the JSON string is invalid with respect to OrderGraphBlockExecutionSynopsis
   */
  public static OrderGraphBlockExecutionSynopsis fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, OrderGraphBlockExecutionSynopsis.class);
  }

  /**
   * Convert an instance of OrderGraphBlockExecutionSynopsis to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
