/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.OrderRuleBreach;
import com.finbourne.sdk.services.lusid.model.ResourceId;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * OrderBreachHistory
 */
@JsonPropertyOrder({
  OrderBreachHistory.JSON_PROPERTY_ID,
  OrderBreachHistory.JSON_PROPERTY_ORDER_ID,
  OrderBreachHistory.JSON_PROPERTY_RUN_ID,
  OrderBreachHistory.JSON_PROPERTY_BREACHES_BY_RULE,
  OrderBreachHistory.JSON_PROPERTY_AS_AT
})

public class OrderBreachHistory {
  public static final String JSON_PROPERTY_ID = "id";
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private ResourceId id;

  public static final String JSON_PROPERTY_ORDER_ID = "orderId";
  @JsonProperty(JSON_PROPERTY_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private ResourceId orderId;

  public static final String JSON_PROPERTY_RUN_ID = "runId";
  @JsonProperty(JSON_PROPERTY_RUN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private ResourceId runId;

  public static final String JSON_PROPERTY_BREACHES_BY_RULE = "breachesByRule";
  @JsonProperty(JSON_PROPERTY_BREACHES_BY_RULE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Map<String, List<OrderRuleBreach>> breachesByRule;

  public static final String JSON_PROPERTY_AS_AT = "asAt";
  @JsonProperty(JSON_PROPERTY_AS_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OffsetDateTime asAt;

  public OrderBreachHistory() {
  }

  public OrderBreachHistory id(ResourceId id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public ResourceId getId() {
    return id;
  }

  public void setId(ResourceId id) {
    this.id = id;
  }


  public OrderBreachHistory orderId(ResourceId orderId) {
    this.orderId = orderId;
    return this;
  }

  /**
   * Get orderId
   * @return orderId
   */
  @javax.annotation.Nonnull
  public ResourceId getOrderId() {
    return orderId;
  }

  public void setOrderId(ResourceId orderId) {
    this.orderId = orderId;
  }


  public OrderBreachHistory runId(ResourceId runId) {
    this.runId = runId;
    return this;
  }

  /**
   * Get runId
   * @return runId
   */
  @javax.annotation.Nonnull
  public ResourceId getRunId() {
    return runId;
  }

  public void setRunId(ResourceId runId) {
    this.runId = runId;
  }


  public OrderBreachHistory breachesByRule(Map<String, List<OrderRuleBreach>> breachesByRule) {
    this.breachesByRule = breachesByRule;
    return this;
  }

  public OrderBreachHistory putBreachesByRuleItem(String key, List<OrderRuleBreach> breachesByRuleItem) {
    if (this.breachesByRule == null) {
      this.breachesByRule = new HashMap<>();
    }
    this.breachesByRule.put(key, breachesByRuleItem);
    return this;
  }

  /**
   * Compliance rule breaches associations with the order and run.
   * @return breachesByRule
   */
  @javax.annotation.Nullable
  public Map<String, List<OrderRuleBreach>> getBreachesByRule() {
    return breachesByRule;
  }

  public void setBreachesByRule(Map<String, List<OrderRuleBreach>> breachesByRule) {
    this.breachesByRule = breachesByRule;
  }


  public OrderBreachHistory asAt(OffsetDateTime asAt) {
    this.asAt = asAt;
    return this;
  }

  /**
   * The asAt datetime at which the order breach was created in LUSID.
   * @return asAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getAsAt() {
    return asAt;
  }

  public void setAsAt(OffsetDateTime asAt) {
    this.asAt = asAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderBreachHistory orderBreachHistory = (OrderBreachHistory) o;
    return Objects.equals(this.id, orderBreachHistory.id) &&
        Objects.equals(this.orderId, orderBreachHistory.orderId) &&
        Objects.equals(this.runId, orderBreachHistory.runId) &&
        Objects.equals(this.breachesByRule, orderBreachHistory.breachesByRule) &&
        Objects.equals(this.asAt, orderBreachHistory.asAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(id, orderId, runId, breachesByRule, asAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderBreachHistory {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    runId: ").append(toIndentedString(runId)).append("\n");
    sb.append("    breachesByRule: ").append(toIndentedString(breachesByRule)).append("\n");
    sb.append("    asAt: ").append(toIndentedString(asAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of OrderBreachHistory given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OrderBreachHistory
   * @throws java.io.IOException if the JSON string is invalid with respect to OrderBreachHistory
   */
  public static OrderBreachHistory fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, OrderBreachHistory.class);
  }

  /**
   * Convert an instance of OrderBreachHistory to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
