/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.NewInstrument;
import java.io.IOException;
import java.util.Arrays;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * A single constituent of a partial closure event for a Flexible Repo. Contains details of the collateral  being exchanged in the Instrument field, represented as a NewInstrument object,  as well as the amount being exchanged and the type of that amount (Units or Percentage of current units).
 */
@JsonPropertyOrder({
  PartialClosureConstituent.JSON_PROPERTY_AMOUNT,
  PartialClosureConstituent.JSON_PROPERTY_AMOUNT_TYPE,
  PartialClosureConstituent.JSON_PROPERTY_INSTRUMENT
})

public class PartialClosureConstituent {
  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private java.math.BigDecimal amount;

  public static final String JSON_PROPERTY_AMOUNT_TYPE = "amountType";
  @JsonProperty(JSON_PROPERTY_AMOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String amountType;

  public static final String JSON_PROPERTY_INSTRUMENT = "instrument";
  @JsonProperty(JSON_PROPERTY_INSTRUMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private NewInstrument instrument;

  public PartialClosureConstituent() {
  }

  public PartialClosureConstituent amount(java.math.BigDecimal amount) {
    this.amount = amount;
    return this;
  }

  /**
   * If AmountType is set to Units, this field represents the number of units of the instrument being exchanged.  If AmountType is set to Percentage, this field represents the percentage of the total repoed units of the instrument being exchanged.  When defining a FlexibleRepoPartialClosureEvent the AmountType can be set to either Units or Percentage,  where Units represents the number of units of the instrument being exchanged, and Percentage represents the  percentage of the total repoed units of the instrument being exchanged in the context of the FlexibleRepo.
   * @return amount
   */
  @javax.annotation.Nonnull
  public java.math.BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(java.math.BigDecimal amount) {
    this.amount = amount;
  }


  public PartialClosureConstituent amountType(String amountType) {
    this.amountType = amountType;
    return this;
  }

  /**
   * The type of amount represented by the Amount field.  I.e., does it represent a number of units or a percentage of the total repoed units of the instrument?  When defining a FlexibleRepoPartialClosureEvent AmountType can be set to either Units or Percentage. Available values: Percentage, Units.
   * @return amountType
   */
  @javax.annotation.Nonnull
  public String getAmountType() {
    return amountType;
  }

  public void setAmountType(String amountType) {
    this.amountType = amountType;
  }


  public PartialClosureConstituent instrument(NewInstrument instrument) {
    this.instrument = instrument;
    return this;
  }

  /**
   * Get instrument
   * @return instrument
   */
  @javax.annotation.Nonnull
  public NewInstrument getInstrument() {
    return instrument;
  }

  public void setInstrument(NewInstrument instrument) {
    this.instrument = instrument;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PartialClosureConstituent partialClosureConstituent = (PartialClosureConstituent) o;
    return (this.amount == null ? partialClosureConstituent.amount == null : (partialClosureConstituent.amount != null && this.amount.compareTo(partialClosureConstituent.getAmount()) == 0)) &&
        Objects.equals(this.amountType, partialClosureConstituent.amountType) &&
        Objects.equals(this.instrument, partialClosureConstituent.instrument);
  }

  @Override
 public int hashCode() {
    return Objects.hash(amount, amountType, instrument);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PartialClosureConstituent {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    amountType: ").append(toIndentedString(amountType)).append("\n");
    sb.append("    instrument: ").append(toIndentedString(instrument)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of PartialClosureConstituent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PartialClosureConstituent
   * @throws java.io.IOException if the JSON string is invalid with respect to PartialClosureConstituent
   */
  public static PartialClosureConstituent fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, PartialClosureConstituent.class);
  }

  /**
   * Convert an instance of PartialClosureConstituent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
