/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.ParticipationRequest;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * A request to create or update multiple Participations.
 */
@JsonPropertyOrder({
  ParticipationSetRequest.JSON_PROPERTY_REQUESTS
})

public class ParticipationSetRequest {
  public static final String JSON_PROPERTY_REQUESTS = "requests";
  @JsonProperty(JSON_PROPERTY_REQUESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<ParticipationRequest> requests;

  public ParticipationSetRequest() {
  }

  public ParticipationSetRequest requests(List<ParticipationRequest> requests) {
    this.requests = requests;
    return this;
  }

  public ParticipationSetRequest addRequestsItem(ParticipationRequest requestsItem) {
    if (this.requests == null) {
      this.requests = new ArrayList<>();
    }
    this.requests.add(requestsItem);
    return this;
  }

  /**
   * A collection of ParticipationRequests.
   * @return requests
   */
  @javax.annotation.Nullable
  public List<ParticipationRequest> getRequests() {
    return requests;
  }

  public void setRequests(List<ParticipationRequest> requests) {
    this.requests = requests;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParticipationSetRequest participationSetRequest = (ParticipationSetRequest) o;
    return Objects.equals(this.requests, participationSetRequest.requests);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(requests);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParticipationSetRequest {\n");
    sb.append("    requests: ").append(toIndentedString(requests)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of ParticipationSetRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ParticipationSetRequest
   * @throws java.io.IOException if the JSON string is invalid with respect to ParticipationSetRequest
   */
  public static ParticipationSetRequest fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, ParticipationSetRequest.class);
  }

  /**
   * Convert an instance of ParticipationSetRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
