/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.HoldingPricingInfo;
import com.finbourne.sdk.services.lusid.model.ModelSelection;
import com.finbourne.sdk.services.lusid.model.PricingOptions;
import com.finbourne.sdk.services.lusid.model.ResultKeyRule;
import com.finbourne.sdk.services.lusid.model.VendorModelRule;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Pricing context node. In order to price an instrument a number of configuration parameters are required to determine which  (a) pricing model (ranging from a simple lookup of a market quote/price through to a Monte-Carlo simulation for the behaviour of its cashflows)  (b) vendor library (Lusid internal models or those provided through an external Vendor such as Refinitiv (proprietary) or QuantLib (open source)  are used in the pricing.    In conjunction with these there are a number of parameters that govern the behaviour of these models. For example, in pricing an Fx volatility  dependent product such as an Fx option, there are various parameters that affect model behaviour for the smile. In Lusid a distinction is made between  those which are understood natively and those which are only held for use with a given vendor-model combination. The problem is that, unlike market  quote data, there are few standards around model descriptions. Hence, apparently similar terminology can be mis-leading; for example in SABR models where  the basic parameters are agreed upon but most practical models have used an approximation with adjustments where the parameters can have wildly different meanings.  To avoid confusion or mis-behaviour in this area, where parameters are not understood to be interchangeable, they are only settable on a per-library per-model  basis, essentially as opaque data that will be given to the Vendor library \&quot;verbatim\&quot; but not used with any other.
 */
@JsonPropertyOrder({
  PricingContext.JSON_PROPERTY_MODEL_RULES,
  PricingContext.JSON_PROPERTY_MODEL_CHOICE,
  PricingContext.JSON_PROPERTY_OPTIONS,
  PricingContext.JSON_PROPERTY_RESULT_DATA_RULES,
  PricingContext.JSON_PROPERTY_HOLDING_PRICING_INFO,
  PricingContext.JSON_PROPERTY_ACCRUAL_DEFINITION
})

public class PricingContext {
  public static final String JSON_PROPERTY_MODEL_RULES = "modelRules";
  @JsonProperty(JSON_PROPERTY_MODEL_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<VendorModelRule> modelRules;

  public static final String JSON_PROPERTY_MODEL_CHOICE = "modelChoice";
  @JsonProperty(JSON_PROPERTY_MODEL_CHOICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Map<String, ModelSelection> modelChoice;

  public static final String JSON_PROPERTY_OPTIONS = "options";
  @JsonProperty(JSON_PROPERTY_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private PricingOptions options;

  public static final String JSON_PROPERTY_RESULT_DATA_RULES = "resultDataRules";
  @JsonProperty(JSON_PROPERTY_RESULT_DATA_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<ResultKeyRule> resultDataRules;

  public static final String JSON_PROPERTY_HOLDING_PRICING_INFO = "holdingPricingInfo";
  @JsonProperty(JSON_PROPERTY_HOLDING_PRICING_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private HoldingPricingInfo holdingPricingInfo;

  public static final String JSON_PROPERTY_ACCRUAL_DEFINITION = "accrualDefinition";
  @JsonProperty(JSON_PROPERTY_ACCRUAL_DEFINITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String accrualDefinition;

  public PricingContext() {
  }

  public PricingContext modelRules(List<VendorModelRule> modelRules) {
    this.modelRules = modelRules;
    return this;
  }

  public PricingContext addModelRulesItem(VendorModelRule modelRulesItem) {
    if (this.modelRules == null) {
      this.modelRules = new ArrayList<>();
    }
    this.modelRules.add(modelRulesItem);
    return this;
  }

  /**
   * The set of model rules that are available. There may be multiple rules for Vendors, but only one per model-instrument pair.  Which of these preference sets is used depends upon the model choice selection if specified, or failing that the global default model specification  in the options.
   * @return modelRules
   */
  @javax.annotation.Nullable
  public List<VendorModelRule> getModelRules() {
    return modelRules;
  }

  public void setModelRules(List<VendorModelRule> modelRules) {
    this.modelRules = modelRules;
  }


  public PricingContext modelChoice(Map<String, ModelSelection> modelChoice) {
    this.modelChoice = modelChoice;
    return this;
  }

  public PricingContext putModelChoiceItem(String key, ModelSelection modelChoiceItem) {
    if (this.modelChoice == null) {
      this.modelChoice = new HashMap<>();
    }
    this.modelChoice.put(key, modelChoiceItem);
    return this;
  }

  /**
   * The choice of which model selection (vendor library, pricing model) to use in evaluation of a given instrument type.
   * @return modelChoice
   */
  @javax.annotation.Nullable
  public Map<String, ModelSelection> getModelChoice() {
    return modelChoice;
  }

  public void setModelChoice(Map<String, ModelSelection> modelChoice) {
    this.modelChoice = modelChoice;
  }


  public PricingContext options(PricingOptions options) {
    this.options = options;
    return this;
  }

  /**
   * Get options
   * @return options
   */
  @javax.annotation.Nullable
  public PricingOptions getOptions() {
    return options;
  }

  public void setOptions(PricingOptions options) {
    this.options = options;
  }


  public PricingContext resultDataRules(List<ResultKeyRule> resultDataRules) {
    this.resultDataRules = resultDataRules;
    return this;
  }

  public PricingContext addResultDataRulesItem(ResultKeyRule resultDataRulesItem) {
    if (this.resultDataRules == null) {
      this.resultDataRules = new ArrayList<>();
    }
    this.resultDataRules.add(resultDataRulesItem);
    return this;
  }

  /**
   * Set of rules that control querying of unit results either for direct queries into aggregation or for  overriding intermediate calculations. For example, a dirty price is made up from a clean price and the accrued interest.  One might consider overriding the accrued interest calculated by a model (perhaps one wants to match an external value or simply disagrees with the  calculated result) and use that in calculation of the dirty price.
   * @return resultDataRules
   */
  @javax.annotation.Nullable
  public List<ResultKeyRule> getResultDataRules() {
    return resultDataRules;
  }

  public void setResultDataRules(List<ResultKeyRule> resultDataRules) {
    this.resultDataRules = resultDataRules;
  }


  public PricingContext holdingPricingInfo(HoldingPricingInfo holdingPricingInfo) {
    this.holdingPricingInfo = holdingPricingInfo;
    return this;
  }

  /**
   * Get holdingPricingInfo
   * @return holdingPricingInfo
   */
  @javax.annotation.Nullable
  public HoldingPricingInfo getHoldingPricingInfo() {
    return holdingPricingInfo;
  }

  public void setHoldingPricingInfo(HoldingPricingInfo holdingPricingInfo) {
    this.holdingPricingInfo = holdingPricingInfo;
  }


  public PricingContext accrualDefinition(String accrualDefinition) {
    this.accrualDefinition = accrualDefinition;
    return this;
  }

  /**
   * Determines which method to use for the calculation of accrued interest. Defaults to SOD.
   * @return accrualDefinition
   */
  @javax.annotation.Nullable
  public String getAccrualDefinition() {
    return accrualDefinition;
  }

  public void setAccrualDefinition(String accrualDefinition) {
    this.accrualDefinition = accrualDefinition;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PricingContext pricingContext = (PricingContext) o;
    return Objects.equals(this.modelRules, pricingContext.modelRules) &&
        Objects.equals(this.modelChoice, pricingContext.modelChoice) &&
        Objects.equals(this.options, pricingContext.options) &&
        Objects.equals(this.resultDataRules, pricingContext.resultDataRules) &&
        Objects.equals(this.holdingPricingInfo, pricingContext.holdingPricingInfo) &&
        Objects.equals(this.accrualDefinition, pricingContext.accrualDefinition);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(modelRules, modelChoice, options, resultDataRules, holdingPricingInfo, accrualDefinition);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PricingContext {\n");
    sb.append("    modelRules: ").append(toIndentedString(modelRules)).append("\n");
    sb.append("    modelChoice: ").append(toIndentedString(modelChoice)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    resultDataRules: ").append(toIndentedString(resultDataRules)).append("\n");
    sb.append("    holdingPricingInfo: ").append(toIndentedString(holdingPricingInfo)).append("\n");
    sb.append("    accrualDefinition: ").append(toIndentedString(accrualDefinition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of PricingContext given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PricingContext
   * @throws java.io.IOException if the JSON string is invalid with respect to PricingContext
   */
  public static PricingContext fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, PricingContext.class);
  }

  /**
   * Convert an instance of PricingContext to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
