/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * A per-side exclusive lower bound on an activity window&#39;s effective range.
 */
@JsonPropertyOrder({
  RecActivitySinceEffectiveAt.JSON_PROPERTY_LEFT,
  RecActivitySinceEffectiveAt.JSON_PROPERTY_RIGHT
})

public class RecActivitySinceEffectiveAt {
  public static final String JSON_PROPERTY_LEFT = "left";
  @JsonProperty(JSON_PROPERTY_LEFT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OffsetDateTime left;

  public static final String JSON_PROPERTY_RIGHT = "right";
  @JsonProperty(JSON_PROPERTY_RIGHT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OffsetDateTime right;

  public RecActivitySinceEffectiveAt() {
  }

  public RecActivitySinceEffectiveAt left(OffsetDateTime left) {
    this.left = left;
    return this;
  }

  /**
   * The exclusive lower bound for the left side. Activity effective at exactly this datetime falls outside the window.
   * @return left
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getLeft() {
    return left;
  }

  public void setLeft(OffsetDateTime left) {
    this.left = left;
  }


  public RecActivitySinceEffectiveAt right(OffsetDateTime right) {
    this.right = right;
    return this;
  }

  /**
   * The exclusive lower bound for the right side. Activity effective at exactly this datetime falls outside the window.
   * @return right
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getRight() {
    return right;
  }

  public void setRight(OffsetDateTime right) {
    this.right = right;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecActivitySinceEffectiveAt recActivitySinceEffectiveAt = (RecActivitySinceEffectiveAt) o;
    return Objects.equals(this.left, recActivitySinceEffectiveAt.left) &&
        Objects.equals(this.right, recActivitySinceEffectiveAt.right);
  }

  @Override
 public int hashCode() {
    return Objects.hash(left, right);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecActivitySinceEffectiveAt {\n");
    sb.append("    left: ").append(toIndentedString(left)).append("\n");
    sb.append("    right: ").append(toIndentedString(right)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of RecActivitySinceEffectiveAt given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RecActivitySinceEffectiveAt
   * @throws java.io.IOException if the JSON string is invalid with respect to RecActivitySinceEffectiveAt
   */
  public static RecActivitySinceEffectiveAt fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, RecActivitySinceEffectiveAt.class);
  }

  /**
   * Convert an instance of RecActivitySinceEffectiveAt to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
