/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * An approval slot required for a result set, passed through from the rec definition&#39;s review configuration.
 */
@JsonPropertyOrder({
  RecRequiredApproval.JSON_PROPERTY_APPROVAL_CODE,
  RecRequiredApproval.JSON_PROPERTY_DESCRIPTION,
  RecRequiredApproval.JSON_PROPERTY_CURRENT_USER_CAN_DECIDE
})

public class RecRequiredApproval {
  public static final String JSON_PROPERTY_APPROVAL_CODE = "approvalCode";
  @JsonProperty(JSON_PROPERTY_APPROVAL_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String approvalCode;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String description;

  public static final String JSON_PROPERTY_CURRENT_USER_CAN_DECIDE = "currentUserCanDecide";
  @JsonProperty(JSON_PROPERTY_CURRENT_USER_CAN_DECIDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Boolean currentUserCanDecide;

  public RecRequiredApproval() {
  }

  public RecRequiredApproval approvalCode(String approvalCode) {
    this.approvalCode = approvalCode;
    return this;
  }

  /**
   * Client-defined identifier for the approval slot (e.g. &#39;Desk&#39;, &#39;Risk&#39;).
   * @return approvalCode
   */
  @javax.annotation.Nonnull
  public String getApprovalCode() {
    return approvalCode;
  }

  public void setApprovalCode(String approvalCode) {
    this.approvalCode = approvalCode;
  }


  public RecRequiredApproval description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Human-readable label for the approval slot.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public RecRequiredApproval currentUserCanDecide(Boolean currentUserCanDecide) {
    this.currentUserCanDecide = currentUserCanDecide;
    return this;
  }

  /**
   * Whether the calling user may decide this approval slot, pre-evaluated at request time.
   * @return currentUserCanDecide
   */
  @javax.annotation.Nullable
  public Boolean getCurrentUserCanDecide() {
    return currentUserCanDecide;
  }

  public void setCurrentUserCanDecide(Boolean currentUserCanDecide) {
    this.currentUserCanDecide = currentUserCanDecide;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecRequiredApproval recRequiredApproval = (RecRequiredApproval) o;
    return Objects.equals(this.approvalCode, recRequiredApproval.approvalCode) &&
        Objects.equals(this.description, recRequiredApproval.description) &&
        Objects.equals(this.currentUserCanDecide, recRequiredApproval.currentUserCanDecide);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(approvalCode, description, currentUserCanDecide);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecRequiredApproval {\n");
    sb.append("    approvalCode: ").append(toIndentedString(approvalCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    currentUserCanDecide: ").append(toIndentedString(currentUserCanDecide)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of RecRequiredApproval given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RecRequiredApproval
   * @throws java.io.IOException if the JSON string is invalid with respect to RecRequiredApproval
   */
  public static RecRequiredApproval fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, RecRequiredApproval.class);
  }

  /**
   * Convert an instance of RecRequiredApproval to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
