/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.AppliedScenarioShift;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Diagnostics for the scenario shifts a valuation applied: every market data target changed by a  shift, with values before and after, plus warnings for market data that matched a shift but could  not honour it. Populated whenever the valuation ran with a request-level scenario or  scenario-decorated metrics; null otherwise. The same material is written to the market data  manifest.
 */
@JsonPropertyOrder({
  ScenarioDiagnostics.JSON_PROPERTY_APPLIED,
  ScenarioDiagnostics.JSON_PROPERTY_SKIPPED,
  ScenarioDiagnostics.JSON_PROPERTY_OMITTED_APPLIED
})

public class ScenarioDiagnostics {
  public static final String JSON_PROPERTY_APPLIED = "applied";
  @JsonProperty(JSON_PROPERTY_APPLIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<AppliedScenarioShift> applied;

  public static final String JSON_PROPERTY_SKIPPED = "skipped";
  @JsonProperty(JSON_PROPERTY_SKIPPED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<String> skipped;

  public static final String JSON_PROPERTY_OMITTED_APPLIED = "omittedApplied";
  @JsonProperty(JSON_PROPERTY_OMITTED_APPLIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Integer omittedApplied;

  public ScenarioDiagnostics() {
  }

  public ScenarioDiagnostics applied(List<AppliedScenarioShift> applied) {
    this.applied = applied;
    return this;
  }

  public ScenarioDiagnostics addAppliedItem(AppliedScenarioShift appliedItem) {
    if (this.applied == null) {
      this.applied = new ArrayList<>();
    }
    this.applied.add(appliedItem);
    return this;
  }

  /**
   * One entry per market data target changed by a shift.
   * @return applied
   */
  @javax.annotation.Nullable
  public List<AppliedScenarioShift> getApplied() {
    return applied;
  }

  public void setApplied(List<AppliedScenarioShift> applied) {
    this.applied = applied;
  }


  public ScenarioDiagnostics skipped(List<String> skipped) {
    this.skipped = skipped;
    return this;
  }

  public ScenarioDiagnostics addSkippedItem(String skippedItem) {
    if (this.skipped == null) {
      this.skipped = new ArrayList<>();
    }
    this.skipped.add(skippedItem);
    return this;
  }

  /**
   * Market data that matched a shift but was skipped (e.g. an element type that does not support  transformation), with the reason. Prefixed with the scenario&#39;s \&quot;scope/code\&quot; reference.
   * @return skipped
   */
  @javax.annotation.Nullable
  public List<String> getSkipped() {
    return skipped;
  }

  public void setSkipped(List<String> skipped) {
    this.skipped = skipped;
  }


  public ScenarioDiagnostics omittedApplied(Integer omittedApplied) {
    this.omittedApplied = omittedApplied;
    return this;
  }

  /**
   * The number of further applied records omitted from this section, when the valuation changed  more targets than the section carries (large portfolios over long schedules). Null when  nothing was omitted. The market data manifest always carries the complete set.
   * @return omittedApplied
   */
  @javax.annotation.Nullable
  public Integer getOmittedApplied() {
    return omittedApplied;
  }

  public void setOmittedApplied(Integer omittedApplied) {
    this.omittedApplied = omittedApplied;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScenarioDiagnostics scenarioDiagnostics = (ScenarioDiagnostics) o;
    return Objects.equals(this.applied, scenarioDiagnostics.applied) &&
        Objects.equals(this.skipped, scenarioDiagnostics.skipped) &&
        Objects.equals(this.omittedApplied, scenarioDiagnostics.omittedApplied);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(applied, skipped, omittedApplied);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScenarioDiagnostics {\n");
    sb.append("    applied: ").append(toIndentedString(applied)).append("\n");
    sb.append("    skipped: ").append(toIndentedString(skipped)).append("\n");
    sb.append("    omittedApplied: ").append(toIndentedString(omittedApplied)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of ScenarioDiagnostics given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ScenarioDiagnostics
   * @throws java.io.IOException if the JSON string is invalid with respect to ScenarioDiagnostics
   */
  public static ScenarioDiagnostics fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, ScenarioDiagnostics.class);
  }

  /**
   * Convert an instance of ScenarioDiagnostics to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
