/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import java.util.Objects;

import java.io.IOException;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Comparison types for strings
 */
public enum StringComparisonType {
  
  EXACT("Exact"),
  
  CONTAINS("Contains"),
  
  CASE_INSENSITIVE("CaseInsensitive"),
  
  CONTAINS_ANY_CASE("ContainsAnyCase"),
  
  IS_ONE_OF("IsOneOf"),
  
  IS_ONE_OF_CASE_INSENSITIVE("IsOneOfCaseInsensitive");

  private String value;

  StringComparisonType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static StringComparisonType fromValue(String value) {
    for (StringComparisonType b : StringComparisonType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
