/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.InstrumentEvent;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Definition of a swap cash flow event.  This event describes the cashflow generated from either an interest rate swap or inflation swap instrument.
 */
@JsonPropertyOrder({
  SwapCashFlowEvent.JSON_PROPERTY_EX_DATE,
  SwapCashFlowEvent.JSON_PROPERTY_PAYMENT_DATE,
  SwapCashFlowEvent.JSON_PROPERTY_CURRENCY,
  SwapCashFlowEvent.JSON_PROPERTY_CASH_FLOW_PER_UNIT
})

@com.fasterxml.jackson.annotation.JsonIgnoreProperties(
  value = "instrumentEventType", // ignore manually set instrumentEventType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the instrumentEventType to be set during deserialization
)
@com.fasterxml.jackson.annotation.JsonTypeInfo(use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, include = com.fasterxml.jackson.annotation.JsonTypeInfo.As.PROPERTY, property = "instrumentEventType", visible = true)

public class SwapCashFlowEvent extends InstrumentEvent {
  public static final String JSON_PROPERTY_EX_DATE = "exDate";
  @JsonProperty(JSON_PROPERTY_EX_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime exDate;

  public static final String JSON_PROPERTY_PAYMENT_DATE = "paymentDate";
  @JsonProperty(JSON_PROPERTY_PAYMENT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private OffsetDateTime paymentDate;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String currency;

  public static final String JSON_PROPERTY_CASH_FLOW_PER_UNIT = "cashFlowPerUnit";
  @JsonProperty(JSON_PROPERTY_CASH_FLOW_PER_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private java.math.BigDecimal cashFlowPerUnit;

  public SwapCashFlowEvent() {
  }

  public SwapCashFlowEvent exDate(OffsetDateTime exDate) {
    this.exDate = exDate;
    return this;
  }

  /**
   * The ex-dividend date of the cashflow.
   * @return exDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getExDate() {
    return exDate;
  }

  public void setExDate(OffsetDateTime exDate) {
    this.exDate = exDate;
  }


  public SwapCashFlowEvent paymentDate(OffsetDateTime paymentDate) {
    this.paymentDate = paymentDate;
    return this;
  }

  /**
   * The payment date of the cashflow.
   * @return paymentDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getPaymentDate() {
    return paymentDate;
  }

  public void setPaymentDate(OffsetDateTime paymentDate) {
    this.paymentDate = paymentDate;
  }


  public SwapCashFlowEvent currency(String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * The currency in which the cashflow is paid.
   * @return currency
   */
  @javax.annotation.Nonnull
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public SwapCashFlowEvent cashFlowPerUnit(java.math.BigDecimal cashFlowPerUnit) {
    this.cashFlowPerUnit = cashFlowPerUnit;
    return this;
  }

  /**
   * The cashflow amount received for each unit of the instrument held on the ex date.
   * @return cashFlowPerUnit
   */
  @javax.annotation.Nullable
  public java.math.BigDecimal getCashFlowPerUnit() {
    return cashFlowPerUnit;
  }

  public void setCashFlowPerUnit(java.math.BigDecimal cashFlowPerUnit) {
    this.cashFlowPerUnit = cashFlowPerUnit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SwapCashFlowEvent swapCashFlowEvent = (SwapCashFlowEvent) o;
    return Objects.equals(this.exDate, swapCashFlowEvent.exDate) &&
        Objects.equals(this.paymentDate, swapCashFlowEvent.paymentDate) &&
        Objects.equals(this.currency, swapCashFlowEvent.currency) &&
        (this.cashFlowPerUnit.compareTo(swapCashFlowEvent.getCashFlowPerUnit()) == 0) &&
        super.equals(o);
  }

  @Override
 public int hashCode() {
    return Objects.hash(exDate, paymentDate, currency, cashFlowPerUnit, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SwapCashFlowEvent {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    exDate: ").append(toIndentedString(exDate)).append("\n");
    sb.append("    paymentDate: ").append(toIndentedString(paymentDate)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    cashFlowPerUnit: ").append(toIndentedString(cashFlowPerUnit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of SwapCashFlowEvent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SwapCashFlowEvent
   * @throws java.io.IOException if the JSON string is invalid with respect to SwapCashFlowEvent
   */
  public static SwapCashFlowEvent fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, SwapCashFlowEvent.class);
  }

  /**
   * Convert an instance of SwapCashFlowEvent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
