/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.Link;
import com.finbourne.sdk.services.lusid.model.ResourceId;
import com.finbourne.sdk.services.lusid.model.TaxRule;
import com.finbourne.sdk.services.lusid.model.Version;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * TaxRuleSet
 */
@JsonPropertyOrder({
  TaxRuleSet.JSON_PROPERTY_ID,
  TaxRuleSet.JSON_PROPERTY_DISPLAY_NAME,
  TaxRuleSet.JSON_PROPERTY_DESCRIPTION,
  TaxRuleSet.JSON_PROPERTY_OUTPUT_PROPERTY_KEY,
  TaxRuleSet.JSON_PROPERTY_RULES,
  TaxRuleSet.JSON_PROPERTY_VERSION,
  TaxRuleSet.JSON_PROPERTY_LINKS
})

public class TaxRuleSet {
  public static final String JSON_PROPERTY_ID = "id";
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private ResourceId id;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String displayName;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String description;

  public static final String JSON_PROPERTY_OUTPUT_PROPERTY_KEY = "outputPropertyKey";
  @JsonProperty(JSON_PROPERTY_OUTPUT_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String outputPropertyKey;

  public static final String JSON_PROPERTY_RULES = "rules";
  @JsonProperty(JSON_PROPERTY_RULES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<TaxRule> rules = new ArrayList<>();

  public static final String JSON_PROPERTY_VERSION = "version";
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Version version;

  public static final String JSON_PROPERTY_LINKS = "links";
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private List<Link> links;

  public TaxRuleSet() {
  }

  public TaxRuleSet id(ResourceId id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public ResourceId getId() {
    return id;
  }

  public void setId(ResourceId id) {
    this.id = id;
  }


  public TaxRuleSet displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * A user-friendly name
   * @return displayName
   */
  @javax.annotation.Nonnull
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  public TaxRuleSet description(String description) {
    this.description = description;
    return this;
  }

  /**
   * A description of what this rule set is for
   * @return description
   */
  @javax.annotation.Nonnull
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public TaxRuleSet outputPropertyKey(String outputPropertyKey) {
    this.outputPropertyKey = outputPropertyKey;
    return this;
  }

  /**
   * The property key that this rule set will write to
   * @return outputPropertyKey
   */
  @javax.annotation.Nonnull
  public String getOutputPropertyKey() {
    return outputPropertyKey;
  }

  public void setOutputPropertyKey(String outputPropertyKey) {
    this.outputPropertyKey = outputPropertyKey;
  }


  public TaxRuleSet rules(List<TaxRule> rules) {
    this.rules = rules;
    return this;
  }

  public TaxRuleSet addRulesItem(TaxRule rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

  /**
   * The rules of this rule set, which stipulate what rate to apply (i.e. write to the OutputPropertyKey) under certain conditions
   * @return rules
   */
  @javax.annotation.Nonnull
  public List<TaxRule> getRules() {
    return rules;
  }

  public void setRules(List<TaxRule> rules) {
    this.rules = rules;
  }


  public TaxRuleSet version(Version version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nullable
  public Version getVersion() {
    return version;
  }

  public void setVersion(Version version) {
    this.version = version;
  }


  public TaxRuleSet links(List<Link> links) {
    this.links = links;
    return this;
  }

  public TaxRuleSet addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @javax.annotation.Nullable
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaxRuleSet taxRuleSet = (TaxRuleSet) o;
    return Objects.equals(this.id, taxRuleSet.id) &&
        Objects.equals(this.displayName, taxRuleSet.displayName) &&
        Objects.equals(this.description, taxRuleSet.description) &&
        Objects.equals(this.outputPropertyKey, taxRuleSet.outputPropertyKey) &&
        Objects.equals(this.rules, taxRuleSet.rules) &&
        Objects.equals(this.version, taxRuleSet.version) &&
        Objects.equals(this.links, taxRuleSet.links);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(id, displayName, description, outputPropertyKey, rules, version, links);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaxRuleSet {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    outputPropertyKey: ").append(toIndentedString(outputPropertyKey)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of TaxRuleSet given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TaxRuleSet
   * @throws java.io.IOException if the JSON string is invalid with respect to TaxRuleSet
   */
  public static TaxRuleSet fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, TaxRuleSet.class);
  }

  /**
   * Convert an instance of TaxRuleSet to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
