/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Touch class for exotic FxOption
 */
@JsonPropertyOrder({
  Touch.JSON_PROPERTY_DIRECTION,
  Touch.JSON_PROPERTY_LEVEL,
  Touch.JSON_PROPERTY_MONITORING,
  Touch.JSON_PROPERTY_TYPE
})

public class Touch {
  public static final String JSON_PROPERTY_DIRECTION = "direction";
  @JsonProperty(JSON_PROPERTY_DIRECTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String direction;

  public static final String JSON_PROPERTY_LEVEL = "level";
  @JsonProperty(JSON_PROPERTY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private java.math.BigDecimal level;

  public static final String JSON_PROPERTY_MONITORING = "monitoring";
  @JsonProperty(JSON_PROPERTY_MONITORING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private String monitoring;

  public static final String JSON_PROPERTY_TYPE = "type";
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String type;

  public Touch() {
  }

  public Touch direction(String direction) {
    this.direction = direction;
    return this;
  }

  /**
   * Supported string (enumeration) values are: [Down, Up].
   * @return direction
   */
  @javax.annotation.Nonnull
  public String getDirection() {
    return direction;
  }

  public void setDirection(String direction) {
    this.direction = direction;
  }


  public Touch level(java.math.BigDecimal level) {
    this.level = level;
    return this;
  }

  /**
   * Trigger level, which the underlying should (or should not) cross/touch.
   * @return level
   */
  @javax.annotation.Nonnull
  public java.math.BigDecimal getLevel() {
    return level;
  }

  public void setLevel(java.math.BigDecimal level) {
    this.level = level;
  }


  public Touch monitoring(String monitoring) {
    this.monitoring = monitoring;
    return this;
  }

  /**
   * Supported string (enumeration) values are: [European, Bermudan, American].  Defaults to \&quot;European\&quot; if not set.
   * @return monitoring
   */
  @javax.annotation.Nullable
  public String getMonitoring() {
    return monitoring;
  }

  public void setMonitoring(String monitoring) {
    this.monitoring = monitoring;
  }


  public Touch type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Supported string (enumeration) values are: [Touch, Notouch].
   * @return type
   */
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Touch touch = (Touch) o;
    return Objects.equals(this.direction, touch.direction) &&
        (this.level == null ? touch.level == null : (touch.level != null && this.level.compareTo(touch.getLevel()) == 0)) &&
        Objects.equals(this.monitoring, touch.monitoring) &&
        Objects.equals(this.type, touch.type);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
 public int hashCode() {
    return Objects.hash(direction, level, monitoring, type);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Touch {\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    monitoring: ").append(toIndentedString(monitoring)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of Touch given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Touch
   * @throws java.io.IOException if the JSON string is invalid with respect to Touch
   */
  public static Touch fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, Touch.class);
  }

  /**
   * Convert an instance of Touch to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
