/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.ScriptMapReference;
import java.io.IOException;
import java.util.Arrays;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Options for overriding default scripted translation configuration.
 */
@JsonPropertyOrder({
  TranslationContext.JSON_PROPERTY_DISABLE_SCRIPTED_TRANSLATION,
  TranslationContext.JSON_PROPERTY_SCRIPT_MAP
})

public class TranslationContext {
  public static final String JSON_PROPERTY_DISABLE_SCRIPTED_TRANSLATION = "disableScriptedTranslation";
  @JsonProperty(JSON_PROPERTY_DISABLE_SCRIPTED_TRANSLATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Boolean disableScriptedTranslation;

  public static final String JSON_PROPERTY_SCRIPT_MAP = "scriptMap";
  @JsonProperty(JSON_PROPERTY_SCRIPT_MAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private ScriptMapReference scriptMap;

  public TranslationContext() {
  }

  public TranslationContext disableScriptedTranslation(Boolean disableScriptedTranslation) {
    this.disableScriptedTranslation = disableScriptedTranslation;
    return this;
  }

  /**
   * Get disableScriptedTranslation
   * @return disableScriptedTranslation
   */
  @javax.annotation.Nullable
  public Boolean getDisableScriptedTranslation() {
    return disableScriptedTranslation;
  }

  public void setDisableScriptedTranslation(Boolean disableScriptedTranslation) {
    this.disableScriptedTranslation = disableScriptedTranslation;
  }


  public TranslationContext scriptMap(ScriptMapReference scriptMap) {
    this.scriptMap = scriptMap;
    return this;
  }

  /**
   * Get scriptMap
   * @return scriptMap
   */
  @javax.annotation.Nullable
  public ScriptMapReference getScriptMap() {
    return scriptMap;
  }

  public void setScriptMap(ScriptMapReference scriptMap) {
    this.scriptMap = scriptMap;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranslationContext translationContext = (TranslationContext) o;
    return Objects.equals(this.disableScriptedTranslation, translationContext.disableScriptedTranslation) &&
        Objects.equals(this.scriptMap, translationContext.scriptMap);
  }

  @Override
 public int hashCode() {
    return Objects.hash(disableScriptedTranslation, scriptMap);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranslationContext {\n");
    sb.append("    disableScriptedTranslation: ").append(toIndentedString(disableScriptedTranslation)).append("\n");
    sb.append("    scriptMap: ").append(toIndentedString(scriptMap)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of TranslationContext given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TranslationContext
   * @throws java.io.IOException if the JSON string is invalid with respect to TranslationContext
   */
  public static TranslationContext fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, TranslationContext.class);
  }

  /**
   * Convert an instance of TranslationContext to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
