/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.CustomEntityFieldDefinition;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * UpdateCustomEntityTypeRequest
 */
@JsonPropertyOrder({
  UpdateCustomEntityTypeRequest.JSON_PROPERTY_DISPLAY_NAME,
  UpdateCustomEntityTypeRequest.JSON_PROPERTY_DESCRIPTION,
  UpdateCustomEntityTypeRequest.JSON_PROPERTY_FIELD_SCHEMA
})

public class UpdateCustomEntityTypeRequest {
  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String displayName;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String description;

  public static final String JSON_PROPERTY_FIELD_SCHEMA = "fieldSchema";
  @JsonProperty(JSON_PROPERTY_FIELD_SCHEMA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<CustomEntityFieldDefinition> fieldSchema = new ArrayList<>();

  public UpdateCustomEntityTypeRequest() {
  }

  public UpdateCustomEntityTypeRequest displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * A display label for the custom entity type.
   * @return displayName
   */
  @javax.annotation.Nonnull
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  public UpdateCustomEntityTypeRequest description(String description) {
    this.description = description;
    return this;
  }

  /**
   * A description for the custom entity type.
   * @return description
   */
  @javax.annotation.Nonnull
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public UpdateCustomEntityTypeRequest fieldSchema(List<CustomEntityFieldDefinition> fieldSchema) {
    this.fieldSchema = fieldSchema;
    return this;
  }

  public UpdateCustomEntityTypeRequest addFieldSchemaItem(CustomEntityFieldDefinition fieldSchemaItem) {
    if (this.fieldSchema == null) {
      this.fieldSchema = new ArrayList<>();
    }
    this.fieldSchema.add(fieldSchemaItem);
    return this;
  }

  /**
   * The description of the fields on the custom entity type.
   * @return fieldSchema
   */
  @javax.annotation.Nonnull
  public List<CustomEntityFieldDefinition> getFieldSchema() {
    return fieldSchema;
  }

  public void setFieldSchema(List<CustomEntityFieldDefinition> fieldSchema) {
    this.fieldSchema = fieldSchema;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateCustomEntityTypeRequest updateCustomEntityTypeRequest = (UpdateCustomEntityTypeRequest) o;
    return Objects.equals(this.displayName, updateCustomEntityTypeRequest.displayName) &&
        Objects.equals(this.description, updateCustomEntityTypeRequest.description) &&
        Objects.equals(this.fieldSchema, updateCustomEntityTypeRequest.fieldSchema);
  }

  @Override
 public int hashCode() {
    return Objects.hash(displayName, description, fieldSchema);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateCustomEntityTypeRequest {\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    fieldSchema: ").append(toIndentedString(fieldSchema)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of UpdateCustomEntityTypeRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateCustomEntityTypeRequest
   * @throws java.io.IOException if the JSON string is invalid with respect to UpdateCustomEntityTypeRequest
   */
  public static UpdateCustomEntityTypeRequest fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, UpdateCustomEntityTypeRequest.class);
  }

  /**
   * Convert an instance of UpdateCustomEntityTypeRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
