/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.EconomicDependency;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * For indicating a dependency on some opaque market data requested by an outside vendor
 */
@JsonPropertyOrder({
  VendorDependency.JSON_PROPERTY_VENDOR_NAME,
  VendorDependency.JSON_PROPERTY_VENDOR_PATH,
  VendorDependency.JSON_PROPERTY_DATE
})

@com.fasterxml.jackson.annotation.JsonIgnoreProperties(
  value = "dependencyType", // ignore manually set dependencyType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the dependencyType to be set during deserialization
)
@com.fasterxml.jackson.annotation.JsonTypeInfo(use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, include = com.fasterxml.jackson.annotation.JsonTypeInfo.As.PROPERTY, property = "dependencyType", visible = true)

public class VendorDependency extends EconomicDependency {
  public static final String JSON_PROPERTY_VENDOR_NAME = "vendorName";
  @JsonProperty(JSON_PROPERTY_VENDOR_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String vendorName;

  public static final String JSON_PROPERTY_VENDOR_PATH = "vendorPath";
  @JsonProperty(JSON_PROPERTY_VENDOR_PATH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<String> vendorPath = new ArrayList<>();

  public static final String JSON_PROPERTY_DATE = "date";
  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OffsetDateTime date;

  public VendorDependency() {
  }

  public VendorDependency vendorName(String vendorName) {
    this.vendorName = vendorName;
    return this;
  }

  /**
   * The name of the outside vendor
   * @return vendorName
   */
  @javax.annotation.Nonnull
  public String getVendorName() {
    return vendorName;
  }

  public void setVendorName(String vendorName) {
    this.vendorName = vendorName;
  }


  public VendorDependency vendorPath(List<String> vendorPath) {
    this.vendorPath = vendorPath;
    return this;
  }

  public VendorDependency addVendorPathItem(String vendorPathItem) {
    if (this.vendorPath == null) {
      this.vendorPath = new ArrayList<>();
    }
    this.vendorPath.add(vendorPathItem);
    return this;
  }

  /**
   * The specific dependency path
   * @return vendorPath
   */
  @javax.annotation.Nonnull
  public List<String> getVendorPath() {
    return vendorPath;
  }

  public void setVendorPath(List<String> vendorPath) {
    this.vendorPath = vendorPath;
  }


  public VendorDependency date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

  /**
   * The effectiveDate of the entity that this is a dependency for.
   * @return date
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VendorDependency vendorDependency = (VendorDependency) o;
    return Objects.equals(this.vendorName, vendorDependency.vendorName) &&
        Objects.equals(this.vendorPath, vendorDependency.vendorPath) &&
        Objects.equals(this.date, vendorDependency.date) &&
        super.equals(o);
  }

  @Override
 public int hashCode() {
    return Objects.hash(vendorName, vendorPath, date, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VendorDependency {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    vendorName: ").append(toIndentedString(vendorName)).append("\n");
    sb.append("    vendorPath: ").append(toIndentedString(vendorPath)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of VendorDependency given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of VendorDependency
   * @throws java.io.IOException if the JSON string is invalid with respect to VendorDependency
   */
  public static VendorDependency fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, VendorDependency.class);
  }

  /**
   * Convert an instance of VendorDependency to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
