/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import com.finbourne.sdk.services.lusid.model.LusidInstrument;
import com.finbourne.sdk.services.lusid.model.Schedule;
import com.finbourne.sdk.services.lusid.model.TimeZoneConventions;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * Whole Loan Facility. A loan facility wholly funded by a single lender: it shares the contractual terms, schedules  and instrument events of a LoanFacility, but ownership is not shared pro-rata across investors, and it is valued  at par rather than from a price quote. Like a LoanFacility, this is a lightweight instrument which acts as a  placeholder for the state that is built from the instrument events, with its contracts modelled via FlexibleLoan  instruments in LUSID.
 */
@JsonPropertyOrder({
  WholeLoanFacility.JSON_PROPERTY_START_DATE,
  WholeLoanFacility.JSON_PROPERTY_MATURITY_DATE,
  WholeLoanFacility.JSON_PROPERTY_DOM_CCY,
  WholeLoanFacility.JSON_PROPERTY_INITIAL_COMMITMENT,
  WholeLoanFacility.JSON_PROPERTY_LOAN_TYPE,
  WholeLoanFacility.JSON_PROPERTY_SCHEDULES,
  WholeLoanFacility.JSON_PROPERTY_TIME_ZONE_CONVENTIONS
})

@com.fasterxml.jackson.annotation.JsonIgnoreProperties(
  value = "instrumentType", // ignore manually set instrumentType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the instrumentType to be set during deserialization
)
@com.fasterxml.jackson.annotation.JsonTypeInfo(use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, include = com.fasterxml.jackson.annotation.JsonTypeInfo.As.PROPERTY, property = "instrumentType", visible = true)

public class WholeLoanFacility extends LusidInstrument {
  public static final String JSON_PROPERTY_START_DATE = "startDate";
  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OffsetDateTime startDate;

  public static final String JSON_PROPERTY_MATURITY_DATE = "maturityDate";
  @JsonProperty(JSON_PROPERTY_MATURITY_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private OffsetDateTime maturityDate;

  public static final String JSON_PROPERTY_DOM_CCY = "domCcy";
  @JsonProperty(JSON_PROPERTY_DOM_CCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String domCcy;

  public static final String JSON_PROPERTY_INITIAL_COMMITMENT = "initialCommitment";
  @JsonProperty(JSON_PROPERTY_INITIAL_COMMITMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private java.math.BigDecimal initialCommitment;

  public static final String JSON_PROPERTY_LOAN_TYPE = "loanType";
  @JsonProperty(JSON_PROPERTY_LOAN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private String loanType;

  public static final String JSON_PROPERTY_SCHEDULES = "schedules";
  @JsonProperty(JSON_PROPERTY_SCHEDULES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  private List<Schedule> schedules = new ArrayList<>();

  public static final String JSON_PROPERTY_TIME_ZONE_CONVENTIONS = "timeZoneConventions";
  @JsonProperty(JSON_PROPERTY_TIME_ZONE_CONVENTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private TimeZoneConventions timeZoneConventions;

  public WholeLoanFacility() {
  }

  public WholeLoanFacility startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

  /**
   * The start date of the instrument. This is normally synonymous with the trade-date.
   * @return startDate
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }


  public WholeLoanFacility maturityDate(OffsetDateTime maturityDate) {
    this.maturityDate = maturityDate;
    return this;
  }

  /**
   * The final maturity date of the instrument. This means the last date on which the instruments makes a payment of any amount.  For the avoidance of doubt, that is not necessarily prior to its last sensitivity date for the purposes of risk; e.g. instruments such as  Constant Maturity Swaps (CMS) often have sensitivities to rates that may well be observed or set prior to the maturity date, but refer to a termination date beyond it.
   * @return maturityDate
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getMaturityDate() {
    return maturityDate;
  }

  public void setMaturityDate(OffsetDateTime maturityDate) {
    this.maturityDate = maturityDate;
  }


  public WholeLoanFacility domCcy(String domCcy) {
    this.domCcy = domCcy;
    return this;
  }

  /**
   * The domestic currency of the instrument.
   * @return domCcy
   */
  @javax.annotation.Nonnull
  public String getDomCcy() {
    return domCcy;
  }

  public void setDomCcy(String domCcy) {
    this.domCcy = domCcy;
  }


  public WholeLoanFacility initialCommitment(java.math.BigDecimal initialCommitment) {
    this.initialCommitment = initialCommitment;
    return this;
  }

  /**
   * The initial commitment for the whole loan facility.
   * @return initialCommitment
   */
  @javax.annotation.Nonnull
  public java.math.BigDecimal getInitialCommitment() {
    return initialCommitment;
  }

  public void setInitialCommitment(java.math.BigDecimal initialCommitment) {
    this.initialCommitment = initialCommitment;
  }


  public WholeLoanFacility loanType(String loanType) {
    this.loanType = loanType;
    return this;
  }

  /**
   * LoanType for this facility. The facility can either be a revolving or a  term loan. Available values: Revolver, TermLoan.
   * @return loanType
   */
  @javax.annotation.Nonnull
  public String getLoanType() {
    return loanType;
  }

  public void setLoanType(String loanType) {
    this.loanType = loanType;
  }


  public WholeLoanFacility schedules(List<Schedule> schedules) {
    this.schedules = schedules;
    return this;
  }

  public WholeLoanFacility addSchedulesItem(Schedule schedulesItem) {
    if (this.schedules == null) {
      this.schedules = new ArrayList<>();
    }
    this.schedules.add(schedulesItem);
    return this;
  }

  /**
   * Repayment schedules for the facility.
   * @return schedules
   */
  @javax.annotation.Nonnull
  public List<Schedule> getSchedules() {
    return schedules;
  }

  public void setSchedules(List<Schedule> schedules) {
    this.schedules = schedules;
  }


  public WholeLoanFacility timeZoneConventions(TimeZoneConventions timeZoneConventions) {
    this.timeZoneConventions = timeZoneConventions;
    return this;
  }

  /**
   * Get timeZoneConventions
   * @return timeZoneConventions
   */
  @javax.annotation.Nullable
  public TimeZoneConventions getTimeZoneConventions() {
    return timeZoneConventions;
  }

  public void setTimeZoneConventions(TimeZoneConventions timeZoneConventions) {
    this.timeZoneConventions = timeZoneConventions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WholeLoanFacility wholeLoanFacility = (WholeLoanFacility) o;
    return Objects.equals(this.startDate, wholeLoanFacility.startDate) &&
        Objects.equals(this.maturityDate, wholeLoanFacility.maturityDate) &&
        Objects.equals(this.domCcy, wholeLoanFacility.domCcy) &&
        (this.initialCommitment == null ? wholeLoanFacility.initialCommitment == null : (wholeLoanFacility.initialCommitment != null && this.initialCommitment.compareTo(wholeLoanFacility.getInitialCommitment()) == 0)) &&
        Objects.equals(this.loanType, wholeLoanFacility.loanType) &&
        Objects.equals(this.schedules, wholeLoanFacility.schedules) &&
        Objects.equals(this.timeZoneConventions, wholeLoanFacility.timeZoneConventions) &&
        super.equals(o);
  }

  @Override
 public int hashCode() {
    return Objects.hash(startDate, maturityDate, domCcy, initialCommitment, loanType, schedules, timeZoneConventions, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WholeLoanFacility {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    maturityDate: ").append(toIndentedString(maturityDate)).append("\n");
    sb.append("    domCcy: ").append(toIndentedString(domCcy)).append("\n");
    sb.append("    initialCommitment: ").append(toIndentedString(initialCommitment)).append("\n");
    sb.append("    loanType: ").append(toIndentedString(loanType)).append("\n");
    sb.append("    schedules: ").append(toIndentedString(schedules)).append("\n");
    sb.append("    timeZoneConventions: ").append(toIndentedString(timeZoneConventions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of WholeLoanFacility given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WholeLoanFacility
   * @throws java.io.IOException if the JSON string is invalid with respect to WholeLoanFacility
   */
  public static WholeLoanFacility fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, WholeLoanFacility.class);
  }

  /**
   * Convert an instance of WholeLoanFacility to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
