/*
 * Merged OpenAPI Specification
 * Merged OpenAPI spec from multiple files
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.sdk.services.lusid.model;

import java.io.IOException;
import java.util.Arrays;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.finbourne.sdk.JSON;

/**
 * The workspace item actions a user is permitted to perform within a workspace.
 */
@JsonPropertyOrder({
  WorkspacePermittedItemActions.JSON_PROPERTY_READ_ITEM,
  WorkspacePermittedItemActions.JSON_PROPERTY_ADD_ITEM,
  WorkspacePermittedItemActions.JSON_PROPERTY_UPDATE_ITEM,
  WorkspacePermittedItemActions.JSON_PROPERTY_DELETE_ITEM
})

public class WorkspacePermittedItemActions {
  public static final String JSON_PROPERTY_READ_ITEM = "readItem";
  @JsonProperty(JSON_PROPERTY_READ_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Boolean readItem;

  public static final String JSON_PROPERTY_ADD_ITEM = "addItem";
  @JsonProperty(JSON_PROPERTY_ADD_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Boolean addItem;

  public static final String JSON_PROPERTY_UPDATE_ITEM = "updateItem";
  @JsonProperty(JSON_PROPERTY_UPDATE_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Boolean updateItem;

  public static final String JSON_PROPERTY_DELETE_ITEM = "deleteItem";
  @JsonProperty(JSON_PROPERTY_DELETE_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  private Boolean deleteItem;

  public WorkspacePermittedItemActions() {
  }

  public WorkspacePermittedItemActions readItem(Boolean readItem) {
    this.readItem = readItem;
    return this;
  }

  /**
   * Whether the user is permitted to read workspace items.
   * @return readItem
   */
  @javax.annotation.Nullable
  public Boolean getReadItem() {
    return readItem;
  }

  public void setReadItem(Boolean readItem) {
    this.readItem = readItem;
  }


  public WorkspacePermittedItemActions addItem(Boolean addItem) {
    this.addItem = addItem;
    return this;
  }

  /**
   * Whether the user is permitted to add workspace items.
   * @return addItem
   */
  @javax.annotation.Nullable
  public Boolean getAddItem() {
    return addItem;
  }

  public void setAddItem(Boolean addItem) {
    this.addItem = addItem;
  }


  public WorkspacePermittedItemActions updateItem(Boolean updateItem) {
    this.updateItem = updateItem;
    return this;
  }

  /**
   * Whether the user is permitted to update workspace items.
   * @return updateItem
   */
  @javax.annotation.Nullable
  public Boolean getUpdateItem() {
    return updateItem;
  }

  public void setUpdateItem(Boolean updateItem) {
    this.updateItem = updateItem;
  }


  public WorkspacePermittedItemActions deleteItem(Boolean deleteItem) {
    this.deleteItem = deleteItem;
    return this;
  }

  /**
   * Whether the user is permitted to delete workspace items.
   * @return deleteItem
   */
  @javax.annotation.Nullable
  public Boolean getDeleteItem() {
    return deleteItem;
  }

  public void setDeleteItem(Boolean deleteItem) {
    this.deleteItem = deleteItem;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkspacePermittedItemActions workspacePermittedItemActions = (WorkspacePermittedItemActions) o;
    return Objects.equals(this.readItem, workspacePermittedItemActions.readItem) &&
        Objects.equals(this.addItem, workspacePermittedItemActions.addItem) &&
        Objects.equals(this.updateItem, workspacePermittedItemActions.updateItem) &&
        Objects.equals(this.deleteItem, workspacePermittedItemActions.deleteItem);
  }

  @Override
 public int hashCode() {
    return Objects.hash(readItem, addItem, updateItem, deleteItem);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkspacePermittedItemActions {\n");
    sb.append("    readItem: ").append(toIndentedString(readItem)).append("\n");
    sb.append("    addItem: ").append(toIndentedString(addItem)).append("\n");
    sb.append("    updateItem: ").append(toIndentedString(updateItem)).append("\n");
    sb.append("    deleteItem: ").append(toIndentedString(deleteItem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Create an instance of WorkspacePermittedItemActions given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WorkspacePermittedItemActions
   * @throws java.io.IOException if the JSON string is invalid with respect to WorkspacePermittedItemActions
   */
  public static WorkspacePermittedItemActions fromJson(String jsonString) throws java.io.IOException {
    return JSON.getMapper().readValue(jsonString, WorkspacePermittedItemActions.class);
  }

  /**
   * Convert an instance of WorkspacePermittedItemActions to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.serialize(this);
  }
}
